### ISSUE TITLE
Artifact downloads should fail on S3 errors

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#100]
During http://buildkitestatus.com/incidents/znhf102jn3xg it was found that:

* Artifact downloads contained the S3 error message, instead of the expected content. They didn't throw any error (and if they did, the build might have still passed because of #88). They should have thrown an error, and failed the build.
* Perhaps to add more protection from this we should "verify" uploaded and downloaded files, just in case there's anything that goes wrong in the process. The artifact upload could send checksum of the original file, and download could use that checksum to verify the file is what was created originally by the team

**Comment by underscorediscovery** [comment]
The checksums are a good idea for peace of mind too.

**Comment by toolmantim** [comment]
Perhaps just checking the S3 status and the bytesize of the file would be enough…

**Comment by keithpitt** [comment]
If artifacts fail to download, the agent will exit with a non 0 exit status, and cause the build to fail.
