### ISSUE TITLE
Agents idle timer with `--disconnect-after-idle-timeout` disconnecting while running jobs on other spawns

### ISSUE THREAD

**Issue by lucas044** [buildkite/agent#1006]
Looks like https://github.com/buildkite/agent/issues/985 and https://github.com/buildkite/agent/issues/1003 were resolved, but now have a weird issue with disconnecting an agent while there is still a job running on one of my `other` spawned agents. The likelyhood is less likey than the above 2 jobs but can still occur and cause scaling issues.

Here is a log output of what occurs:

```
INFO   build.linux-i-0f7ff5055498a6746-1 Agent has been idle for 600 seconds
INFO   build.linux-i-0f7ff5055498a6746-3 Agent has been idle for 600 seconds
INFO   build.linux-i-0f7ff5055498a6746-3 Gracefully stopping agent. Since there is no job running, the agent will disconnect immediately
INFO   build.linux-i-0f7ff5055498a6746-4 Agent has been idle for 600 seconds
INFO   build.linux-i-0f7ff5055498a6746-3 Disconnecting...
INFO   build.linux-i-0f7ff5055498a6746-4 Process with PID: 7360 finished with Exit Status: 0
INFO   build.linux-i-0f7ff5055498a6746-4 Finished job 123456-6cd9-459a-bd73-9ff882bfe0db
INFO   build.linux-i-0f7ff5055498a6746-4 Job finished. Resetting idle timer...
```

Looks like the idle timer should maybe be reset for the internal agent when the job is picked up not when the job has finished?

**Comment by lox** [comment]
Thanks for this, it looks like there are still some race conditions we haven't caught. Will dig into it!
