### ISSUE TITLE
Include version numbers in release file names

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#101]
> Could we add the version tag to the download zip file name?
> I had a whole handful of the same zip (1) (2) (3) and I now just delete them all and download again, but it could be nice

This is how all the rest of open-source software tends to work too… we should probably do the same?

**Comment by keithpitt** [comment]
Ah yeah, this should be pretty easy!

**Comment by keithpitt** [comment]
Fixed in the latest release! https://github.com/buildkite/agent/releases/tag/v1.0-beta.20 :dancers:
