### ISSUE TITLE
git-mirrors permission denied with multiple agents on same host

### ISSUE THREAD

**Issue by HenryCook** [buildkite/agent#1017]
Hey,

We've been playing with `git-mirrors` which is awesome however having problems with them on instances with multiple agents running as it throws permission denied errors when trying to create the lockfile:

```
# Could not acquire lock on "/tmp/buildkite-git-mirrors/name-of-repo.clonelock" (open /tmp/buildkite-git-mirrors/name-of-repo-git.clonelock.996722947: permission denied)
# Trying again in 1s...
# Could not acquire lock on "/tmp/buildkite-git-mirrors/name-of-repo.clonelock" (open /tmp/buildkite-git-mirrors/name-of-repo.clonelock.480326955: permission denied)
# Trying again in 1s.
```

The agent config is:

```
experiment="git-mirrors"
git-mirrors-path="/tmp/buildkite-git-mirrors"
```

The `git-mirrors-path` that is created by the agent is created with `0755` so the other agents are unable to write to the directory:

To get around this we have edited each agent to append it's number to the end of the `git-mirrors-path`:

```
git-mirrors-path="/tmp/buildkite-git-mirrors-<agent_number>"
```

We however feel this is an anti pattern (as per outlined in the experimental features doc) as we will be cloning the repo twice on the same instance, when we are using `git-mirrors` to solve this very issue.

https://github.com/buildkite/agent/blob/master/EXPERIMENTS.md#git-mirrors

> Maintain a single bare git mirror with for each repository on a host that is shared amongst multiple agents and pipelines

Is this working as expected?

**Comment by lox** [comment]
Sorry for the slow reply, can you confirm if you are running your agents with different users?

**Comment by HenryCook** [comment]
Yes, we are running the agents with different users.

**Comment by lox** [comment]
That’s a scenario we hadn’t really considered, what’s the motivation behind privilege separation between multiple parallel agents on the same host? Are they different queues/tags?

**Comment by HenryCook** [comment]
Apologise for the late reply.

We have multiple agents on the same instance as the jobs that run are small and short running so we can reduce the number of instances we run while utilising the resources better.

**Comment by lox** [comment]
That makes lots of sense and is quite common, the uncommon but is having different linux users for each instance of the agent on the host. Am I right in understanding that is the configuration?

**Comment by HenryCook** [comment]
Yes, that is correct.

They are then effectively treated as completely separate agents but on the same host.

**Comment by lox** [comment]
So sounds like the issue there is that default file creation mode for the repository checkouts. We could potentially add a setting that allows that to be customized, or possibly you might be able to set a different `UMASK` environment for your agents.

**Comment by HenryCook** [comment]
Ideally we would prefer not to have to manage `UMASK`s, but that is a possibility.

**Comment by keithduncan** [comment]
I think the best thing we can do in this situation is detect EPERM, treat it as non-retryable, and abort using git-mirrors 🤔

**Comment by HenryCook** [comment]
Thanks for looking into this @keithduncan.

As of around a month ago we are no longer running multiple agents per host so this is no longer an issue for us.

**Comment by ocharles** [comment]
FWIW, all [NixOS](https://nixos.org) users currently have this problem, because NixOS also runs each Buildkite agent as a different user. If that's atypical, I can submit a patch to the NixOS configuration of Buildkite to run only a single user.

**Comment by ocharles** [comment]
I set `core.sharedRepository = group` on the mirror repository, and changed it to be owned by a group common to all agents, and things seem to be working. Will keep an eye on things!
