### ISSUE TITLE
Uploading artifacts within a hidden directory

### ISSUE THREAD

**Issue by lucasteligioridis** [buildkite/agent#1018]
Agent struggles with trying to upload an artifact within a hidden directory or in this case it was a subfolder; can't find the file.

Here is a ls of a file successfully found prior to the upload command:
```
output/.terraform/modules/df8e19bb40b6858a25393345a1e5c5bc
```

Then the upload command:
```
2019-05-20 06:02:37 FATAL  Failed to upload artifacts: open /var/lib/buildkite-agent/builds/default-i-0b6e921d54616be3e-3/my-company/application/output/application/output/.terraform/modules/df8e19bb40b6858a25393345a1e5c5bc: no such file or directory
```

**Comment by keithduncan** [comment]
From your log the `application/output/` path segment is repeated twice, it looks like the relative path passed to `artifact upload` may not have actually existed? 😅 

Hidden or `.` prefixed directories aren’t treated any differently by artifact upload but something else may be causing this error, if you’re still experiencing this let us know and we’ll take a look!
