### ISSUE TITLE
"Failed to scan lines"

### ISSUE THREAD

**Issue by deoxxa** [buildkite/agent#102]
```
2015-03-02 09:54:41 ERROR  Failed to scan lines: (*errors.errorString: bufio.Scanner: token too long)
```

Can't seem to reproduce this, but it might be related to (seemingly) long lines. It happened while I was doing a `docker build`, which ended up pulling down a lot of parent images. this would have involved a ton of escape sequences, and probably not a lot of newlines. Just a guess.

**Comment by deoxxa** [comment]
For reference, the error didn't occur the second time I ran the build. I'll run the agent in debug mode the next time I boot up a fresh CI box (should be later tonight).

**Comment by keithpitt** [comment]
Ah yeah, that could happen. I'll look into fixing it. When you have those ascii progress bars, they tend to output a lot of characters before it outputs a `\n` (which is what I use to determine lines). I'll see what I can do. Thanks for letting me know!
