### ISSUE TITLE
missing /v3 suffix in go.mod

### ISSUE THREAD

**Issue by gracenoah** [buildkite/agent#1026]
For a v3 release, the go.mod file must contain a /v3 suffix. Otherwise anyone trying to use parts of this repo as a library would get the following error: 
```
go: github.com/buildkite/agent/v3@v3.12.0: go.mod has non-.../v3 module path "github.com/buildkite/agent" (and .../v3/go.mod does not exist) at revision v3.12.0
```

**Comment by lox** [comment]
Good point! We'll discuss internally.

**Comment by lox** [comment]
Looks like the other option is branches/tags, which we do:

https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

What version of go are you using?

**Comment by gracenoah** [comment]
I'm using go 1.12.

I think one of us is misunderstanding the recommendation from the docs you linked to.

One thing that I didn't realize until now is that, actually, you need to use the /v3 suffix for internal imports everywhere when you choose to support semantic import versioning.

So the 3 options are:
1. Add /v3 to go.mod and use /v3 everywhere internally -> This works on go versions 1.9.7+, 1.10.3+, 1.11+
2. Move everything to a v3 subdirectory and add /v3 to go.mod -> This is not pretty and I don't think it's a great way of doing things, but works in old go versions.
3. Don't change anything and require importers of the package to add +nocompatible to the end of the version number in their go.mod

I didn't realize 3. is an option! We were just importing it using a commit hash and version 0.0.0. I thought this was the only way, but maybe the situation is not as bad as I thought because of this workaround.

**Comment by lox** [comment]
Apologies @gracenoah, still getting my head around go modules and the best practices for this stuff. I'm inclined to go with option 1 out of that list.

**Comment by gracenoah** [comment]
Bump? Option 1 is the best IMO.

**Comment by lox** [comment]
Apologies @gracenoah, just back from vacation and working through a backlog! Would happily accept a PR if you've got some time to help.

**Comment by sayboras** [comment]
Just came across this issue while playing around with the source code. here is the PR if you guys don't mind

**Comment by sayboras** [comment]
Seems like we can close this one.

**Comment by gracenoah** [comment]
Thanks!
