### ISSUE TITLE
What's the package name in homebrew

### ISSUE THREAD

**Issue by tas50** [buildkite/agent#1027]
The readme says the agent can be installed via homebrew, but doesn't tell you the name of the package to do so. It would be great to get a full command example there.

**Comment by apanzerj** [comment]
https://github.com/buildkite/homebrew-buildkite 

:-D

**Comment by keithduncan** [comment]
Hi @tas50, we now link to the Buildkite Docs from the README and the [macOS specific docs](https://buildkite.com/docs/agent/v3/macos) cover which brew package name to install 😄
