### ISSUE TITLE
Missing quotes in `git submodule foreach`

### ISSUE THREAD

**Issue by morxa** [buildkite/agent#1028]
The sub-command of `git submodule foreach` is not quoted, which results in a failed working directory preparation with git 2.22.0:
```
~~~ Preparing working directory
$ cd <builddir>
# Host "github.com" already in list of known hosts at "/var/lib/buildkite-agent/.ssh/known_hosts"
$ git remote set-url origin git@github.com:carologistics/fawkes-robotino.git
$ git submodule foreach --recursive git clean -ffdqx
Entering 'fawkes'
error: unknown switch `f'
usage: git submodule--helper foreach [--quiet] [--recursive] [--] <command>

    -q, --quiet           Suppress output of entering each submodule command
    --recursive           Recurse into nested submodules

fatal: run_command returned non-zero status while recursing in the nested submodules of fawkes
.
⚠️ Warning: Checkout failed! exit status 128 (Attempt 1/3 Retrying in 2s)
```

This occurs on our CentOS 7 buildhost. It seems like this used to work with older git versions (< 2.22.0).

In any case, quoting the command (as suggested by the manpage) should fix this with all versions of git.

**Comment by jgavris** [comment]
+1, we are also facing this. It's an unfortunately consequence of installing both `git` and `buildkite-agent` from homebrew (at HEAD), neither of which have versioned taps.

**Comment by lox** [comment]
I'll have a look!
