### ISSUE TITLE
Gracefully handle log files that are too large

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#103]
At the moment if the agent server returns a "413 Request Entity Too Large" response, it'll just keep retrying forever… and never know if the job is cancelled… so it just hangs and they have to ctrl-c their agent.

We should handle this in some way.

https://github.com/buildkite/agent/blob/3f732681711e3832e2c02479fb54abe1447379db/buildkite/job.go#L201

One idea: we send the max file size in the response header at the start of the job, or on agent rego, so it knows how big a file it can send. And then if the log is bigger than that number we just send up the last X bytes and a boolean to say if we truncated it? That way we should never hit the 413 in the first place.

**Comment by keithpitt** [comment]
Since we chunk uploads now, this isn't a problem.
