### ISSUE TITLE
Artifact upload fails with path outside working directory

### ISSUE THREAD

**Issue by petercgrant** [buildkite/agent#1043]
Symptom:

> buildkite-agent artifact upload /tmp/bb52024.tar.gz
> --
>   | 2019-07-15 15:47:05 INFO   Found 1 files that match "/tmp/bb52024.tar.gz"
>   | 2019-07-15 15:47:05 INFO   Creating (0-1)/1 artifacts
>   | 2019-07-15 15:47:05 INFO   Uploading artifact cd48a35e-74dd-45a2-a10c-acb3710d0bc4 tmp/bb52024.tar.gz (543205773 bytes)
>   | 2019-07-15 15:47:05 WARN   open tmp/bb52024.tar.gz: no such file or directory (Attempt 1/10 Retrying in 5s)
>   | 2019-07-15 15:47:10 WARN   open tmp/bb52024.tar.gz: no such file or directory (Attempt 2/10 Retrying in 5s)
>   | 2019-07-15 15:47:15 WARN   open tmp/bb52024.tar.gz: no such file or directory (Attempt 3/10 Retrying in 5s)
>   | 2019-07-15 15:47:20 WARN   open tmp/bb52024.tar.gz: no such file or directory (Attempt 4/10 Retrying in 5s)
>   | 2019-07-15 15:47:25 WARN   open tmp/bb52024.tar.gz: no such file or directory (Attempt 5/10 Retrying in 5s)
>   | 2019-07-15 15:47:30 WARN   open tmp/bb52024.tar.gz: no such file or directory (Attempt 6/10 Retrying in 5s)
>   | 2019-07-15 15:47:35 WARN   open tmp/bb52024.tar.gz: no such file or directory (Attempt 7/10 Retrying in 5s)
>   | 2019-07-15 15:47:40 WARN   open tmp/bb52024.tar.gz: no such file or directory (Attempt 8/10 Retrying in 5s)
>   | 2019-07-15 15:47:45 WARN   open tmp/bb52024.tar.gz: no such file or directory (Attempt 9/10 Retrying in 5s)
>   | 2019-07-15 15:47:50 WARN   open tmp/bb52024.tar.gz: no such file or directory (Attempt 10/10 Retrying in 5s)
>   | 2019-07-15 15:47:55 ERROR  Error uploading artifact "tmp/bb52024.tar.gz": open tmp/bb52024.tar.gz: no such file or directory
>   | 2019-07-15 15:47:56 FATAL  Failed to upload artifacts: There were errors with uploading some of the artifacts

This appears to be a regression between v3.13.0 and v3.13.1 when the artifact upload logic was refactored into `multipartStreamer`. The artifact file was previously opened via `os.Open(artifact.AbsolutePath)` but is now being opened via `streamer.WriteFile(artifact.UploadInstructions.Action.FileInput, artifact.Path)`. This should be changed to use `artifact.AbsolutePath`, and an additional unit test should be added to account for files outside the working directory.

**Comment by lox** [comment]
Thanks @petercgrant! Good catch and thanks for the fix.

**Comment by lox** [comment]
This is not quite correct in that it sends the absolute path to the back end for relative files. 🤔

**Comment by petercgrant** [comment]
Do you have a handle on it, or shall I give it another shot?

**Comment by petercgrant** [comment]
The form uploader test ignores the file header. I'll improve that.

There is some strangeness with `artifact.Path`: it seems to be the value the backend wants, but it may be relative to the working directory or to the root. Therefore it may not actually point to a file.

**Comment by lox** [comment]
Thanks @petercgrant! I should have provided a bit more context, I was still investigating exactly what was going wrong. 

I noticed I got failures with `bk run .buildkite/pipeline.bk-test.yml` for relative path uploads. I'll check out your PR and digest what is happening in there.

Really appreciate the prompt response and the PRs!
