### ISSUE TITLE
RPM builds

### ISSUE THREAD

**Issue by wfarr** [buildkite/agent#105]
Along with the supported .deb builds in the beta, it'd be very convenient if .rpm builds were available too for those of us on RHEL or RHEL-derivative stacks.

**Comment by keithpitt** [comment]
@wfarr yup! We've got plans to do this. Now that we have .deb, it should be easy to get .rpm's going. We use a tool called `fpm` so it should make the process pretty straightforward.

Which OS do you use? I'll use what even OS you have in my tests.

**Comment by wfarr** [comment]
We're on CentOS 7, which is compatible with RHEL 7.

**Comment by keithpitt** [comment]
Ok, this has been shipped in the latest version of the agent! <3<3 :dancers:

**Comment by keithpitt** [comment]
It also sports a fancy systemd script: https://github.com/buildkite/agent/blob/master/packaging/linux/root/usr/share/buildkite-agent/systemd/buildkite-agent.service
