### ISSUE TITLE
Allow builds to be triggered without buildkite User

### ISSUE THREAD

**Issue by Hermain** [buildkite/agent#1050]
I have the option turned on to allow "Build pull requests from third-party forked repositories". However after one of those PRs gets merged to my Repo I get: 
>422 Builds cannot be triggered from this pipeline as there is no Buildkite user linked to this build. Ensure that a user has added "<< redacted >>@users.noreply.github.com" as a verified email address on their account. (Attempt 1/60 Retrying in 5s)

I don't want to invite contributors to my buildkite organization because they would then be able to see environment variables which are secret. Therefore I suggest an option to run builds without a buildkite user. If I can do it for a PR (unknown code) I should also be able to do that for my repository (code that I actually reviewed).

I'm open to other ways how to solve that issue.

**Comment by Hermain** [comment]
Ping

**Comment by worxli** [comment]
@lox do you have a suggested solution to this problem?

**Comment by lox** [comment]
Mind dropping us an email to support@buildkite.com and we will assist?
