### ISSUE TITLE
macOS Agent does not utilize default "path" settings

### ISSUE THREAD

**Issue by troyfontaine** [buildkite/agent#1068]
It looks like the macOS agent does not utilize the default paths for the buildkite-agent as installed via homebrew.

The agent does not look in `/usr/local/etc/buildkite-agent/hooks` for example.  Instead, you must specify `hooks-path` in the agent configuration.  Additionally, no default `plugins` directory is installed by default, so the first time you go to use a plugin you receive an error message and have to a) add it to the configuration and b) create the appropriate directory.

Some documentation warning that this is the default behaviour would be nice, even better would be if the default directories were created on macOS and would be used without having to be explicitly configured in the agent 😄 

Thanks!

**Comment by keithduncan** [comment]
Hi @troyfontaine! Thank you for opening this issue 😄 

It looks like some time between filing this issue these have been addressed in the Homebrew formula. Both directories are now given a [default configuration](https://github.com/buildkite/homebrew-buildkite/blob/f7632b86594dd56773ec33e9a7449129b25e4215/buildkite-agent.rb#L80-L81). The formula [creates](https://github.com/buildkite/homebrew-buildkite/blob/f7632b86594dd56773ec33e9a7449129b25e4215/buildkite-agent.rb#L56) the hooks directory, and the agent itself lazily [creates](https://github.com/buildkite/agent/blob/bd1678c104f1fcd16471bc7938a98c83e5880249/bootstrap/bootstrap.go#L869) the plug-ins directory.

Hopefully these changes address your issue if not please let me know and I’ll see what we can do! 😄
