### ISSUE TITLE
feature request: checkout plugin if there is update from the plugin source

### ISSUE THREAD

**Issue by aluo-at-tyro** [buildkite/agent#1073]
From https://github.com/buildkite/agent/blob/0c2928974456f1ec8c753934779869a8d99dcb0b/bootstrap/bootstrap.go#L722, agents only check whether pluginGitDirectory and the head commit exist and ignore checkout if exists.

A scenario is that plugin has updated and re-tagged the (existing) version with a newer commit, so that we don't need frequent update existing pipelines to pin the new plugin version while new function of the plugin can be used. 
An option provided to configure agents to enable the feature might be considered.

To implement it, only need to check the commit from the plugin source and compare it with the local head commit, if the commit from the plugin source is newer, checkout from the source.

**Comment by sj26** [comment]
Great observation! I think this might be a duplicate:
https://github.com/buildkite/agent/issues/422
