### ISSUE TITLE
fatal: reference is not a tree [commit] is causing re-download of entire repository

### ISSUE THREAD

**Issue by pscarey** [buildkite/agent#1088]
May be similar to #581

- Pushing directly to staging branch.
- Staging has been protected previously in GitHub, but disabling this didn't help.
- Agent is deleting and re-downloading the entire repo on a checkout error - not all the time but very frequently.
- This is blowing out build times from 3 to 15 minutes, as every step needs to re-download the repo.
- An old PR is referenced in the messages and buildkite, which was long closed and merged.
- The difference between the below simple step with and without re-checkout is 3m31s vs 11s.
- See in below log comments with ###
- Some information is redacted.

`buildkite-agent pipeline upload .buildkite/pipeline.yaml`

```
~~~ Running global environment hook
[90m$[0m buildkite/hooks/environment
--- :house_with_garden: Setting up the environment

[90m# BUILDKITE_DISABLE_GIT_SUBMODULES changed[0m
[90m# BUILDKITE_NO_GIT_SUBMODULES changed[0m
[90m# BUILDKITE_GIT_SUBMODULES changed[0m   ### Dont think any of these even work?
~~~ Preparing working directory
[90m$[0m cd /buildkite/builds/general-buildkite-agent-1-1/base-up/platform
[90m# Host "github.com" already in list of known hosts at "/root/.ssh/known_hosts"[0m
[90m$[0m git remote set-url origin git@github.com:base-up/platform.git
[90m$[0m git submodule foreach --recursive "git clean -ffxdq"

Entering [SUBMODULE]  ### REDACTED - message appears for all submodules

[90m$[0m git clean -ffxdq
[90m# Fetch and checkout pull request head from GitHub[0m
[90m$[0m git fetch -v --prune origin refs/pull/297/head ### Why is this being fetched? PR was closed on 1 Aug.
key_load_public: invalid format                         ### AFAIK, not an issue.

From github.com:base-up/platform

 * branch                refs/pull/297/head -> FETCH_HEAD

[90m# FETCH_HEAD is now `4a4cb804523e6692b29a65546401b307ab60b77b`[0m     ### Incorrect and unrelated closed PR commit
[90m$[0m git checkout -f 51e271f13b7d676a5989a37084bdeb5b2c0fab62         ### Correct commit reference
fatal: reference is not a tree: 51e271f13b7d676a5989a37084bdeb5b2c0fab62

[33m⚠️ Warning: Checkout failed! exit status 128 (Attempt 1/3 Retrying in 2s)[0m       ### Presumably because we're now on the PR branch?
^^^ +++
[90m# Removing /buildkite/builds/general-buildkite-agent-1-1/base-up/platform[0m       ### Now the entire repo needs re-downloading.
[90m# Host "github.com" already in list of known hosts at "/root/.ssh/known_hosts"[0m
[90m# Creating "/buildkite/builds/general-buildkite-agent-1-1/base-up/platform"[0m
[90m$[0m git clone -v -- git@github.com:base-up/platform.git .
Cloning into '.'...

key_load_public: invalid format

### Long download for whole repo....

[90m$[0m git submodule foreach --recursive "git clean -ffxdq"
[90m$[0m git clean -ffxdq
[90m# Fetch and checkout pull request head from GitHub[0m
[90m$[0m git fetch -v --prune origin refs/pull/297/head       ### Once again with the unrelated PR?
key_load_public: invalid format

From github.com:base-up/platform

 * branch                refs/pull/297/head -> FETCH_HEAD

[90m# FETCH_HEAD is now `4a4cb804523e6692b29a65546401b307ab60b77b`[0m     ### Again incorrect and unrelated closed pr commit
[90m$[0m git checkout -f 51e271f13b7d676a5989a37084bdeb5b2c0fab62         ### Correct commit reference
Note: checking out '51e271f13b7d676a5989a37084bdeb5b2c0fab62'.



You are in 'detached HEAD' state. You can look around, make experimental

changes and commit them, and you can discard any commits you make in this

state without impacting any branches by performing another checkout.



If you want to create a new branch to retain commits you create, you may

do so (now or later) by using -b with the checkout command again. Example:



  git checkout -b <new-branch-name>



HEAD is now at 51e271f13 [REDACTED]                                     ### Got the commit fine this time...

[90m# Git submodules detected[0m
[90m$[0m git submodule sync --recursive
[90m$[0m git submodule update --init --recursive --force

[REDACTED] ### Submodule downloads

[90m# Checking to see if Git data needs to be sent to Buildkite[0m
[90m$[0m buildkite-agent meta-data exists buildkite:git:commit
[90m# Sending Git commit information back to Buildkite[0m
[90m$[0m buildkite-agent meta-data set buildkite:git:commit "commit 51e271f13b7d676a5989a37084bdeb5b2c0fab62 [REDACTED]"
~~~ Running global pre-command hook
[90m$[0m /buildkite/hooks/pre-command
--- :wrench: Configuring bazel for CI environment

~~~ Running commands
[90m$[0m buildkite-agent pipeline upload .buildkite/pipeline.yaml
[38;5;48m2019-09-17 12:03:32 INFO  [0m [0mReading pipeline config from ".buildkite/pipeline.yaml"[0m

[38;5;48m2019-09-17 12:03:32 INFO  [0m [0mUpdating BUILDKITE_COMMIT to "51e271f13b7d676a5989a37084bdeb5b2c0fab62"[0m

[38;5;48m2019-09-17 12:03:33 INFO  [0m [0mSuccessfully uploaded and parsed pipeline config[0m
```

**Comment by lox** [comment]
Sorry you are having problems with this! 

Looks to me like two problems are happening here. It looks like there is a cached pull request associated with the branch, which is causing the attempted checkout of that pull request. We can help fix this (and troubleshoot why it's happening via support@buildkite.com).

The other problem is that the agent removes the entire checkout if a checkout fails on the theory that there might be a corrupt checkout. We've discussed making an agent change to prevent the working directory being removed if checkout fails due to a failed `fetch` operation. I'll have a go at that. 

Beyond that, I'd suggest looking at the [Git Mirrors](https://forum.buildkite.community/t/shared-git-repository-checkouts-in-the-agent/443) experiment to speed up re-clones!

**Comment by pscarey** [comment]
Already emailed support & they requested I post here.

Git mirrors might work generally but unsure how it'd go with our setup - we have a K8s cluster running a collection of pre-emptible VMs, which use persistent volumes to preserve the build directory, yarn modules and Bazel builds across restarts.

Each agent is in its own container, and we mount different secrets to configure the environment of our agents separately. That way, agents running basic build jobs don't have access to secrets required for deployment or database access. We assign our agents to queues based on the permissions they have, e.g. `general`, `staging`, `production`. Branch protection in GitHub means the agents with elevated permissions only run builds on source code which we've explicitly approved to be merged in.

Bazel builds everything incrementally & fully reproducibly (even our containers!) with a shared cache between the machines, so everything should always be fast for any incremental changes.

**Comment by lox** [comment]
Thanks, I'm just reading that ticket too!

**Comment by lox** [comment]
Wouldn't you just have the repository mirrors mounted into your agent containers in that setup?

**Comment by pscarey** [comment]
I'd need to look into it more, but GKE only supports the `ReadWriteOnce` and `ReadOnlyMany` Persistent Volume classes, I think we'd need `ReadWriteMany` to use git mirrors in this setup, as I assume all agents will need to read and write the mirror simulatenously?

**Comment by lox** [comment]
It would be totally fine to have a different volume for each agent.

**Comment by pscarey** [comment]
I understand - in this case the mirror is just for that agent to try and avoid the checkout issue, rather than trying to offer a performance/bandwidth improvement to all agents using a shared mirror.

I've enabled the mirror and the logs confirm this with `# Using git-mirrors experiment 🧪` etc. It's looking good at the minute but I'll post and update once we've run enough builds to be conclusive - thanks.

**Comment by pscarey** [comment]
It currently seems that the `git-mirrors` experiment is a viable workaround, fixing the issue for us. We've not seen a checkout error here. Support also reset our GitHub PR recently cache which now hows staging as Head rather than the merged PR. It seems like that could be a root cause - also based on previous issues.

Build times are back to normal:
![Buildkite Agent Checkout Error](https://user-images.githubusercontent.com/20896758/65120681-596bcb00-da31-11e9-8b4f-268b48f25219.png)

**Comment by lox** [comment]
That is great news @pscarey!
