### ISSUE TITLE
Intermittently AWS EC2 agents fail to register with Buildkite

### ISSUE THREAD

**Issue by liam-bailey** [buildkite/agent#1090]
Upon inspection of the services and logs, it appears that calls to the instance metadata service have failed (empty response), causing cloud-final.service to fail and leave the instance running but it's not connected to Buildkite. We have had other similar issues where obtaining the metadata randomly (and again rarely) fails after the agent has registered and it's running a build (during the pre-command script).
According to AWS docs (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-throttling), there is throttling at an instance level, but I fail too see how we would be hitting any limits. We only make a small number of calls to the metadata service per instance.

May be worth increasing the timeouts and retries in the agent?

**Comment by dbaggerman** [comment]
@liam-bailey, I'm pretty sure this is https://github.com/buildkite/elastic-ci-stack-for-aws/issues/572 and not strictly a problem with the agent itself.

**Comment by lox** [comment]
Yup, agree, think it's that issue. Going to close this one out.
