### ISSUE TITLE
Build succeeds even though docker pull failed

### ISSUE THREAD

**Issue by morxa** [buildkite/agent#1091]
In [this build](https://buildkite.com/fawkesrobotics/fawkes-build/builds/863#608ba17b-bd84-4b96-bb0a-2631da903eb5) with [this buildkite config](https://github.com/fawkesrobotics/fawkes/blob/cb1fada9ee48b5bae4ed5f0f55cee9c705d5d354/.buildkite/pipeline.yml), docker failed to pull the image. Nevertheless, the build succeeded and all tests were marked as passed.

`docker pull` failed because the image was built with podman, not docker, but the reason should not matter here.

The build host is running the buildkite agent v3.13.2.

This is most probably a duplicate of #981, but as I can't reopen that issue, I'm opening this one. Feel free to close and move the discussion to #981, if you think that's better.

**Comment by lox** [comment]
This will be an issue in the docker plugin @morxa! See https://github.com/buildkite-plugins/docker-buildkite-plugin/issues/109. 

We fixed it in docker plugin version 3.3.0. https://github.com/buildkite-plugins/docker-buildkite-plugin/releases/tag/v3.3.0
