### ISSUE TITLE
Error when parsing pipeline.yml with regular expression containing `$`

### ISSUE THREAD

**Issue by bilalm19** [buildkite/agent#1102]
I was using conditions in my pipeline.yml in which I wanted the build.message to end with a certain keyword. For this the regular expression will contain a `$`. But the following error is shown in the build:
```
FATAL  Pipeline parsing of "pipeline.yml" failed (Expected identifier to start with a letter, got /)
--
  | 🚨 Error: The command exited with status 1

```
What I noticed is that the parser for the pipeline.yml file always expects a letter immediately after the dollar sign. I even tried the example expressions given in https://buildkite.com/docs/pipelines/conditionals#example-expressions that contain `$` and I get similar error.

**Comment by lox** [comment]
Sorry you ran into this! The condition is has variable interpolation applied to it, so that errors is because the $ marks the start of variable interpolation.

Try escaping $ with either `\$` or `$$`.
