### ISSUE TITLE
Disabling re-cloning logic on checkout fail for big repos

### ISSUE THREAD

**Issue by SEAPUNK** [buildkite/agent#1108]
We have big git repos that take a significant time to clone. In the cases where a build is triggered for a recently rebased or merged PR (we automatically delete branches once merged), the agent can't check out the commit it's trying to build, because the commit no longer exists on the remote, causing it to go into a retry loop where it [deletes the checkout](https://github.com/buildkite/agent/blob/06ca64522bf5893b4249621aaa8063d38275b231/bootstrap/bootstrap.go#L921-L926
), clones it, and tries to check out the commit again.

For some steps, where we have lots of builds and limited agents, this causes a real bottleneck for us, where the agent takes 30+ minutes to fail, where we expect the agents to finish doing their jobs within 20 seconds, eventually snowballing and causing a big backlog of jobs.

Can the agent have an option to disable this behavior? For us, if the agent can't check out a commit, we're fine with it failing and moving on, without trying to remediate. I'm willing to open a PR for this, if I can get some direction on how this should be implemented.

**Comment by lox** [comment]
Good news is we've fixed this in https://github.com/buildkite/agent/pull/1104.

It will be released shortly in v3.16.0.

**Comment by SEAPUNK** [comment]
Oh, nice! Thank you!
