### ISSUE TITLE
how to switch window CMD.exe shell script to powershell?

### ISSUE THREAD

**Issue by bphan625** [buildkite/agent#1114]
Hi guys, 

I want to use powershell to execute my script on windows agent. After I changed 'buildkite-agent.cfg',(add "shell="C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"" at the end).
Is that correct way to change the shell script?
Because I can use powershell to execute "cargo clippy" in machine directly, 
but in buildkite agent, the error said "
error: no default toolchain configured
"
It's same as I executed with cmd.exe. So I think I didn't successfully switch to powershell on agent.
Do you guys have any ideas about that issue?

**Comment by sj26** [comment]
Hi @bphan625!

Hmm, setting shell should change the way we invoke your command. Can you try running the agent with the "--debug" flags and take a look in the logs to confirm it's using your shell to run your command?

Another option could be to set your command to `powershell $YOUR_REAL_COMMAND` to be sure it's using powershell.

**Comment by keithduncan** [comment]
Hi @bphan625 we haven’t heard back from you so I’m going to close this issue for now. Please do reach out if you’re still experiencing this issue and we’ll help get it resolved :bow:
