### ISSUE TITLE
Get job logs via graphql

### ISSUE THREAD

**Issue by takn** [buildkite/agent#1123]
Hi, not sure if this is the best place to ask, but i'd like to get the logs for each failed job in a pipeline.

This is what i have so far:

```
query pipeline {
  pipeline(slug: "org/my-pipeline") {
    builds(branch: "mybranch", state: FAILED) {
      count
      edges {
        node {
          id
          message
          state
          number
          startedAt
          url
          jobs(first: 500, passed: false) {
            count
            edges {
              node {
                ... on JobTypeCommand {
                  state
                  label
                  exitStatus
                  passed
                  url
                  finishedAt
                }
              }
            }
          }
        }
      }
    }
  }
}

```

**Comment by keithduncan** [comment]
Hi @takn I’ve just looked into this and unfortunately job logs aren’t exposed through our GraphQL API, our best recommendation would be to discover the jobs whose logs you want and then request them using the [REST API](https://buildkite.com/docs/apis/rest-api/jobs#get-a-jobs-log-output). Sorry I couldn’t be of more help here! :bow:
