### ISSUE TITLE
Can't set up shell variables

### ISSUE THREAD

**Issue by aliasgarlabs** [buildkite/agent#1130]
I need to set some shell variables to be consumed by the same shell process. Unfortunately, the shell variables don't get set.

Code: 

```
NAME="BUILDKITE"
echo The name is $NAME
```

Expected: 

`The name is BUILDKITE`

Actual:

`The name is `

Additional context: 

I even tried using the EXPORT keyword but still no luck. Using buildkite meta-data variables is overkill here and I don't want these variables to be available in the subsequent steps.

**Comment by keithduncan** [comment]
Hi @aliasgarlabs, is it possible your `$NAME` variable was part of a command and interpolated by a `buildkite-pipeline upload`, and was missing from the pipeline received by Buildkite? Support might be the best place to handle this issue, if you’re still experiencing trouble please email support@buildkite.com with a link to a build and we’ll take a look 😄
