### ISSUE TITLE
The repo link on dockerhub links to an old repo (not this one)

### ISSUE THREAD

**Issue by nickatsegment** [buildkite/agent#1131]
![image](https://user-images.githubusercontent.com/40582825/69887937-43368280-129e-11ea-9ce5-ac8d0162f8af.png)

https://github.com/buildkite/docker-buildkite-agent

Also, the listed Dockerfile is super out of date. Had me very scared I was running ubuntu 14.04 and dind for a bit

**Comment by keithduncan** [comment]
This looks like it was fixed at some point, thank you for reporting it @nickatsegment :bow:
