### ISSUE TITLE
Commit message not set when using custom checkout hook

### ISSUE THREAD

**Issue by evandam** [buildkite/agent#1133]
I'm writing a custom `checkout` hook to try to cache git repos, but it looks like there's some hidden functionality that this hook is responsible for handling.

I saw mention of `buildkite-agent meta-data exists buildkite:git:commit` - do I need to be setting metadata of the build in this hook, and is there anything else I should be aware of?

**Comment by evandam** [comment]
@lox any idea on this one? Documentation around this hook is pretty sparse and it makes it difficult for my team to identify what builds are running.

Thanks!

**Comment by lox** [comment]
Hey @evandam, sorry docs are sparse on that nuance. Generally, the `checkout` hook does a lot and we generally advise folks avoid overriding that and instead use something like `pre-checkout`. 

Could you tell us a bit more about what you are trying to do with the git repo caching?

**Comment by evandam** [comment]
The repo for my pipeline is fairly large and takes a minute or two to clone. When running parallel steps on a single instance with multiple agents, I'd like to clone once from GitHub, and copy from there for each agent instead. General flow is this:

- Check if `/var/lib/buildkite/repos/${BUILDKITE_REPO}` exists.
  - Clone it if it does not, pull if it does.
- Copy `/var/lib/buildkite/repos/${BUILDKITE_REPO}` to agent's working dir.
- Run `git checkout`, `git clean`, etc.

**Comment by lox** [comment]
Sounds a lot like https://forum.buildkite.community/t/shared-git-repository-checkouts-in-the-agent/443 :)

**Comment by evandam** [comment]
Perfect! In the meantime I did switch to a `pre-checkout` hook that just clones to a shared directory on the host and then copies to the agent's working dir and it seems to be working well.

I'll close this issue out for now, thanks for the help!
