### ISSUE TITLE
Cannot Retry Cancelled Jobs

### ISSUE THREAD

**Issue by evandam** [buildkite/agent#1143]
Hi again :wave:

I'm attempting to handle some retry logic when a buildkite agent goes down, so users don't need to rely on setting the appropriate automatic retries on every step in their pipeline.

I currently have a small script that runs before an instance is shutdown. It queries the Buildkite API for all agents running on the host, stops them (with `force: true`), and then hits each job's `/retry` endpoint.

This almost works, up to the point where I get the error:
```
{"message": "Only failed or timed out jobs can be retried"}
```

Is there a way that I can accomplish this? I think the main blocker is really that stopping the `buildkite-agent` service waits for all jobs to complete, but cancelling those jobs prevents them from being retried.

**Comment by evandam** [comment]
cc @lox for any thoughts

**Comment by lox** [comment]
Could I trouble you to drop us an email to support@buildkite.com @evandam? This one isn't agent related and the folks there will be able to assist!

**Comment by sj26** [comment]
We're chatting about this in an email thread now, but for future travellors: canceled jobs can indeed be retried, but only once they have finished canceling. Waiting for the agent service to stop or polling the job until its status changes from `canceling` to `canceled` should work here.
