### ISSUE TITLE
trailing slash in BUILDKITE_ARTIFACT_UPLOAD_DESTINATION duplicates

### ISSUE THREAD

**Issue by jufemaiz** [buildkite/agent#1145]
Hi team, love your work!

I've just noticed on my builds that if I set the env `BUILDKITE_ARTIFACT_UPLOAD_DESTINATION` with a trailing slash, it duplicates the slash when joining to an artifact path.

e.g.
```
export BUILDKITE_ARTIFACT_S3_BUCKET="sweet-buildkite-artifacts"
export BUILDKITE_ARTIFACT_S3_PATH="$BUILDKITE_PIPELINE_SLUG/$BUILDKITE_BRANCH/$BUILDKITE_BUILD_NUMBER/"
export BUILDKITE_ARTIFACT_UPLOAD_DESTINATION="s3://$BUILDKITE_ARTIFACT_S3_BUCKET/$BUILDKITE_ARTIFACT_S3_PATH"
```

yields a file `test.txt` uploaded in `.artifacts` to be found at:

```
https://sweet-buildkite-artifacts.s3.amazonaws.com/repository-name/branch/name/build-number//.artifacts/test.txt
```

S3 however removes the duplicate slash (unsure of other destination services).

**Comment by shevaun** [comment]
Thanks @jufemaiz for the report and sorry it's taken us so long to address it! This has been fixed now and will be released in the next version of the agent :)
