### ISSUE TITLE
Special case `413 Request Entity Too Large` errors

### ISSUE THREAD

**Issue by keithpitt** [buildkite/agent#115]
If a build log exceeds Buildkite's maximum POST size, a `413 Request Entity Too Large` is sent back to the agent. However, the agent will continue to POST the data until it gets a 200 response.

We should special case `413` in the final job update call, so if we receive one, just send the job update without the final log.

**Comment by toolmantim** [comment]
Duplicate of #103

**Comment by keithpitt** [comment]
Since we chunk uploads now, this isn't a problem.
