### ISSUE TITLE
Buildkite Agent v3.19.0 fails to download files from GCS with backslashes in the name?

### ISSUE THREAD

**Issue by philwo** [buildkite/agent#1159]
Hi,

I'm debugging a mysterious pipeline failure that seems to occur since we upgraded our Buildkite Agents from v3.14.0 to v3.19.0.

We have some build artifacts that are in a sub-folder on Windows, e.g. `bazel-bin\bin\bazel.exe`. When Buildkite Agent uploads them, they get stored like this on GCS: https://storage.googleapis.com/bazel-trusted-buildkite-artifacts/148f94cc-c9bd-4600-b73c-7b41d5bdc8e6/bazel-bin%5Csrc%5Cbazel.exe (the backslashes remain and aren't converted into forward slashes).

<img width="901" alt="Screenshot 2020-02-04 at 21 23 40" src="https://user-images.githubusercontent.com/504652/73783817-a0feb380-4794-11ea-9582-8a96131a1c47.png">

This is also visible in the GCS console:

<img width="566" alt="Screenshot 2020-02-04 at 21 33 56" src="https://user-images.githubusercontent.com/504652/73784598-0ef7aa80-4796-11ea-927d-8b1ca0d2d170.png">

Since v3.19.0, Buildkite Agent fails to download these artifacts, at least when it's running on Linux (haven't tested what happens when the downloading agent runs on Windows).

With v3.14.0:
<img width="934" alt="Screenshot 2020-02-04 at 21 19 13" src="https://user-images.githubusercontent.com/504652/73783442-00a88f00-4794-11ea-914d-2e029acaffd6.png">

With v3.19.0:
<img width="1033" alt="Screenshot 2020-02-04 at 21 18 56" src="https://user-images.githubusercontent.com/504652/73783424-f6869080-4793-11ea-85cb-b44497d18056.png">

The issue seems to be that the agent now converts the backslashes to forward slashes when it builds the URL for the download. This is the one it tries to download from:

https://www.googleapis.com/storage/v1/b/bazel-trusted-buildkite-artifacts/o/edf99f72-5065-4b49-815e-afb715d8fad3%2Fbazel-bin%2Fsrc%2Fbazel.exe?alt=media

This would be the correct one (note that %2F vs. %5C):

https://www.googleapis.com/storage/v1/b/bazel-trusted-buildkite-artifacts/o/edf99f72-5065-4b49-815e-afb715d8fad3%2Fbazel-bin%5Csrc%5Cbazel.exe?alt=media

Our pipeline is now failing. I can see a workaround here, of course - we can upload the binaries without the path in their name, but this seems like a bug? 🤔

**Comment by yob** [comment]
PR #1113 shipped in agent 3.17.0 and sounds like it might be related.

Maybe @lox can provide some more context about that change and why it might result in what you're seeing.

**Comment by harrietgrace** [comment]
@lox @pda This has come up a few times for a bunch of different people. Here's one from the forum too: https://forum.buildkite.community/t/enhancement-artifact-uploads-into-gcs-from-windows-use-backslashes-in-their-keys/390
