### ISSUE TITLE
Can we get an rpm for aarch64

### ISSUE THREAD

**Issue by jnewbigin** [buildkite/agent#1162]
Hi,

We are looking at running some of our build agents on ARM.

Our current process does a yum install but we had to do manual setup for the ARM boxes. An rpm for aarch64 would streamline our agent setup.

Looking at https://github.com/buildkite/agent/blob/aa5791c912c04ec261191a5e3561b8605a248e1f/.buildkite/steps/build-rpm-packages.sh#L30 it might be straightforward.

I am happy to test anything if that helps.
Thanks

**Comment by jnewbigin** [comment]
I am happy to test a package for you. You can dm me on buildkite-community.slack.com if the file is not public.

**Comment by chloeruka** [comment]
Hey @jnewbigin, I've published an edge release if you want to give this one a try with your infrastructure/ARM builds. Edge release is at `yum.buildkite.com/buildkite-agent/experimental/aarch64/buildkite-agent_3.23-beta.1-3452_aarch64.rpm`

So to install via yum:
1. Install our repo: 
```sh
sudo sh -c 'echo -e "[buildkite-agent]\nname = Buildkite Pty Ltd\nbaseurl = https://yum.buildkite.com/buildkite-agent/experimental/aarch64/\nenabled=1\ngpgcheck=0\npriority=1" > /etc/yum.repos.d/buildkite-agent.repo'
```

2. Configure and start the agent:
```sh
sudo yum -y install buildkite-agent
sudo sed -i "s/xxx/INSERT-YOUR-AGENT-TOKEN-HERE/g" /etc/buildkite-agent/buildkite-agent.cfg
sudo systemctl enable buildkite-agent && sudo systemctl start buildkite-agent
sudo tail -f /var/log/messages
```

3. If everything went OK, you'll see your agent in the console:
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30171259/87495249-3d0dde80-c694-11ea-93e4-2acc7ab90459.png">

**Comment by jnewbigin** [comment]
Hi
Sorry it took so long to get round to this.
I can confirm that I can yum install and use the aarch64 rpm agent on CentOS aarch64.
Thanks
John

**Comment by jayco** [comment]
@jnewbigin thanks for letting us know
