### ISSUE TITLE
Disable submodules at pipeline level?

### ISSUE THREAD

**Issue by jmazar** [buildkite/agent#1173]
Is there any way to disable submodules at the pipeline level? My repo has both code I compile that relies on submodules but also some devops scripts that don't rely on any compiled code. I'd really like to be able to run these scripts with buildkite without having to wait on submodule & git lfs pulldowns I don't care about. 

I've found the environment variable/config variable to disable things at the agent level but it's overkill for me - there are cases I do want my submodules and they are more common than not.

**Comment by rr0gi** [comment]
what is the actual solution please :pray:
