### ISSUE TITLE
Are all bash parameter expansion features supported in pipeline files?

### ISSUE THREAD

**Issue by levicole** [buildkite/agent#1179]
Hello!

In my pipeline, I'm attempting to sanitize git branch names with `/`'s in them. I'd expect something along these lines to work:

```
env:
  MY_BRANCH: "${BUILDKITE_BRANCH/\//-}"
```

But I end up with the following error:

```
Pipeline parsing of "pipeline.yml" failed (Failed to parse pipeline.yml: line 13: found unknown escape character)
```

I made the assumption that any of the bash parameter expansion features would work, but I assume that since I'm getting this error, that is not the case. Is that correct?

**Comment by toolmantim** [comment]
👋 @levicole — it's just https://buildkite.com/docs/agent/v3/cli-pipeline#environment-variable-substitution that's supported I'm afraid. If you pre-process the pipeline file via Bash or similar, using [dynamic pipelines](https://buildkite.com/docs/pipelines/defining-steps#dynamic-pipelines), then you'll have a few more options there.

**Comment by levicole** [comment]
Thanks @toolmantim! I love buildkite! I'll go ahead and close out this issue.
