### ISSUE TITLE
BUILDKITE_BRANCH being set to tag instead of branch

### ISSUE THREAD

**Issue by collinvandyck** [buildkite/agent#1196]
We've noticed that for some of our builds, when they are created using a tag, that the BUILDKITE_BRANCH environment variable is set to the tag name instead of the branch name.  So for example, if we are on the branch `master` and tag it as `v1`, both BUILDKITE_BRANCH and BUILDKITE_TAG will be set to `v1`.

The expected behavior would be for the build to have BUILDKITE_BRANCH=`master` and BUILDKITE_TAG=`v1`.

The build we recently saw it on uses the git-release subcommand that comes from the git-extras repository.  Relevant code from git-release: https://github.com/tj/git-extras/blob/be50c2f3f510c6677e88d4f41d74ac3b64c74b36/bin/git-release#L125-L129

**Comment by sj26** [comment]
Hi @collinvandyck! This is a good point, it's not obvious. But in git, branches and tags aren't really related — they're completely separate refs, both of which point directly at a commit — so a tag isn't created from a branch, and we don't know about that relationship when creating the build for you from a webhook. But `$BUILDKITE_BRANCH` can't be empty, so we fill it with the tag name. Does that make sense?

**Comment by collinvandyck** [comment]
Hey @sj26 thanks for the reply!  That makes sense.  It might be helpful to include this subtlety in the https://buildkite.com/docs/pipelines/environment-variables documentation for others down the road :vulcan_salute:
