### ISSUE TITLE
Artifact support with BUILDKITE_DOCKER=1

### ISSUE THREAD

**Issue by nickstenning** [buildkite/agent#120]
At the moment, there doesn't appear to be any support for build artifacts when using single-container docker builds, as discussed over email with @keithpitt today.

It shouldn't be too difficult to add support for this using [`docker cp`](https://docs.docker.com/reference/commandline/cli/#cp) to copy the artifacts out of the (stopped) container after the build has completed. I'd be happy to work up a patch to the default `bootstrap.sh` to do this if that sounds like the right approach. It would have the advantage (I think) of being image-agnostic, and wouldn't require users to dump artifacts in any particular location (unlike a docker volume based approach).

Unfortunately this is made slightly more complicated by the requirement to support wildcards in artifact paths. My current solution is a bit of a hack: namely snapshot the stopped container to an image, and then use that image to extract the files matching the wildcards.

I imagine it would look something like this (inserted after [the main build](https://github.com/buildkite/agent/blob/4560aaf6920e0a6f922a910265449850ca74fb69/templates/bootstrap.sh#L277-L296)):

``` shell
if [[ "$BUILDKITE_ARTIFACT_PATHS" != "" ]]; then

    echo "~~~ Extracting artifacts from build container"
    DOCKER_ARTIFACT_IMAGE="buildkite_"$BUILDKITE_JOB_ID"_artifact_image"
    DOCKER_ARTIFACT_LIST=".buildkite_"$BUILDKITE_JOB_ID"_artifacts"

    # Snapshot container to temporary image
    buildkite-run "docker commit $DOCKER_CONTAINER $DOCKER_ARTIFACT_IMAGE"
    # Use shell in container to establish wildcard matches
    buildkite-run "docker run $DOCKER_ARTIFACT_IMAGE /bin/bash -c \"echo $BUILDKITE_ARTIFACT_PATHS\" > $DOCKER_ARTIFACT_LIST"
    # Copy files from original container to working directory
    buildkite-run "for path in $(cat $DOCKER_ARTIFACT_LIST); do docker cp $DOCKER_CONTAINER:$path .; done"
fi
```

(There would also need to be a couple of lines added to `docker-cleanup`, I imagine.)

**Comment by toolmantim** [comment]
ah, yeah I think this could be the right general solution. The workaround we use is to simply mount the working directory inside the image, but that doesn't really handle the general cases.

We should also do this for the docker-compose case as well (which means you might want to DRY these into a function that takes the original container name)

A PR would be very much appreciated!

**Comment by perryn** [comment]
Did anything happen with this by any chance? currently tearing out hair trying to get capybara screenshots out of our docker-compose based builds...

**Comment by toolmantim** [comment]
@perryn no auto-magical copying, but if you mount `.` into the app from your `docker-compose.yml` the artifact will be available on the host machine running the agent. Is that an option?

**Comment by perryn** [comment]
Thanks @toolmantim that seems to have worked. I wasn't sure since our agent is itself running in a sibling docker container, but mounting /buildkite/builds in *that* one seems to do the trick. My brain hurts.

**Comment by lox** [comment]
Closing in favour of moving docker things to docker plugins in v3: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/issues/79
