### ISSUE TITLE
Hooks always use /bin/bash

### ISSUE THREAD

**Issue by keithduncan** [buildkite/agent#1200]
I’ve been running the buildkite agent in some reduced environments like alpine which only has `/bin/sh` (linked to the busybox implementation) but found that there’s a [hard dependency](https://github.com/buildkite/agent/blob/bed05dda2d7bfb888d80c621af827ee2bce39144/bootstrap/shell/shell.go#L279-L281) on `/bin/bash` to invoke hooks.

I tried setting `BUILDKITE_SHELL` that that isn’t used for hooks 😢 

I wasn’t sure if bash was a hard dependency for the before/after environment magic, or if these could use the `BUILDKITE_SHELL` if given?

**Comment by sj26** [comment]
> I wasn’t sure if bash was a hard dependency for the before/after environment magic

This one, I think. :-( We do some `set` commands and some env/`export -p` magic which I think relies on bash-isms. I'm hoping in the future that plugins will support more than bash, but not for the moment sorry.

I think it's reasonable to widen from `/bin/bash` to searching the `$PATH`, though, like [Windows already does](https://github.com/buildkite/agent/blob/bed05dda2d7bfb888d80c621af827ee2bce39144/bootstrap/shell/shell.go#L262-L267).

**Comment by keithduncan** [comment]
Closing my own issue as a duplicate of #1136 😄
