### ISSUE TITLE
Running agent as non root in kubernetes

### ISSUE THREAD

**Issue by rayanebel** [buildkite/agent#1201]
Hello everyone,

I'm trying to deploy `buildkite-agent` on Kubernetes and in our kubernetes environment we are not allowed to run pod as `root` and each pod run with a random user UID. So, when I deploy the agent, pod crash with the following error message:

```mkdir: can't create directory '//.ssh': Permission denied ```

I also tried to launch the pod with `BUILDKITE_AGENT_DEBUG=true` but I did not have any additional logs to help me to troubleshoot.

Can someone help me ?
Thanks.

**Comment by keithduncan** [comment]
This appears to be coming from our [knownhosts](https://github.com/buildkite/agent/blob/8e03f727d61dd8c6a65ffd13f5ecf7293aa58550/bootstrap/knownhosts.go#L22-L49) support which will create a `$HOME/.ssh` directory if it doesn’t exist.

Does the user your kubernetes pod processes are running as have a home directory in the mount namespace they are using?

**Comment by keithduncan** [comment]
I’m going to close this issue @rayanebel but please let us know if this is still an issue and we’ll help get this fixed 😄
