### ISSUE TITLE
canceled typo?

### ISSUE THREAD

**Issue by joelmoss** [buildkite/agent#121]
Seems there is a typo at https://github.com/buildkite/agent/blob/1636d0eeeea7c7c66128a02784aecc7b4728cb7e/buildkite/job.go#L147, where cancelled os spelt canceled. This seems to be the only place, as everywhere else, the correct spelling is used.

**Comment by joelmoss** [comment]
Or perhaps this is intentional because the Buildkite API returns 'canceled'?

**Comment by keithpitt** [comment]
Yeah, it's what the Buildkite API returns, and apparently `canceled` is the preferred spelling in the US? I'm Australian, so when I write comments and variables, I tend to use our spelling. I should probably just stick to the US version everywhere.

**Comment by keithpitt** [comment]
http://grammarist.com/spelling/cancel/

**Comment by joelmoss** [comment]
bloody americans! ;)

**Comment by keithpitt** [comment]
I know right! It hurts every time I type "color" (it's supposed to be colour!!!)

![image](https://cloud.githubusercontent.com/assets/25882/6904452/bf5ea9bc-d718-11e4-8bd6-1ee8a76ffa9b.png)

Event Chrome knows I'm right! :)

**Comment by keithpitt** [comment]
Going to close this - but thanks for mentioning it! If you see anything else in the codebase that looks funky-town - feel free to open another issue :)
