### ISSUE TITLE
how to use if?

### ISSUE THREAD

**Issue by yuzhaoMR** [buildkite/agent#1215]
Hi, you can see my step, I want to skip the command when if the result is true.

`steps:

label: ":maven: 📦"
command: mvn package
if: build.tag == "v1.0"
artifact_paths: "target/*.jar"
plugins:

docker-compose#v1.5.2:
run: maven
config: .buildkite/docker-compose.yml
wait

label: "Deploy"
command: "deploy.sh"
if: build.tag == "v1.0"`

but when I add the tag v1.0 and push the code, I found all command will not be work through. can you help me?

**Comment by jl-applied** [comment]
I'm not sure if `build.tag` is a defined value. Maybe try using the `BUILDKITE_TAG` env variable instead.

**Comment by chloeruka** [comment]
Hi @yuzhaoMR! Sorry to see you've had some trouble getting pipeline conditionals to work. `build.tag` should be available there [according to the documentation](https://buildkite.com/docs/pipelines/conditionals#supported-variables). If you're trying to skip the `:maven: 📦"` step, you might want to use something like `if: build.tag != "v1.0"` to indicate to the pipeline scheduler that you **don't** want to run that step if your tag is `v1.0`.

As this is not specifically an issue with the agent, I'd advise you to ping our friendly [support@buildkite.com](mailto:support@buildkite.com) instead with the affected build and we can have a closer look at it for you.
