### ISSUE TITLE
Feature Request: Auto-cancel after N minutes

### ISSUE THREAD

**Issue by mipearson** [buildkite/agent#122]
Every so often one of our agents gets 'stuck' or docker cracks the shits or we do something stupid in our app and a build that normally takes 5 minutes will still be running after three hours.

Add an option (preferably in the web-interface, not the agent, but it could be on the agent if that's easier) to auto-kill builds that take longer than N minutes.

**Comment by toolmantim** [comment]
Hey! So we already have timeout support on a per-step basis:

![automatic-timeout](https://cloud.githubusercontent.com/assets/153/6912821/f26a57d4-d7c2-11e4-9f08-eff6a0654de8.png)

Is that what you wanted?

**Comment by mipearson** [comment]
.. yes. :/
