### ISSUE TITLE
Agent does not restart on upgrade (on CentOS)

### ISSUE THREAD

**Issue by morxa** [buildkite/agent#1231]
At least on CentOS 7, the agent does not restart automatically when being upgraded. After updating the package, the agent is still displayed with the old version on the agent overview. Only after manually running `systemctl restart buildkite-agent`, the new version is running.

In the systemd case, I guess that this could be fixed by replacing:
https://github.com/buildkite/agent/blob/f7d57d748ac9fdac4084338546a21b03efde21e7/packaging/linux/scripts/after-install-and-upgrade.sh#L75
with:
```
  START_COMMAND="sudo systemctl enable buildkite-agent && sudo systemctl restart buildkite-agent"
```
(i.e., `start` -> `restart`)

**Comment by triarius** [comment]
Fixed by a combination of https://github.com/buildkite/agent/pull/1947 and https://github.com/buildkite/agent/pull/1993
