### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by schwmi** [buildkite/agent#1236]
Currently, I am not able to run the buildkite-agent on macOS 11, with Apple A12Z Bionic chip.
Leads to `bad CPU type in executable: ./buildkite-agent`.

**Comment by yob** [comment]
Thanks for sharing this report @schwmi.

We're super keen to have a version of the agent that runs on Apple's upcoming ARM systems, and plan to add it as a build target once golang supports it  (see https://github.com/golang/go/issues/38485).

None of us have an arm dev kit yet, but I naively assumed the current macos binary might "just work" via Rosetta 2 though. It's interesting that it doesn't! Have you noticed the same error with other applications, or does Rosetta 2 seem to do it's thing most of the time?

**Comment by ticky** [comment]
Hi @schwmi, it sounds like there may be a number of issues which may affect golang binaries on the new hardware right now, but the one that sticks out is which version did you download? We have both `386` and `amd64` binaries, and the one you will want for Rosetta 2 on Apple Silicon is definitely `amd64`!

**Comment by schwmi** [comment]
Thanks, that makes sense. The `amd64` version works on the dev kit. When installing the binary manually I had to remove the quarantine flag with `xattr -c` from the `buildkite-agent`.
Feel free to close this issue…

**Comment by yob** [comment]
perfect, thanks for reporting back!

**Comment by dbast** [comment]
Apple Silicon support is now there, but still via manual steps (afaik till go 1.16 is released)... steps are described here https://github.com/golang/go/issues/38485#issuecomment-730247329

**Comment by yob** [comment]
We have an open PR that builds a working agent for Apple Silicon, however
we're still considering the best way to manage code signing.

All the gory details are in #1339

**Comment by dbast** [comment]
ah. thx!
