### ISSUE TITLE
annotation artifact links with hash/fragment get removed entirely

### ISSUE THREAD

**Issue by robotdana** [buildkite/agent#1253]
Hi :) 

We use simplecov, and i wanted to make our coverage annotation more user-friendly with direct links to files in the simplecov generated html artifact. i expected `<a href="artifact://tmp/coverage/index.html#filename_digest_id">blah</a>` to be transformed to the s3 url, keeping the fragment `#filename_digest_id` at the end.

instead it was transformed to `<a>blah</a>` which i wasn't expecting at all. This was the same whether i used HTML links or markdown links. 

Links without a fragment/hash work perfectly, that is `<a href="artifact://tmp/coverage/index.html">blah</a>` gets transformed to a link to the s3 url as documented here: https://buildkite.com/docs/agent/v3/cli-annotate#embedding-and-linking-artifacts-in-annotations

**Comment by sj26** [comment]
Interesting, I don't think anyone's ever tried that before — but I love it! I'll see if we can sneak this in for you.

**Comment by sj26** [comment]
Hi again - just letting you know we shipped a fix for this (and the commit closed this issue when it was merged 😅). Try it out and let us know if it’s working for you?

**Comment by robotdana** [comment]
it works thank you :)
