### ISSUE TITLE
Git checkout failed at: argument list too long

### ISSUE THREAD

**Issue by alexzhaobin** [buildkite/agent#1269]
When we squash merge a large branch in github, it will generate a huge commit message like this with 2000 lines:

```
Commit message (#2297)

* Bugfix/3007 .............................

* Bugfix/1210 .............................

* Bugfix/2783 .............................

* Bugfix/2118 .............................
```

This causes buildkite agent to fail at git checkout with error: fork/exec /usr/local/bin/buildkite-agent: argument list too long

Full error message:
Error: Error running `/usr/local/bin/buildkite-agent meta-data set buildkite:git:commit "commit ..."`: fork/exec /usr/local/bin/buildkite-agent: argument list too long

**Comment by sj26** [comment]
Oh no, sorry that's probably just not a case we've seen very often — but a bug!

We can modify this code to pipe the commit message into the meta-data command instead. I'll see if we can pop up a quick fix.

**Comment by pda** [comment]
Thanks again for the report @alexzhaobin — we have one fix merged, another ready for review, and it should land in a release within the next week. /cc @jayco

**Comment by pda** [comment]
Hey @alexzhaobin — [buildkite/agent v3.24.0](https://github.com/buildkite/agent/releases/tag/v3.24.0) contains #1302 and #1307 which should fix up the handling of very large commit messages. Let us know how you go with it 🙏🏼
