### ISSUE TITLE
`Running local post-command hook` isn't on a new line when script doesn't end with "\n"

### ISSUE THREAD

**Issue by keithpitt** [buildkite/agent#127]
If a script that is run doesn't end with a "\n", then the `--- Running local post-command hook` header get's added to the next line. Now, the simple solution would be for us to just add a `echo ""` after we execute the actual script, but the "aesthetics" bug me when the script would end with a `\n` (it'd have a double line).

![image](https://cloud.githubusercontent.com/assets/25882/6990193/13ba5792-da5f-11e4-83c8-5df1633acccf.png)

I wonder if there's some magic in bash to determine if the cursor is on a new line, and if it's not, insert a `\n` character? If there's not, we should just bite the bullet and add the new line :-1:

**Comment by toolmantim** [comment]
I don't think it's possible? I reckon we just leave this as WONTFIX, and call it a bug in their hook, rather than a bug in out bootstrap…

**Comment by keithpitt** [comment]
It was actually our build script - but I think you're probably right as being a WONTFIX for now.
