### ISSUE TITLE
[Feature Request] buildkite agent for windows arm64 (Windows on ARM)

### ISSUE THREAD

**Issue by ghuntley** [buildkite/agent#1282]
ie.  https://docs.microsoft.com/en-us/windows/arm/ <3

**Comment by yob** [comment]
We're keen to support arm on various operating systems, however no one on staff at Buildkite is very familiar with arm+windows.

Do you have a windows+arm machine/instance handy @ghuntley?

Our support will depend on golang's support for windows+arm64 as a compilation target. A low-knowledge test suggests maybe [that's still coming](https://github.com/golang/go/issues/36439)?

```
# default compilation target on linux compiles
$ go build -o ./buildkite-agent .

# windows/arm supported
$ GOOS=windows GOARCH=arm go build -o ./buildkite-agent .

# windows/arm64 not supported
$ GOOS=windows GOARCH=arm64 go build -o ./buildkite-agent .
cmd/go: unsupported GOOS/GOARCH pair windows/arm64
```

**Comment by keithduncan** [comment]
This is workable now with golang 1.17.

If possible we’d like to build Windows/arm64 with the newer version of go but keep other OS/arch pairs on their current version, specifically macOS for which a golang major version bump of 1.16 -> 1.17 means dropping old operating systems.

An update to the `golang.org/x/sys` package is also required to get this building.

**Comment by yob** [comment]
> If possible we’d like to build Windows/arm64 with the newer version of go but keep other OS/arch pairs on their current version, specifically macOS for which a golang major version bump of 1.16 -> 1.17 means dropping old operating systems.

There's prior art for this in the git history - we originally built a binary for m1 macs using a differnet version of golang to the stable version that built every other binary.
