### ISSUE TITLE
Token not entered into config when using brew install

### ISSUE THREAD

**Issue by twometresteve** [buildkite/agent#1284]
The docs say that running the following should enter the token into the Buildkite config file when installing.

```
brew install --token='INSERT-YOUR-AGENT-TOKEN-HERE' buildkite-agent
```

However, the token in my config file is empty and so I have to update it manually.
```
# The token from your Buildkite "Agents" page
token=""
```

I'm using Homebrew 2.4.16 on MacOS 10.15.6.

**Comment by jayco** [comment]
Hey @twometresteve, thanks for raising this!

We have done some investigation and from what we can tell this was broken in version 2.3.0. I think we thought we’d fixed it in https://github.com/buildkite/homebrew-buildkite/pull/16/files, but this only fixed the error we were getting.

While Homebrew itself supports options with values, the Formula API hasn’t ever really been intended to. Every formula Homebrew has ever published has used binary flags, either enabling or turning off functionality. They’re passed to the same argument parser ultimately, and it in turn inadvertently accepts flags with values, but it doesn’t pass them through to formulae.

With Homebrew 2.3.0’s changes to remove access to the global ARGV object, we’ve lost the accidental path through which we were able to access these values. It was never really intended for formulae to be able to use this, and as such, it’s now gone and there’s no replacement which does what we want.

For the short term, I have created a PR to update the docs to remove this functionality https://github.com/buildkite/docs/pull/820
