### ISSUE TITLE
Agent meta-data get "--default" not working from version 3.23.0

### ISSUE THREAD

**Issue by feimeng** [buildkite/agent#1285]
We've noticed that
`buildkite-agent meta-data get "ENV_VARIABLE" --default "some_default_value"`
is no longer working but returning error message with 404. By reading the code, I think it might be introduced by this command https://github.com/buildkite/agent/commit/7cf126fc2ea9aef89e65dfdd68711849e7b83f10#diff-939779aad1086b82ea304d09e361ad1b when `urfave/cli` was upgraded to v2. Most likely the `cli.Context` does not set the default anymore.

**Comment by yob** [comment]
Thanks for flagging this, we didn't appreciate that upgrading to would result in a user breaking change to the cli.

In hindsight, I can see that called out in the [v1 to v2 upgrade guide](https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md).

@feimeng based on my read of that upgrade guide, does your command work if the arguments are re-ordered?

```
buildkite-agent meta-data  --default "some_default_value" get "ENV_VARIABLE"
```

The question for us is whether that's OK, or whether we roll back to v1 so arguments can be ordered in any way :thinking:

**Comment by ticky** [comment]
Hi @feimeng, just had a look at this and it seems like the underlying CLI library changed ordering requirements for arguments on us and we missed it in that release.

I’d recommend rolling back while we figure out how we’ll approach it!

**Comment by feimeng** [comment]
Thanks @yob and @ticky ! We've already rolled back to version `3.22.1` to unblock our production. I felt it's probably a regression to other users so I reported here. I'll test the re-ordered command
```
buildkite-agent meta-data get --default "some_default_value"  "ENV_VARIABLE"
```
but my question is would the new order be the new interface or we'll get back to before?

**Comment by yob** [comment]
@feimeng our intention is to revert the change, so the interface you're using will work going forward.

**Comment by feimeng** [comment]
Thank you @yob. We'll upgrade to the next release once it's ready.

**Comment by pda** [comment]
https://github.com/buildkite/agent/releases/tag/v3.23.1 is released, rolling back the CLI changes.

**Comment by lachlancooper** [comment]
It would be great to get some test coverage on the clicommand to minimise the chance of regression here in future 😉
