### ISSUE TITLE
Job and it's processes are unable to be stopped/canceled/terminated on windows

### ISSUE THREAD

**Issue by filipVisko** [buildkite/agent#1292]
We're seeing some odd behaviour where`buildkite-agent` is unable to stop spawned processes.
This occurs during game engine builds (which run ugly batch or other things out of our control) and when either:
- The job being executed times out. ie: reaches its `BUILDKITE_TIMEOUT` limit.
- A user visiting buildkite.com clicks the cancel button for the job.

Expected outcome: Job cancels immediately! The job state in the buildkite.com UI is now red.
Actual outcome: Job is in a `canceling` state forever. The job state in the UI is yellow. (The only reliable way to terminate the process is to use the OS service manager)

https://github.com/buildkite/agent/blob/master/agent/job_runner.go#L357
Inside of `Cancel()`, it logs with `Canceling job %s with a grace period of %d` and then with `Job %s hasn't stopped in time, terminating`.
This happens because `Cancel()` is called by `CancelAndStop()` which is called from within `Stop()`, but `Stop()` never checks the return value of `CancelAndStop()`.

I suspect that `CancelAndStop()` is returning an error which needs to be handled. `go-lint` also flags this line as an unhandled error.
https://github.com/buildkite/agent/blob/master/agent/agent_worker.go#L271

**Comment by sj26** [comment]
Thanks for the report @filipVisko, this does sound like a problem. We've got a few folks looking at agent stuff soon, I'll see if we can get their eyes on this as well.

**Comment by meteorcloudy** [comment]
We encountered the same problem on Bazel CI:
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/633#637566fd-07bd-4ed7-9571-6a1d8f9c77fd

**Comment by filipVisko** [comment]
The added symptom of this issue is that the Buildkite http health endpoint still returns `200`. Which means that our autoscaling groups never kills these instances and wastes our compute time (until we notice this via alerts for long lived instances).

**Comment by yob** [comment]
Thanks for reporting this @filipVisko. We've had another customer report the same symptoms and it's definitely something we'd like to fix.

In #1317 we added some debug logging for the unhandled errors you identified here, and with the other customer we confirmed that `r.Cancel()` is returning an error: 

```
2020-10-09 09:29:18 INFO   host-1 Canceling job 818efd1d-d0e7-4c91-8696-6ce3ec150a0c with a grace period of 10s 
2020-10-09 09:29:28 INFO   host-1 Job 818efd1d-d0e7-4c91-8696-6ce3ec150a0c hasn't stopped in time, terminating 
2020-10-09 09:29:28 DEBUG  host-1 [Process] Terminating process tree with TASKKILL.EXE PID: 1234 
2020-10-09 09:29:28 ERROR  host-1 Unexpected error canceling process as requested by server (job: 818efd1d-d0e7-4c91-8696-6ce3ec150a0c) (err: exit status 128)
```
However, I haven't managed to replicate the issue locally yet. Any tips you can provide that might help us replicate it would be super useful.

Our theory had been that maybe the bootstrap process is terminating early and we're not detecting it, but it sounds like you might have the opposite problem - the bootstrap (and related build processes) are still running and fail to shutdown?
