### ISSUE TITLE
Inconsistent clone behavior when using git-mirrors

### ISSUE THREAD

**Issue by chrislloyd** [buildkite/agent#1299]
Hey folks, I've been experimenting with using `git-mirrors` and so far the results are looking good. However, I'm seeing some weird behavior and thought I'd open an issue to keep notes while I debug and see if anybody else has ideas.

On some machines, the call to [fetch the commit fails](https://github.com/buildkite/agent/blob/master/bootstrap/bootstrap.go#L1185) fails, but on others it doesn't. This is problematic for us because a full fetch is extremely slow (it's often longer than  the job timeouts we've set).

```
$ git fetch -v --prune origin 092318fe9d0575735cc74e333449759dae16a70b
# Fetch received by "xxx", forwarding to cluster host.
# Acquiring read lock for repository "rP" on device "xxx"...
# Acquired read lock immediately.
# Device "xxx" is already a cluster leader and does not need to be synchronized.
# Cleared to fetch on cluster host "xxx"
$ git fetch -v --prune origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
# Fetch received by "xxx", forwarding to cluster host.
(proceeds to do a full fetch)
```

Note that the command appears to be succeeding (normal output) until it doesn't. There's no output of what the particular error was.

On another machine in the same cluster:

```
$ git fetch -v --prune origin 092318fe9d0575735cc74e333449759dae16a70b
# Fetch received by "xxx, forwarding to cluster host.
# Acquiring read lock for repository "rP" on device "xxx"...
# Acquired read lock immediately.
# Device "xxx is already a cluster leader and does not need to be synchronized.
# Cleared to fetch on cluster host "xxx".
From ssh://xxx
* branch            092318fe9d0575735cc74e333449759dae16a70b -> FETCH_HEAD
$ git checkout -f 092318fe9d0575735cc74e333449759dae16a70b
(continues as normal)
```

When running the fetch command manually on the failing machine, it succeeds. This makes me think that there's perhaps a bug in the agent causing the fetch command to report an error incorrectly. Perhaps a race condition with something else?

**Comment by chrislloyd** [comment]
Update: It looks like the call periodically fails regardless of the machine. I have an example where on the same worker it failed once, passed once, then failed again.

**Comment by sj26** [comment]
Sorry @chrislloyd, this seems pretty frustrating.

Does the second fetch typically succeed, or also fail?

Is there any correlated log output on the system?

We're already asking git to fetch verbosely, so I'm not sure how that fetch might be failing without some output. :thinking:

This is very odd:

```
# Fetch received by "xxx", forwarding to cluster host.
# Acquiring read lock for repository "rP" on device "xxx"...
# Acquired read lock immediately.
# Device "xxx" is already a cluster leader and does not need to be synchronized.
# Cleared to fetch on cluster host "xxx"
```

Is this part of the git mirror implementation, or some sort of git proxy service? Sorry, I'm not familiar.

**Comment by lox** [comment]
Yeah that caught my eye too, is that Phabricator?

**Comment by chrislloyd** [comment]
> Does the second fetch typically succeed, or also fail?

Usually times out (but looks to be successful). For reasons (_waves hands_) a full clone of our repo takes ~1h which is longer than our step timeouts.

> Is there any correlated log output on the system?

Nothing obvious that I can see. I traced exit signals with BPF. 

> Yeah that caught my eye too, is that Phabricator?

Yep!

I just verified that our git servers are running protocol v2 and it looks like they  are. I'm a little stumped as to what's happening here. Definitely not 100% sure it's the agent, but will keep posting updates here regardless. Feel free to close if you'd like to tidy.

**Comment by sj26** [comment]
It smells a bit like an issue in the git fetch itself, more than the behaviour added by mirrors. But I'm not sure.

We can leave this open @chrislloyd for any further details you can find. But I'm not sure there's much we can actively to do fix it at the moment, sorry, until we identify what's going on. :-(

**Comment by sj26** [comment]
That gave me an idea, actually. Could you adjust your builds, maybe using a hook, to supply `BUILDKITE_REFSPEC=refs/the/thing/phabrictor/uses` so it asks for the specific named ref from phabricator instead? Perhaps that might work better. Then it would go via this code path instead:

https://github.com/buildkite/agent/blob/9c399b6e987da50d61452b61318dd1617261ea02/bootstrap/bootstrap.go#L1150-L1156

**Comment by chrislloyd** [comment]
I'm currently investigating our git server config - I believe we don't have `uploadpack.allowAnySHA1InWant` enabled which is common for the major git hosting providers. We're also not using the V2 protocol which may or may not be an issue. Will report back.

Re: setting `BUILDKITE_REFSPEC` - I'm not sure that'll affect it much as Phabricator _does_ correctly set a branch and in cases like master we do want to fetch the parent commit.

**Comment by sj26** [comment]
Turning on `uploadpack.allowAnySHA1InWant` would be hugely beneficial and optimise the fetch quite a lot. :-)

**Comment by sj26** [comment]
We could also add a "skip commit fetch" option to the agent to shortcircuit the first fetch, when you know it won't work and want to jump straight to the fetch by ref name?

**Comment by chrislloyd** [comment]
Circling back - `uploadpack.allowAnySHA1InWant` is definitely pretty useful :D I'd recommend adding that to the docs somewhere (happy to do a PR but it's probably most useful on the site) so it's clear to self-hosters.

However, one more interesting case I've noticed is when the remote hangs up while the during the fetch, but _while_ the index is being rebuilt ("resolving refs") locally:

```sh
Receiving objects: 100% (6340093/6340093), 21.10 GiB \| 65.46 MiB/s, done.
remote: Total 6340093 (delta 4888179), reused 6237010 (delta 4795525)
Connection to xxx closed by remote host.
Resolving deltas: 100% (4888179/4888179), completed with 22628 local objects.
$ git fetch -v --prune origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
```

I _think_ in this case it returns a non-zero exit code, but that then launches into a full fetch (taking forever). Not 100% sure how to proceed - perhaps finding out what the exit code is? Is this something ya'll have seen before?

**Comment by chrislloyd** [comment]
Ok, more evidence of weirdness:

```
$ cd /mnt/git-repos
# Commit "b464db5c40bf363946922a273d1a85fdad53dc3a" exists in mirror
$ cd /mnt/buildkite-pipelines/xxx/pinterest/pinboard-differential
$ git remote set-url origin xxx.git
$ git clean -ffxdq
$ git fetch -v --prune origin abc123
... goes into full fetch ...
# Received cancellation signal, interrupting
$ git fetch -v --prune origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
... continues to timeout ...
```

Basically it's finding the commit in the mirror but still fetch the commit. When that times out ("received cancellation signal") it then attempts to do a full fetch.

**Comment by sj26** [comment]
> Circling back - uploadpack.allowAnySHA1InWant is definitely pretty useful :D I'd recommend adding that to the docs somewhere (happy to do a PR but it's probably most useful on the site) so it's clear to self-hosters.

Yeah, we should probably have a page about hosting your own git and how to make it work well. Most folks use github or run github enterprise etc which have these sorts of things configured by default. I think modern versions of git itself might default these sorts of things as well.

> However, one more interesting case I've noticed is when the remote hangs up while the during the fetch, but while the index is being rebuilt ("resolving refs") locally ...

This sounds to me like the local repository is doing operations while expecting a remote connection to stay open, but it is being killed by the remote as an idle connection, or something?

> Basically it's finding the commit in the mirror but still fetch the commit. When that times out ("received cancellation signal") it then attempts to do a full fetch.

That sounds like a bug we could fix in the agent, i.e. when we have a fully-qualified commit sha and have a matching commit object already then avoid fetch entirely.

**Comment by sj26** [comment]
I've written up this last part as: #1313

**Comment by keithduncan** [comment]
Hi @chrislloyd it looks like this _might_ have been fixed with some your-side changes to the git hosting? The last part appears to be captured in #1313 so I’m going to close this issue but if I have missed anything or there’s more to discuss please do re-open or comment below 😄 Thanks again, and let us know if there’s anything further we can do to help here.
