### ISSUE TITLE
Agent exits uncleanly when stopped from the UI

### ISSUE THREAD

**Issue by patrobinson** [buildkite/agent#1301]
When I stop all agents on a box via the UI, the system process exits uncleanly:

```
● buildkite-agent.service - Buildkite Agent
   Loaded: loaded (/etc/systemd/system/buildkite-agent.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2020-09-15 06:59:11 UTC; 1min 3s ago
     Docs: https://buildkite.com/agent
  Process: 1980 ExecStopPost=/usr/local/bin/terminate-instance (code=exited, status=255)
```

This causes systemd to try and restart the services, even though we don't want them to.

**Comment by sj26** [comment]
Weird, it looks like not the agent process but `/usr/local/bin/terminate-instance` has exited badly (`status=255`). Are you using the [elastic-ci-stack-for-aws](https://github.com/buildkite/elastic-ci-stack-for-aws)? It may be an issue for that repository, instead.

Can you see any log output?

**Comment by patrobinson** [comment]
@sj26 oh hai

We are using a modified version of that stack. I'm going to guess it doesn't have permission to do that and hence exits badly. Will raise a PR to add `|| true` to it. Thanks for the pointer (I didn't notice it).

**Comment by sj26** [comment]
Hi!! 😁 

Oh, yeah, that might be why! Mystery solved. Sounds like that'll work a treat. :+1:
