### ISSUE TITLE
git mirrors pull request fetch

### ISSUE THREAD

**Issue by sj26** [buildkite/agent#1305]
The [git mirrors experiment fetch/checkout process](https://github.com/buildkite/agent/blob/9c399b6e987da50d61452b61318dd1617261ea02/bootstrap/bootstrap.go#L1015-L1091) doesn't currently support pull request fetch, like [the regular fetch/checkout process](https://github.com/buildkite/agent/blob/9c399b6e987da50d61452b61318dd1617261ea02/bootstrap/bootstrap.go#L1158-L1171). This means builds of commits in github forked repositories currently fails (#1303).

**Comment by ticky** [comment]
#1308 implements this, and just needs a review 👍🏼

**Comment by philwo** [comment]
Just stumbled upon a reference to this issue in our code - as #1308 is merged, can we close this? :)

**Comment by keithduncan** [comment]
Well spotted @philwo, thanks!
