### ISSUE TITLE
[Request] Redhat RPM for arm64 architecture

### ISSUE THREAD

**Issue by runlevel5** [buildkite/agent#1306]
I am setting up buildkite-agent on the AWS ARM-based EC2 instance manually with tarball binary which works but kinda involving to setting up systemd service file, etc.

It would be super convenient if the team could provide the RPM package for arm64 platform on the official yum repo  https://yum.buildkite.com/buildkite-agent/stable/

**Comment by keithduncan** [comment]
It looks like this was addressed in https://github.com/buildkite/agent/pull/1241 so I’m going to close this, let us know if you are experiencing issues with the RPM :bow:
