### ISSUE TITLE
Documentation for git-clone-mirror-flags is confusing

### ISSUE THREAD

**Issue by chrislloyd** [buildkite/agent#1319]
Hey folks, the [documentation](https://buildkite.com/docs/agent/v3/configuration) around the `git-clone-mirror-flags` is a little confusing. It mentions an example "-v --mirror" and no default. I set it to `--config pack.threads=35` to speed up our checkouts. However, that meant that the `-v` and `--mirror` flags were lost, making the mirror clone a full checkout clone. I think the best solution here is to update the mirror clone to always add the `--mirror` flag (like what happens for `--reference`) and make the `-v` flag a default.

(I didn't notice this previously because I'm pre-cloning mirrors for a few select repos onto machines before the agent starts up and I'm doing my own clone there).

**Comment by sj26** [comment]
Good suggestion @chrislloyd! I'll let our docs folks know.

**Comment by sj26** [comment]
The default is `-v --mirror`
