### ISSUE TITLE
Agent artifact download fails to find uploaded artifact (to GCS) following job failure and successful retry

### ISSUE THREAD

**Issue by 0x0I** [buildkite/agent#1327]
My team is experiencing an issue which results in artifact downloads failing to discover artifacts which were uploaded from failed and eventually successful-on-retry jobs; despite making use of the `--include-retried-jobs` flag within the agent download command. The same artifacts are being discovered fine in the absence of the job retry (or successful first run) which is what is indicating to us an issue with the retry include logic.

**Agent version:** [ubuntu-3](https://hub.docker.com/layers/buildkite/agent/3-ubuntu/images/sha256-c7ea4e5abfe4292597531d23eac6908693bfc21786dcc1edfbc0ad55dd4637c2?context=explore) (docker image)

**Example Failure:** https://buildkite.com/o-1-labs-2/mina/builds/4349#34dfa286-79f9-4251-b60d-e8895f3d51fc

artifact upload path setting:

`BUILDKITE_ARTIFACT_UPLOAD_DESTINATION="gs://buildkite_k8s/coda/shared/${BUILDKITE_JOB_ID}"`

agent download command:

`buildkite-agent artifact download --build <build-id> --include-retried-jobs --step <step-key-id> <artifact> .`

**Comment by 0x0I** [comment]
Issue appears when the `--step` scope is applied to the download command and is absent when not (as evidenced by run: https://buildkite.com/o-1-labs-2/mina/builds/4392#0fae5bd4-9248-47b6-bda6-3c65993c1585)

**Comment by sj26** [comment]
Sorry @0x0I, we made a change recently to start respecting `--include-retried-jobs` in combination with `--step` and it seems to have bitten you here.

Looking at your particular build, I can see the artifact was uploaded by the successful _retry_ job, but was missing from the failed _retried_ job. `--include-retried-job` means that `--step ...` is prioritising the first step that it matches which is the failed job, which does not have the artifact. I don't think you want `--include-retried-job` here at all, it looks like only a successful (potential retry) job will ever uploade such an artifact. Can you try removing the flag?

Separately, I think it makes sense for us to select the latest matching step for artifact download here, and I'll look at making that change.

**Comment by 0x0I** [comment]
Hey @sj26, ah thanks for the response/explanation and apologies for the delay in reply. Will give that a try!

In the same sense I think - also found that removing the `--step` flag allows for artifacts from *retries* to be discovered with the `--include-retried-jobs` flag added.

Anyway, agreed and cool :+1:
