### ISSUE TITLE
Expose CPU/memory/disk information

### ISSUE THREAD

**Issue by wfarr** [buildkite/agent#133]
Would love to have the agent expose CPU, memory, and disk information about the machine it's running on to the buildkite service.

For example, we've just added 2 new, beefier builders and want to retire the old ones, but aside from IP addressing, there's not really a means to differentiate them in the UI.

**Comment by toolmantim** [comment]
I like the idea of showing system stats, but for the differentiating of agents have you checked out the `--name` argument? (I noticed you're not using it). You can also specify a `%n` pattern in it (e.g. `--name "beefy-agents-%n"`). We do this for ours (`"buildkite-ci-%n"`)

**Comment by keithpitt** [comment]
I actually started this a while back! But I couldn't find a cross platform library that'd let me get this info.

**Comment by wfarr** [comment]
You may want to take a look at: https://github.com/kelseyhightower/terminus

:grin:

**Comment by keithpitt** [comment]
I actually saw that one, but no Windows support :P I'll keep looking thoughQ

**Comment by toolmantim** [comment]
Now thanks to proctitle support in the linux build we've support for adding linux-only features. So we could look at adding this in via terminus…

**Comment by keithpitt** [comment]
Also found this: https://github.com/shirou/gopsutil

**Comment by keithpitt** [comment]
We're doing some spring cleaning of our GitHub issues, and I might close this one for now. Tracking stats is a really interesting idea, but not sure how useful it'd be when you've got 10-100's of agents all running on the same machine. We totally want to improve the agents page in the future though so you can get a sense of how an agent is performing.
