### ISSUE TITLE
buildkite-agent on ReactOS can't talk to server

### ISSUE THREAD

**Issue by pda** [buildkite/agent#1331]
buildkite-agent on [ReactOS](https://reactos.org) (0.4.13) can't talk HTTPS to the API.
Maybe it's a TLS/cipher/cert error, but looks more like an internal socket API error.

This (ReactOS support) doesn't really matter, and is more likely a problem with ReactOS or perhaps Go's support for older Windows. I just thought it'd be interesting to make a note of it. ReactOS could be an interesting way for people to run builds for older Windows software. Maybe this issue should be closed but remain searchable?

> dial tcp ADDR:443: connectex: invalid argument

I tested the current [v3.24.0](https://github.com/buildkite/agent/releases/tag/v3.24.0) and also [v3.5.4](https://github.com/buildkite/agent/releases/tag/v3.5.4) which I believe was the last version compiled with Go 1.10 which [I believe](https://github.com/golang/go/issues/33344) was the last Go to officially support Windows XP / 2003 which I believe is what ReactOS aims to emulate.

![image](https://user-images.githubusercontent.com/15759/96254890-c7523f80-1001-11eb-97dc-cafa05a1fee2.png)

**Comment by yob** [comment]
Could it be a TLS version incompatibility?

**Comment by ticky** [comment]
Looks like [`ConnectEx`](https://docs.microsoft.com/en-au/windows/win32/api/mswsock/nc-mswsock-lpfn_connectex?redirectedfrom=MSDN) is only supported in Windows Vista onwards, so maybe it’s not implemented at all, and just responds with an invalid argument error code?

**Comment by pda** [comment]
For context — I was checking this because https://github.com/buildkite/agent/pull/1329 introduces some more specific Windows API calls, and I was wondering if that PR would break the agent on ReactOS. Turns out it was already broken, so no need to worry :)

There's some mention of ConnectEx here: https://reactos.org/wiki/User:Lone_Rifle/kjk_on_ws2
But it's not clear how it relates to the current status of ReactOS.

Anyway, not really worth spending 🧠/🕐 on, unless somebody has a legit use-case for buildkite-agent on ReactOS one day.
