### ISSUE TITLE
[crash] SIGSEGV/Panic due to nil pointer dereference when calling `Write` of `Prefixer` type

### ISSUE THREAD

**Issue by pventuzelo** [buildkite/agent#1338]
# Summary:

During the decoding of some specific bytes, the function `Write` of the `Prefixer` type will trigger a segmentation fault/panic and make the complete program/process to crash.

# Description:

This panic bug occurs when calling `append(out, []byte(p.f())...)` line 56 because out is not large enough. Size of out is determined based on `len(data)` line 41 but later the length of out is not checked before append operation to it.
link: https://github.com/buildkite/agent/blob/a9c89bd9bcc303ba504c47d201e6a104fd5ec765/process/prefixer.go#L56

# Steps To Reproduce:
STEP 1: create a go project: mkdir testing; touch main.go; touch go.mod
STEP 2: go.mod content
``` golang
module main

go 1.15

replace github.com/buildkite/agent => ../

require (
    github.com/buildkite/agent v0.0.0-00010101000000-000000000000
    github.com/buildkite/agent/v3 v3.25.0 // indirect
)
```
STEP 3: main.go content
``` golang
package main

import (
    process "github.com/buildkite/agent/process"
)

func repro_PrefixerWrite(){
    data := []byte("\x0a")
    var out process.Prefixer
    _, _ = out.Write(data)
    // panic: runtime error: invalid memory address or nil pointer dereference
}

func main() {
    repro_PrefixerWrite()
}

// Run with:
// go run main.go
```
STEP 4: Execute the program with: go run main.go

# Supporting Material/References:
This testing program will crash with the following error message:
``` sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4aa078]

goroutine 1 [running]:
github.com/buildkite/agent/process.(*Prefixer).Write(0xc000104f58, 0xc00001a118, 0x1, 0x1, 0x405e65, 0xc000016118, 0x0)
    /XXX/agent/process/prefixer.go:56 +0x238
main.repro_PrefixerWrite(...)
    /XXX/agent/crashPrefixerWrite/main.go:10
main.main()
    /XXX/agent/crashPrefixerWrite/main.go:15 +0x70
exit status 2
```

**Comment by yob** [comment]
Thanks for the clear and well written report @pventuzelo  :heart: 

> This panic bug occurs when calling append(out, []byte(p.f())...) line 56 because out is not large enough. Size of out is determined based on len(data) line 41 but later the length of out is not checked before append operation to it.

Is a missing size check really the root cause, or is it because in the reproduction code the `process.Prefixer` is initialized with default values and not via `process.NewPrefixer()`?

**Comment by pventuzelo** [comment]
Oh my bad, you're right I completely missed that `f` was actually a function. 🙏
