### ISSUE TITLE
S3 uploader support when using EKS with IRSA

### ISSUE THREAD

**Issue by mkandelaars** [buildkite/agent#1356]
Currently the buildkite-agent S3 artifact upload code doesn't support using the new AWS IAM Roles for Service Accounts (IRSA) feature on EKS. When running the Buildkite agent in a container on EKS the current behavior is to look for custom credentials, environment variables, and EC2 Role / Metadata. As of writing, any credentials from a Service Account using IRSA are currently ignored.

PR with proposed fix here #1310

**Comment by chloeruka** [comment]
Good call! Thanks for picking this up, we'll test out your solution and hopefully get that through soon.
