### ISSUE TITLE
S3 uploader support should support session tokens too

### ISSUE THREAD

**Issue by grahamc** [buildkite/agent#1357]
I'd like to have my buildkite agent use an assumed role's credentials to upload. However, to do that, buildkite needs to use a third environment variable in addition to BUILDKITE_S3_ACCESS_KEY_ID and BUILDKITE_S3_SECRET_ACCESS_KEY: it would need an BUILDKITE_S3_SESSION_TOKEN.

**Comment by chloeruka** [comment]
Ah, yep! I see the problem. I might be able to find some time to add this, but if I don't, here's some context:

This should be possible to add to the S3 CredentialsProvider by optionally setting [creds.SessionToken](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/#Value) using the suggested environment variable.

https://github.com/buildkite/agent/blob/d8506f8166026b9b20d71f9cfde3db1d1ac0f257/agent/s3.go#L21

Out of interest, how are you hydrating these values, is it through an environment hook? It occurs to me that the [assumable-roles plugin](https://github.com/cultureamp/aws-assume-role-buildkite-plugin) is a good fit, but on closer inspection it doesn't modify these values used specifically for S3 uploads. 🤔

**Comment by grahamc** [comment]
I have some custom tooling to create agents on my NixOS machines, it looks like this:

```nix
{
  grahamc.buildkite-vault-generic = {
    netboot1 = {
      top_level_approle = "netboot";
      buildkite_token_path = "secret/buildkite/grahamc/token";
      slugs = {
        packet-nix-builder = {
          approle = "buildkite-packet-nix-builder";
          artifact_pointer = "buildkite-artifacts-packet-nix-builder";
        };
      };
    };
  };
```

This creates an agent called "netboot1", which pre-startup fetches its buildkite token from Vault, under the path `secret/buildkite/grahamc/token`, and becomes the Vault approle "netboot".

Then there are different configurations per project slug, and I automatically generate an environment hook. For the `packet-nix-builder` slug, the environment hook becomes the `buildkite-packet-nix-builder` approle. Under that approle, it uses the `artifact_pointer` to find where the artifacts are stored:

1. `buildkite-artifacts-packet-nix-builder` is expanded to `secret/buildkite-artifact/buildkite-artifacts-packet-nix-builder`, which contains a json blob:

```
```

  export VAULT_TOKEN=$(get_token 'buildkite-packet-nix-builder')






  export BUILDKITE_S3_ACL="private"
export BUILDKITE_S3_DEFAULT_REGION=$(/nix/store/a8dhmz00z3zn2ck4x63lw1f2da43x1kh-vault-1.6.0/bin/vault kv get -field bucket_region secret/buildkite-artifact/'buildkite-artifacts-packet-nix-builder')
export BUILDKITE_ARTIFACT_UPLOAD_DESTINATION=$(/nix/store/a8dhmz00z3zn2ck4x63lw1f2da43x1kh-vault-1.6.0/bin/vault kv get -field buildkite_upload_destination_prefix secret/buildkite-artifact/'buildkite-artifacts-packet-nix-builder')/$BUILDKITE_JOB_ID
role_path=$(/nix/store/a8dhmz00z3zn2ck4x63lw1f2da43x1kh-vault-1.6.0/bin/vault kv get -field role_path secret/buildkite-artifact/'buildkite-artifacts-packet-nix-builder')
aws_creds=$(/nix/store/a8dhmz00z3zn2ck4x63lw1f2da43x1kh-vault-1.6.0/bin/vault kv get -format=json "$role_path")
export BUILDKITE_S3_ACCESS_KEY_ID=$(/nix/store/515in6kg2xfd8vcbg5n9xwnk1f3j928f-jq-1.6-bin/bin/jq -r .data.access_key <<<"$aws_creds")
export BUILDKITE_S3_SECRET_ACCESS_KEY=$(/nix/store/515in6kg2xfd8vcbg5n9xwnk1f3j928f-jq-1.6-bin/bin/jq -r .data.secret_key <<<"$aws_creds")
unset aws_creds role_path

(
  export AWS_ACCESS_KEY_ID=$BUILDKITE_S3_ACCESS_KEY_ID
  export AWS_SECRET_ACCESS_KEY=$BUILDKITE_S3_SECRET_ACCESS_KEY

  for  i in $(seq 1 100); do
    if /nix/store/aa8zjzcfbzpr6qdalbz5kmah1za8m4av-awscli-1.18.128/bin/aws sts get-caller-identity; then
      break;
    else
      echo "Trying again in 1s..."
      sleep 1
    fi
  done
)
unset role_path

**Comment by grahamc** [comment]
I have some custom tooling to create agents on my NixOS machines, it looks like this:

```nix
{
  grahamc.buildkite-vault-generic = {
    netboot1 = {
      top_level_approle = "netboot";
      buildkite_token_path = "secret/buildkite/grahamc/token";
      slugs = {
        packet-nix-builder = {
          approle = "buildkite-packet-nix-builder";
          artifact_pointer = "buildkite-artifacts-packet-nix-builder";
        };
      };
    };
  };
```

This creates an agent called "netboot1", which pre-startup fetches its buildkite token from Vault, under the path `secret/buildkite/grahamc/token`, and becomes the Vault approle "netboot".

Then there are different configurations per project slug, and I automatically generate an environment hook. For the `packet-nix-builder` slug, the environment hook becomes the `buildkite-packet-nix-builder` approle. Under that approle, it uses the `artifact_pointer` to find where the artifacts are stored:

1. `buildkite-artifacts-packet-nix-builder` is expanded to `secret/buildkite-artifact/buildkite-artifacts-packet-nix-builder`, which contains a json blob:

```json
{
    "bucket_name": "buildkite-artifacts-xxx",
    "bucket_region": "us-east-1",
    "buildkite_upload_destination_prefix": "s3://buildkite-artifacts-xxx/buildkite-artifacts-packet-nix-builder/",
    "role_path": "aws/creds/buildkite-artifacts-packet-nix-builder",
    "write_prefix": "buildkite-artifacts-packet-nix-builder/*"
}
```

2. The environment hook, when run for this project's slug, uses this data to get credentials and configure the artifacts:

```bash
export BUILDKITE_S3_ACL="private"
export BUILDKITE_S3_DEFAULT_REGION=$(vault kv get -field bucket_region secret/buildkite-artifact/buildkite-artifacts-packet-nix-builder)
export BUILDKITE_ARTIFACT_UPLOAD_DESTINATION=$(vault kv get -field buildkite_upload_destination_prefix secret/buildkite-artifact/buildkite-artifacts-packet-nix-builder)/$BUILDKITE_JOB_ID

role_path=$(vault kv get -field role_path secret/buildkite-artifact/buildkite-artifacts-packet-nix-builder)
aws_creds=$(vault kv get -format=json "$role_path")
export BUILDKITE_S3_ACCESS_KEY_ID=$(jq -r .data.access_key <<<"$aws_creds")
export BUILDKITE_S3_SECRET_ACCESS_KEY=$(jq -r .data.secret_key <<<"$aws_creds")
unset aws_creds role_path

(
  export AWS_ACCESS_KEY_ID=$BUILDKITE_S3_ACCESS_KEY_ID
  export AWS_SECRET_ACCESS_KEY=$BUILDKITE_S3_SECRET_ACCESS_KEY

  echo "Waiting for the Buildkite AWS credentials to become valid..."
  for  i in $(seq 1 100); do
    if aws sts get-caller-identity; then
      break;
    else
      echo "Trying again in 1s..."
      sleep 1
    fi
  done
)
```

It is a bit of sausage, but the levels of approle means other pipelines aren't allowed to accidentally upload artifacts to the wrong bucket or provision other pipeline's secrets.
