### ISSUE TITLE
[Feature Request] Support PowerPC 64-bit Big Endian

### ISSUE THREAD

**Issue by runlevel5** [buildkite/agent#1360]
1stly, I am so happy to know that the agent does support ppc64le :clap: 

I would like to ask if the team could support the binary for the big endian version too.

Many thanks in advance

P/S: I am happy to cook up new PR

**Comment by ticky** [comment]
Hi @runlevel5, I've just gone and added this target to our builds in #1362. We don't have any ppc64 systems on hand to test with, so are you able to give this binary a shot for us and let us know if it's happy?

[buildkite-agent-linux-ppc64-3.26.0.tar.gz](https://github.com/buildkite/agent/files/5833131/buildkite-agent-linux-ppc64-3.26.0.tar.gz)

**Comment by ticky** [comment]
@runlevel5 have you had a chance to test this out?

**Comment by runlevel5** [comment]
Good to go @ticky 

Great thanks

**Comment by ticky** [comment]
Thanks! There'll be a ppc64 build in the next release, for now you can keep using the one I posted here :)
