### ISSUE TITLE
[Suggestion] Mentioning about dbus as a required component for the agent

### ISSUE THREAD

**Issue by runlevel5** [buildkite/agent#1361]
When I compile and run the agent on Alpine Linux 3.13, I got an error that `/etc/machine-id` could not be found.

It turns out that dbus is not pre-installed on certain Linux distro. I think the README should mention have a section outlining all prerequisites external dependencies.

**Comment by ticky** [comment]
Hi @runlevel5, I've added this to the README, thanks for pointing it out.

I think every Linux environment we've used had dbus already, so good to be reminded it's not universal!

**Comment by yob** [comment]
Interesting, I didn't realise the agent relied on `/etc/machine-id`.

Looking at the code it seems we might only use if for tags, and only if the `--tags-from-host` flag is used. Were you using that flag @runlevel5 ?

If so it seems best effort and I'd love to find a way to make the error non-fatal.

**Comment by ticky** [comment]
We also use it in the registration code path, but omitting it _appears_ non-fatal to my eye:

https://github.com/buildkite/agent/blob/3f6b183588248853ce5678d3dde65192112cf431/agent/register.go#L78-L81
