### ISSUE TITLE
Ubuntu uninstall systemd glob error

### ISSUE THREAD

**Issue by plaindocs** [buildkite/agent#1370]
I noticed this `Glob pattern passed to enable, but globs are not supported for this.
Invalid unit name "buildkite-agent@*" escaped as "buildkite-agent@\x2a".`

buildkite-agent version 3.26 3674
Ubuntu 20.04 in a VM

```shell
$ sudo apt-get remove buildkite-agent
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  buildkite-agent
0 upgraded, 0 newly installed, 1 to remove and 3 not upgraded.
After this operation, 36,6 MB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 160410 files and directories currently installed.)
Removing buildkite-agent (3.26.0-3674) ...
Stopping buildkite-agent systemd service
Glob pattern passed to enable, but globs are not supported for this.
Invalid unit name "buildkite-agent@*" escaped as "buildkite-agent@\x2a".
```

**Comment by sj26** [comment]
Nice catch! And very interesting.

It comes from here:
https://github.com/buildkite/agent/blob/main/packaging/linux/scripts/before-remove.sh#L20

This is legit usage with other subcommands like `systemctl start "buildkite-agent@*"` but doesn't seem to work for enable/disable.

But the docs for disable hint that disabling the template file will be enough to disable all instances:
https://www.freedesktop.org/software/systemd/man/systemctl.html#disable%20UNIT…
> Note that this removes all symlinks to matching unit files, including manually created symlinks, and not just those actually created by enable or link.

I'll post a quick PR>
