### ISSUE TITLE
Unable to apply regex to env variable

### ISSUE THREAD

**Issue by crak-mmarcoux** [buildkite/agent#1381]
Hi! 

Trying to export a new variable using a regex and a buildkite defined variable.

my config is the following:
- label: "🔨 Docker Build and Push - Docker HUB"
    key: "docker-build-push"
    env:
      FEATURE: ${BUILDKITE_BRANCH/\feature\/}

The name of my branch is feature/buildkite

When doing this instead of giving me everything after my / (which would result FEATURE=buildkite) it is giving me back feature/buildkite.

Tested on ubuntu, works properly but on the agent never works.
![image](https://user-images.githubusercontent.com/56592790/108012859-6733d000-6fd8-11eb-9705-4f4d85366fee.png)
![image](https://user-images.githubusercontent.com/56592790/108012875-6f8c0b00-6fd8-11eb-87a6-916fccc7b4f9.png)

Thanks!

**Comment by ticky** [comment]
Hi @crak-mmarcoux,

Regexes are not supported here, the agent only handles the POSIX parameter expansions we document here: https://buildkite.com/docs/agent/v3/cli-pipeline#environment-variable-substitution

If you need to rely on Bash- or other shell-specific behaviour you may need to dynamically generate your pipeline YAML, or use the value within your commands.
