### ISSUE TITLE
artifact_paths failed to update files when file name contains # character

### ISSUE THREAD

**Issue by Singwai** [buildkite/agent#1384]
Hi,

After we upload an artifact file with a "#" character in the file name to the build. We will not able to download it using the web interface. We can see that the file name in the s3 link is cut off. 

For example, if the file is named `hello hash #.png`. The last segment of the URL should look like `hello%20hash%20%23.png` instead, we got `hello%20hash%20`. See URL example. 

```
https://s3.amazonaws.com/buildkiteartifacts.com/7993eca9-c06b-4174-ab90-5ed73dd38733/cc062b35-8d32-4ee9-82a1-03a272431b26/8fd21263-83a7-4f4e-bbf3-1103970260ff/67682c35-aa13-4dbc-b704-559de944ee2c/cypress/e2e/surveys/__image_snapshots__/hello%20hash%20?[omitted AWS file signature]
```
We will get a `no such key` exception from S3 when trying to download or open the artifact. 

---

![image](https://user-images.githubusercontent.com/5863227/108431902-c411cf00-7200-11eb-8eda-8fa97cf6f7f6.png)
![image](https://user-images.githubusercontent.com/5863227/108432158-29fe5680-7201-11eb-895b-753da86e2e8e.png)

We can also see the S3 error that the key after the hash character is not in the request. 

---
Here is what I am using in the `pipeline.yml` file. Only files with a `#` character are having this behavior, other files are working fine. 

```
    artifact_paths:
      - "cypress/e2e/surveys/__image_snapshots__/**/*"
 ```

**Comment by ticky** [comment]
Hi @Singwai, thanks for the report.

That looks like an oversight on our part; [`#` in URIs indicates a fragment](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax), which is never sent to the server. We should be URL encoding that `#` as `%23` for that file name to work.

Would you be up for sending us an email at <support@buildkite.com> with a link to that job so we can confirm which part of the system is responsible for this? We should be able to get it sorted fairy easily.

**Comment by Singwai** [comment]
kk will follow up with a support email.

**Comment by ticky** [comment]
We fixed this server-side; future artifacts will correctly handle `#` characters. :)
