### ISSUE TITLE
RPM package for PPC64 and PPC64LE

### ISSUE THREAD

**Issue by runlevel5** [buildkite/agent#1393]
Hi Buildkite

I am running 2 agents on Linux PPC64 (Big Endian) and PPCLE (Little Endian) respectively by compiling / creating custom systemd service files (which are based on the x86_64). I would like to ask if Buildkite could also provide the RPM for these two which would help streamline my setup.

If your devs need access to a proper PowerPC box, the [KernelCafe](https://github.com/KernelCafe/welcome) does offer some free nodes.

I am happy to contribute code changes if it helps.

Many thanks in advance

**Comment by yob** [comment]
I don't think we'd be opposed to the idea, although I must admit PPC isn't on our radar much. Looking at our agent telemetry, there's been a maximum of 1 PPC agent connected in the past week - I assume that's your agent :smile: 

I don't think we'd need access to a PPC instance - go cross compiles the binary and everything else in the package is arch-neutral.
 
#1243 is where @chloeruka added arm64 to the rpm repo. Are PPC64 and PPCLE arches that rpm will recognise, and could it be as simple as adding them to the list in `.buildkite/steps/publish-rpm-package.sh`?

**Comment by runlevel5** [comment]
> I don't think we'd be opposed to the idea, although I must admit PPC isn't on our radar much. Looking at our agent telemetry, there's been a maximum of 1 PPC agent connected in the past week - I assume that's your agent smile

It must be me :). The PPC has been using TravisCI but the recent disruption with new management pushes the community to seek alternatives and I don't see anything better than Builkite Agent. Having been using it at work, I don't see any reason why people should not use it for their OSS projects.

> #1243 is where @chloeruka added arm64 to the rpm repo. Are PPC64 and PPCLE arches that rpm will recognise, and could it be as simple as adding them to the list in .buildkite/steps/publish-rpm-package.sh?

Go does support cross compilation so it should be not an issue. And if it is not, I could set up an agent for you on my box to use

**Comment by runlevel5** [comment]
@chloeruka please let me know if I could be any help

**Comment by keithduncan** [comment]
As this just came up for the deb package too I thought I’d drop some notes on what needs to change for the RPM package to add this too.

The [build step](https://github.com/buildkite/agent/blob/main/.buildkite/pipeline.yml#L285-L292) needs a step dependency on the binary building steps for the architectures it wants to include. The [step script](https://github.com/buildkite/agent/blob/main/.buildkite/steps/build-rpm-packages.sh#L27) needs to invoke the build script for each arch. Then the [build script](https://github.com/buildkite/agent/blob/main/scripts/build-rpm-package.sh#L25-L34) needs support for each new architecture.

We’d welcome a pull request that added these 😄
