### ISSUE TITLE
Problem starting on Ubuntu 12.04

### ISSUE THREAD

**Issue by RohanM** [buildkite/agent#140]
On Ubuntu 12.04, I had an error starting the agent:

    $ sudo service buildkite-agent start
    start: Unknown job: buildkite-agent

I investigated with `init-checkconf`. It's outputting is broken in this version of Ubuntu, but I was able to read its results from its tmp file:

    $ init-checkconf -d /etc/init/buildkite-agent.conf
    $ cat /tmp/init-checkconf-upstart-output.UTdozg6Hr7
    init:/tmp/init-checkconf.DhCWDbF5Mt/buildkite-agent.conf:9: Unknown stanza

Line 9 of /etc/init/buildkite-agent.conf is:

    reload signal USR2

Commenting out this line resulted in the agent starting. Perhaps there would be a way to optionally include that line in later versions of Ubuntu so that the agent works out of the box in 12.04?

**Comment by keithpitt** [comment]
This should be fixed in the latest version of the agent https://github.com/buildkite/agent/releases/tag/v1.0-beta.30 - thanks for letting me know!
