### ISSUE TITLE
docker-compose file ownership

### ISSUE THREAD

**Issue by kplimack** [buildkite/agent#1413]
When running steps in docker-compose that produce artifacts, the artifacts end up being owned by root and then cleanup fails.  Im sure Im not the first to stumble into this, is there a solution before I do [terrible] things ?

**Comment by moensch** [comment]
The containers still run as whatever is defined as the `USER` in your `Dockerfile`.

If you're using the official docker-compose plugin, there's a parameter you can pass in a magical parameter that maps your build user: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin#propagate-uid-gid-optional-run-only-boolean

**Comment by kplimack** [comment]
@moensch much obliged, Samuel! 
👏

**Comment by keithduncan** [comment]
Thanks for commenting with the fix for this issue @moensch 👏 I’m going to close this issue but feel free to re-open or leave another comment if we can help further.
