### ISSUE TITLE
Is it possible to clone a subdirectory of a repo for a build agent?

### ISSUE THREAD

**Issue by timendez** [buildkite/agent#1461]
I have a very large repo (~100gb). In that repo, there exists a more manageable directory (~500mb). I want to use Buildkite to build a project in that subdirectory.

It is possible to clone a subdirectory in a repo using `git clone --filter`. However, I'm not sure where I would add this command for a specific pipeline. Additionally, I'll need to run `git sparse-checkout set my-sub-dir` afterwards.

The repo is so large because there is data that is generated and sent across all sorts of subdirectories so it can't split up as content needs to be in lockstep.

Thanks!

**Comment by keithduncan** [comment]
This should be possible using a [`checkout` hook](https://buildkite.com/docs/agent/v3/hooks#available-hooks) in your agent, or in a plug-in.

The checkout hook takes over responsibility for fetching [`BUILDKITE_COMMIT`](https://buildkite.com/docs/pipelines/environment-variables#bk-env-vars-buildkite-commit) source code from the [`BUILDKITE_REPO`](https://buildkite.com/docs/pipelines/environment-variables#bk-env-vars-buildkite-repo) and placing it into the [`BUILDKITE_BUILD_CHECKOUT_PATH`](https://buildkite.com/docs/pipelines/environment-variables#bk-env-vars-buildkite-build-checkout-path).

Let us know whether that works for you and if not we can figure out an alternative! 😄

**Comment by timendez** [comment]
Is it possible to have it configured for only a single pipeline? I can't seem to specify it any lower than the agent level

**Comment by keithduncan** [comment]
> Is it possible to have it configured for only a single pipeline?

The two ways I can think of to do this would be to use [`BUILDKITE_PIPELINE_NAME`](https://buildkite.com/docs/pipelines/environment-variables#bk-env-vars-buildkite-pipeline-name) or [`BUILDKITE_PIPELINE_SLUG`](https://buildkite.com/docs/pipelines/environment-variables#bk-env-vars-buildkite-pipeline-slug) in your agent hooks to determine whether to enable the behaviour.

Alternatively, plug-ins are configured at the pipeline level but must be included in each step. There’s no way to apply them 'globally' to a pipeline today I’m afraid.
