### ISSUE TITLE
buildkite-agent config field to delay buildkite-agent start

### ISSUE THREAD

**Issue by OliverKoo** [buildkite/agent#1463]
**Context**

I am running buildkite-agent on mac EC2 instances. I have observed the following race condition.

buildkite-agent is kicked off as a LaunchAgent `/Users/buildkite-agent/Library/LaunchAgents/com.buildkite.buildkite-agent.plist` when machine boot and I have auto login set up.

I am also using a userdata script that gets run at the initial boot of the EC2 instances. It is the same framework that CI Elastic Stack is doing (@yob's [bk-install-elastic-stack.sh](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/linux/conf/bin/bk-install-elastic-stack.sh)). This script adjust the buildkite-agent configuration (name, tags, disconnect-after-idle....etc) base on env variables.This is a brilliant way to adjust buildkite configuration for different queues without alternating the AMI.

**Issue**

However, the adjusted config is not picked up sometimes due to buildkite-agent got launched just milliseconds before the userdata script completed running. 

userdata script log

```
2021/07/07 12:08:14.979286 Successfully completed module [ExecuteUserData] (type: userdata, group: 4) with message: successfully ran user data with stdout: [] and stderr: [#!/bin/bash -xv
...
BUILDKITE_STACK_NAME="ios-agent-queue" \
...
ec2-user@ip-xx-xxx-x-xx ~ % cat /var/log/amazon/ec2/ec2-macos-init.log 
+ AWS_REGION=us-east-1
+ /usr/local/bin/bk-install-elastic-stack.sh
]
2021/07/07 12:08:14.979444 Successfully completed processing of priority level 4
```

buildkite-agent start log
```
ec2-user@ip-xx-xxx-x-xx ~ % cat /Users/buildkite-agent/.buildkite-agent/log/buildkite-agent.log

   _           _ _     _ _    _ _                                _
  | |         (_) |   | | |  (_) |                              | |
  | |__  _   _ _| | __| | | ___| |_ ___    __ _  __ _  ___ _ __ | |_
  | '_ \| | | | | |/ _` | |/ / | __/ _ \  / _` |/ _` |/ _ \ '_ \| __|
  | |_) | |_| | | | (_| |   <| | ||  __/ | (_| | (_| |  __/ | | | |_
  |_.__/ \__,_|_|_|\__,_|_|\_\_|\__\___|  \__,_|\__, |\___|_| |_|\__|
                                                 __/ |
 https://buildkite.com/agent                    |___/

2021-07-07 12:08:09 NOTICE Starting buildkite-agent v3.30.0 with PID: 582
2021-07-07 12:08:09 NOTICE The agent source code can be found here: https://github.com/buildkite/agent
2021-07-07 12:08:09 NOTICE For questions and support, email us at: hello@buildkite.com
2021-07-07 12:08:09 INFO   Configuration loaded path=/usr/local/etc/buildkite-agent/buildkite-agent.cfg
2021-07-07 12:08:09 INFO   Running builds within a pseudoterminal (PTY) has been disabled
2021-07-07 12:08:09 INFO   Fetching EC2 meta-data...
2021-07-07 12:08:09 INFO   Successfully fetched EC2 meta-data
2021-07-07 12:08:09 INFO   Fetching EC2 tags...
2021-07-07 12:08:11 INFO   Successfully fetched EC2 tags
2021-07-07 12:08:11 INFO   Registering agent with Buildkite...
```

**Possible Solution**

If there is a config field `delay-start-second=30` then the race condition can be avoided.

Also open to other solutions 🙏 

note: I have also tried to launch the agent as part of the userdata script post buildkite-agent config adjustment but no luck so far.

**Comment by keithduncan** [comment]
Thanks for opening this issue 🙇‍♂️ I’ll have a think on what the best way to configure the agent config on Mac from the UserData script is 🤔

**Comment by keithduncan** [comment]
I wonder if supporting [hot reloadable config](https://github.com/buildkite/agent/issues/476) for the buildkite-agent is the way to support this.

**Comment by keithduncan** [comment]
> buildkite-agent is kicked off as a LaunchAgent `/Users/buildkite-agent/Library/LaunchAgents/com.buildkite.buildkite-agent.plist` when machine boot and I have auto login set up.

I’ve been looking into this today in concert with the Host Resource Group auto-provision to see what we could provide in terms of a CloudFormation template to customers. I’ve discovered that it is possible to defer installing the Launchd Agent configuration until the UserData script, allowing you to edit the Buildkite Agent configuration file before the service is started at all.

When booting an AMI that has auto-login enabled, there are two possible scenarios for the UserData script to handle. The first scenario is auto-login hasn’t occurred yet but will shortly. The second scenario is when auto-login has already occurred. Auto-login takes place concurrently with respect to the UserData script executing as root, so our solution needs to handle both while also allowing modifications to the buildkite-agent configuration file.

This is the UserData that I am using:

```bash
#!/bin/bash
PDISK=$(diskutil list physical external | head -n1 | cut -d" " -f1)
APFSCONT=$(diskutil list physical external | grep "Apple_APFS" | tr -s " " | cut -d" " -f8)
yes | diskutil repairDisk $PDISK
diskutil apfs resizeContainer $APFSCONT 0
user=ec2-user
su - "${!user}" -c 'brew install buildkite/buildkite/buildkite-agent'
config="$(brew --prefix)"/etc/buildkite-agent/buildkite-agent.cfg
sed -i '' "s/xxx/${BuildkiteAgentToken}/g" "${!config}"
echo "tags=\"queue=${BuildkiteAgentQueue}\"" >> "${!config}"
echo "tags-from-ec2=true" >> "${!config}"
su - "${!user}" -c 'brew services start buildkite/buildkite/buildkite-agent'
```

My testing has shown this works in both scenarios outlined above.

In the first scenario, the configuration file is written, followed by the launchd agent configuration, followed by a `launchctl load`. The `launchctl load` will fail because Launch Agents default to `LimitLoadToSessionType: Aqua` if not otherwise specified and there is no Aqua session running. But that is okay because subsequently auto-login will take place, and the Launch Agent will be loaded and started.

In the second scenario auto-login has already occurred by the time we are executing our UserData script. In this scenario, invoking `launchctl load` as the `ec2-user` works as we expect because the GUI session is active, and the agent is booted.

> note: I have also tried to launch the agent as part of the userdata script post buildkite-agent config adjustment but no luck so far.

Please let me know if the above is helpful in getting this to work! I’ll keep this issue open in the meantime 😄

**Comment by keithduncan** [comment]
I’m going to close this for now but let me know if I can help further with boot-time macOS agent configuration :bow:

**Comment by OliverKoo** [comment]
Hey @keithduncan thank you for the follow ups! 🙇 sorry for the delayed reply.

My AMI current set up script is`install-buildkite-agent-mac.sh`
```
# install buildkite agent via brew then write some config and set up perm....etc
...
echo "Adding buildkite service plist template..."
sudo mkdir -p /Users/buildkite-agent/Library/LaunchAgents
sudo cp /tmp/conf/buildkite-agent/LaunchAgents/com.buildkite.buildkite-agent.plist /Users/buildkite-agent/Library/LaunchAgents/com.buildkite.buildkite-agent.plist
sudo chmod 775 /usr/local/var/log
sudo chown root:wheel /Users/buildkite-agent/Library/LaunchAgents/com.buildkite.buildkite-agent.plist
sudo launchctl load -w /Users/buildkite-agent/Library/LaunchAgents/com.buildkite.buildkite-agent.plist

echo "Configure auto-login of buildkite-agent user"
sudo cp /tmp/conf/buildkite-agent/kcpassword /private/etc/kcpassword
sudo chown -R root:wheel /private/etc/kcpassword
sudo defaults write /Library/Preferences/com.apple.loginwindow "autoLoginUser" 'buildkite-agent'
...
```
so I guess the buildkite-agent  LaunchAgent is "pre-loaded" in the AMI if that make sense.

I am going to comment out `sudo launchctl load -w /Users/buildkite-agent/Library/LaunchAgents/com.buildkite.buildkite-agent.plist` this line then add 
`su - "${user}" -c 'brew services start buildkite/buildkite/buildkite-agent'` to UserData script and give it a shot

Also I am curious is the code that handle increasing the disk size is crucial or not? I have that as part of my AMI creation as well (because apparently after resizing the disk it requires a [reboot](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-mac-instances.html#mac-instance-increase-volume) ?). Does it work for you as part of the UserData script?

**Comment by keithduncan** [comment]
> add [...] to UserData script and give it a shot

Great! Let us know how it goes 😄 

> Does it work for you as part of the UserData script?

I haven’t had to reboot the instance after issuing the `diskutil apfs resizeContainer $APFSCONT 0` command, I *think* those docs are referring to online growing/resizing the EBS volume itself and then trying to use the new space on an already running instance.

**Comment by OliverKoo** [comment]
alright this is what I see - 

commeting out `sudo launchctl load........ buildkikte-agent.plist` and use `su - "${user}" -c 'brew services start buildkite/buildkite/buildkite-agent'` didn't cause any issue but I don't think it worked. I still think the agent somehow was started before the config gets modified. I see  around 5% of the agent name as `ip-x-x-x-x.ec2.internal` in the buildkite console. That is the indicator that the agent got started before the UserData script modified its names. Part of the UserData script modified and set agent name to ios-agent-queue-<instance id>-<pid>.

I have auto-login configured. I am wondering if that combined with the existence of LaunchAgent buildkite-agent.plist cause buildkite-agent to be automatically kick off when the machine is booted?

**Comment by keithduncan** [comment]
> I have auto-login configured. I am wondering if that combined with the existence of LaunchAgent buildkite-agent.plist cause buildkite-agent to be automatically kick off when the machine is booted?

Yes you’ll need to make sure that the launchd.plist for the buildkite-agent _doesn’t_ exist in the AMI, otherwise writing the configuration will race with the service starting from auto-login. That should give you the freedom to write the configuration from `UserData` and then start the service.
