### ISSUE TITLE
Default agent name to be `%hostname-%n`

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#147]
Whilst writing the Ubuntu docs for running multiple agents on the one machine I realised we could skip the "don't forget to update the name in your config file" if we made the default value of name to be `%hostname-%n`.

Also the problem with `my-agent-%n` and the new cfg format is that you can't specify `%hostname-%n`, so perhaps we need to add that too?

**Comment by keithpitt** [comment]
This is done now! :dancer:
