### ISSUE TITLE
apt repository missing `ppc64el` architecture

### ISSUE THREAD

**Issue by staticfloat** [buildkite/agent#1472]
I am trying to install the buildkite agent through `apt` as described [here](https://buildkite.com/docs/agent/v3/debian), and I noticed that the `ppc64el` architecture seems to be missing.  The other architectures that I care about (`amd64`, `armhf`, `arm64`) all exist, but `ppc64el` doesn't.  This can be verified by trying to download the `Packages.gz` file:

```
# curl -L https://apt.buildkite.com/buildkite-agent/dists/stable/main/binary-ppc64el/Packages.gz
<html>
<head><title>404 Not Found</title></head>
<body>
...
```

**Comment by keithduncan** [comment]
It looks like our [debian](https://github.com/buildkite/agent/blob/main/.buildkite/pipeline.yml#L273-L283) build step doesn’t depend on any of the `ppc*` artifacts.

Support is also missing from the [step script](https://github.com/buildkite/agent/blob/main/.buildkite/steps/build-debian-packages.sh#L27) and [individual arch](https://github.com/buildkite/agent/blob/main/scripts/build-debian-package.sh#L25-L38) build script.

We’d welcome adding support for this if you’re able to contribute a pull request!
