### ISSUE TITLE
[panic]  runtime error: index out of range [255] with length 255

### ISSUE THREAD

**Issue by scv119** [buildkite/agent#1478]
We've seen following error in our buildkite jobs: [example](https://buildkite.com/ray-project/ray-builders-branch/builds/2657#952b0a74-b8c7-4d13-86a2-b84655684a9a)

Though I'm not too familiar with go, but looks like https://github.com/buildkite/agent/blob/main/bootstrap/redactor.go#L19
 should be 256 instead of 255?

```
panic: runtime error: index out of range [255] with length 255
--
  |  
  | goroutine 81 [running]:
  | github.com/buildkite/agent/v3/bootstrap.(*Redactor).Write(0xc000400000, 0xc0004bc000, 0x21c, 0x8000, 0x21c, 0x0, 0x0)
  | /work/bootstrap/redactor.go:125 +0xdd7
  | io.copyBuffer(0xf22900, 0xc000400000, 0xf23720, 0xc00052c140, 0xc0004bc000, 0x8000, 0x8000, 0xdf4970, 0xc0000457c0, 0x762325)
  | /usr/local/go/src/io/io.go:425 +0x21c
  | io.Copy(...)
  | /usr/local/go/src/io/io.go:382
  | github.com/buildkite/agent/v3/process.(*Process).Run.func2(0xc000536e00, 0xc00052c140, 0xc000510e90, 0xc000522c40)
  | /work/process/process.go:181 +0xa9
  | created by github.com/buildkite/agent/v3/process.(*Process).Run
  | /work/process/process.go:176 +0x39c
```

**Comment by keithduncan** [comment]
Hi @scv119 thank you for reporting this, we’ll look to release a bugfix for this shortly.

In the meantime there is an escape hatch to disable the redactor if you set the `redacted-vars` agent configuration to an empty string, using the config file or command line flag.

Sorry you have run into this, we’ll get it fixed up for you :bow:

**Comment by scv119** [comment]
@keithduncan thank you so much!
cc @rkooo567

**Comment by simon-mo** [comment]
thanks! we rollbacked to previous agent version for now as it's a bit hard to configure agent flags with elastic-ci-stack (have to specify custom bootstrap script).

**Comment by keithduncan** [comment]
The fix for this has been incorporated into the Elastic CI Stack v5.5.1 which is building now and will be available in the next hour or so https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v5.5.1
