### ISSUE TITLE
Cancelled jobs report an exit code of 0 on Windows

### ISSUE THREAD

**Issue by keithduncan** [buildkite/agent#1489]
This is inconsistent with Linux (haven’t tested on macOS). We should make this behaviour the same across all operating systems.

**Comment by twometresteve** [comment]
Works fine for us here on macOS, but fixing it on Windows would be great - thank you.

**Comment by staticfloat** [comment]
I can confirm that this is occurring as well.  If there's any need for debugging (we have a fleet of Windows VMs that we run in buildkite) I'd be happy to deploy changes for testing, etc...

**Comment by JustinTether** [comment]
We're also running into this issue which has been causing some confusion when looking at a green cancelled step -- We found that we could get more accurate states by removing the `artifact_paths` keys from our steps and artifacting manually
