### ISSUE TITLE
Buildkite-agent spawn in conjunction with resource limits.

### ISSUE THREAD

**Issue by williamblevins** [buildkite/agent#1508]
Is there a mechanism to use `buildkite-agent --spawn=#` in conjunction with some sort of resource limit (or just a resource limit model)?

Example: `buildkite-agent --spawn=4` with host having `cpu=10`.

Host would accept up to 4 jobs so long as the resource limit is not exceeded.

**Comment by keithduncan** [comment]
There isn’t support for this in the agent itself, I’d consider resource limiting to be in the domain of your agent _process management_ or _orchestration tool_, e.g. a custom systemd job, EC2 instance sizing, ECS container sizing, or kubernetes container limits.

You may also be interested in the [`--acquire-job` flag](https://buildkite.com/changelog/129-one-shot-agents-with-the-acquire-job-flag) which enables you to schedule each job individually and also puts you in control of how much oversubscription of the shared resource is appropriate.

I hope that answers your question, let me know if I can provide more detail on anything above 😄
