### ISSUE TITLE
Allow buildkite agents print logs to stdout

### ISSUE THREAD

**Issue by olehb** [buildkite/agent#1512]
Is there a way to make buildkite agents print job logs into stdout in addition to to sending them buildkite?

We use custom docker image to run buildkite agents. We would like to have build logs printed to stdout, so they flow into our centralized logging system.

Currently only high-level job start/stop information is printed into console logs:
```
2021-09-21 23:15:11 INFO   infra Starting job xxxx-xxxxx-xxxxxx
2021-09-21 23:15:11 INFO   infra [Process] Process is running with PID: 123456
2021-09-21 23:15:12 INFO   infra Process with PID: 123456 finished with Exit Status: 0, Signal: nil
```

**Comment by keithduncan** [comment]
Hi @olehb, you might be able to use a [custom bootstrap handler](https://buildkite.com/docs/agent/v3/securing#customizing-the-bootstrap) for this. The Buildkite Agent spawns a bootstrap process per-job and forwards the logs from that process to the Buildkite service. You could customise the bootstrap handler with a process which executes the normal bootstrap handler and forwards the received log output to both `stdout` (for the Buildkite Agent to send to the Buildkite service) and your own log sink for your centralised logging system.
