### ISSUE TITLE
Installing on Debian 7.x

### ISSUE THREAD

**Issue by phindmarsh** [buildkite/agent#156]
Found a couple of issues with the .deb installer for Debian 7.x (specifically 7.8). 

Firstly, we use a Debian AMI from the AWS marketplace which by default has several files in the `/etc/init` directory but doesn't actually use upstart. This means the [`after-install-and-upgrade.sh`](https://github.com/buildkite/agent/blob/master/packaging/linux/scripts/after-install-and-upgrade.sh) script it incorrectly chooses upstart as the init system. It seems like the AWS AMI has several upstart based init scripts for cloud-config etc, hence why the folder exists but is never used.

Perhaps we need to investigate other ways of [detecting the init system](http://unix.stackexchange.com/questions/18209/detect-init-system-using-the-shell) as folder bases discovery seems a bit flakey. A quick fix might be to just look for `/etc/init.d` first since `sysvinit` is the default Debian init system and upstart isn't that common. I'm happy to help with this where I can, but I'm not that familiar with this stuff.

When working around this I also found that even if the init system is correctly detected the script can't be copied to `/etc/init.d/buildkite-agent.sh` because the `/usr/share/buildkite-agent/lsb/buildkite-agent.conf` was renamed a few days ago (to `buildkite-agent.sh`). Changing the command on [line 80](https://github.com/buildkite/agent/blob/master/packaging/linux/scripts/after-install-and-upgrade.sh#L80) of `after-install-and-upgrade.sh` to fix the filename and all works as expected.

**Comment by phindmarsh** [comment]
Oh, also the `buildkite-agent.sh` needed to be made `+x` to allow it to be executed.

**Comment by keithpitt** [comment]
I just fixed the first part of this problem in master: https://github.com/buildkite/agent/commit/d538f43eb61d3e364f6dc880a4f3731ba44e09c1

Can you run: `initctl --version` on your system for me?

**Comment by keithpitt** [comment]
I've just tested installation on Debian 7, and it all works like a charm now. Thanks for submitting the bug report!! :heart:

**Comment by keithpitt** [comment]
(All the fixes are in beta 33)

**Comment by phindmarsh** [comment]
Perfect, thank you!






On Mon, May 25, 2015 at 1:28 PM -0700, "Keith Pitt" <notifications@github.com> wrote:












(All the fixes are in beta 33)
