### ISSUE TITLE
Incorrect error message when artifact uploading returns 500

### ISSUE THREAD

**Issue by jradtilbrook** [buildkite/agent#1565]
**Is your feature request related to a problem? Please describe.**
If an artifact upload fails with a 500 response code, an error message is printed showing it will retry 10 times when in fact the code is written to not retry for this error code. So it's a bit confusing to users.

<details>
<summary>Example error message in job logs:</summary>

![Screen Shot 2022-02-24 at 14 18 59](https://user-images.githubusercontent.com/6128798/155469330-bec53c06-4ac2-4756-9543-a91ef38c18bf.png)

</details>

Responsible code: https://github.com/buildkite/agent/blob/61a06503fe330d93f00415c99d841215d82f8b4f/agent/artifact_batch_creator.go#L75

**Describe the solution you'd like**
I think this should print an accurate error message that it will not be retrying.

**Describe alternatives you've considered**
It could also retry as it states 🤷

**Comment by yob** [comment]
It's interesting that we're intentionally not retrying on 500. I assume we'll retry on 502/503 from the load balancers though?

The check for 500 was added in ee417c3754ddcd426ac9291e6f728aff4e55ca7d - @keithpitt any idea what 2015 Keith was thinking when making that commit? 😂

**Comment by jradtilbrook** [comment]
Yeah that's my assumption because I fairly sure I've seen it actually retry in the past - although it could be the meta-data command I'm thinking of.

One thought for the reasoning behind this is a thundering heard type issue - if we are having an incident, retrying is just going to get worse.

I also think there are multiple places it could retry - in the initial request to the artifacts API, and then to the pre-signed S3 URL (I think that's how it works anyway)

**Comment by toolmantim** [comment]
Confusing! I would have expected it to retry, with an exponential jittered back-off like other things 🤔
