### ISSUE TITLE
Use system file locks for mirror clone operations

### ISSUE THREAD

**Issue by KevinGreen** [buildkite/agent#1622]
**Is your feature request related to a problem? Please describe.**
We’re running multiple agents on the same EC2 instance with ECS and we’re seeing an issue when the agent is killed while checking out the repo using the experimental git mirror feature. 

In this case the agent never had a chance to release the lock because we deployed and it was hard killed by ECS because the agent didn't stop before the SIGINT timeout expired and now any other builds on the same EC2 instance are failing to grab the clone lock because it's a shared mounted directory between all the agents.

Digging through the agent source, it seems like the agent is using https://github.com/nightlyone/lockfile to do file locking. The library manages temporary files itself https://github.com/nightlyone/lockfile/blob/master/lockfile.go#L205 and when the agent is forcefully killed the pid file is left on disk with the old agent pid still reserving the lock. It seems like when it tries to find if the owner of the lock is still running it can't because it’s from another docker container so it’ll return nil here: https://github.com/nightlyone/lockfile/blob/master/lockfile.go#L70 which will just see if it matches the current pid which it won’t https://github.com/nightlyone/lockfile/blob/master/lockfile.go#L146.

This issue is mentioned in this old issue in the lockfile repo https://github.com/nightlyone/lockfile/issues/25#issuecomment-454053849

**Describe the solution you'd like**
Our current build system uses `flock` https://linux.die.net/man/2/flock to implement locking for the exact same use case. Flock uses the operating system's native locking when available which uses file descriptors to ensure if the process holding the lock is killed the file descriptors are automatically cleaned up. I found https://github.com/gofrs/flock which is an alternative go library that uses flock sys calls internally with a very similar interface to lockfile that could be used as a replacement. We've used flock successfully between docker containers with shared volumes and mounts from the host system.

**Describe alternatives you've considered**
https://github.com/nightlyone/lockfile/issues/25 suggests storing additional metadata to determine if the lock file is invalid. I don't think that's as good as using flock since it's more work and won't be as reliable.

**Additional context**
The log we see until we terminate the EC2 instance on any agent running is
```
[2022-04-27T21:31:14Z] # Could not acquire lock on "/var/reference_repos/repo.clonelock" (Locked by other process)
[2022-04-27T21:31:14Z] # Trying again in 1s...
...
```
repeated until the lock timeout is reached.

**Comment by moskyb** [comment]
@KevinGreen this is a really interesting one! i can totally understand your frustration here, it's absolutely not an ideal solution. i'd imagine that it would be even worse if the git mirror was being shared across multiple machines, ie with an EFS mount.

The [flock](https://github.com/gofrs/flock) library you posted looks really interesting, but in my (admittedly extremely limited) testing, it seems like equivalent lockfiles don't propagate locked-ness properly - ie, i have some test code:

```Go
package main

import (
	"fmt"
	"time"

	"github.com/gofrs/flock"
)

func main() {
	go func() {
		lock := flock.New("./cool.lock")
		lock.TryLock()
		time.Sleep(5 * time.Second)
		lock.Unlock()
	}()

	lock := flock.New("./cool.lock")
	slept := time.Duration(0)
	for {
		if slept > 7*time.Second {
			break
		}
		state := "unlocked"
		if lock.Locked() {
			state = "locked"
		}
		fmt.Printf("cool.lock is %s\n", state)

		time.Sleep(500 * time.Millisecond)
		slept += 500 * time.Millisecond
	}
}
```

which outputs 
```
$ go run main.go
cool.lock is unlocked
cool.lock is unlocked
# ...
cool.lock is unlocked
cool.lock is unlocked
```

if i'm reading this output correctly (which it's entirely possible that i'm not! please correct me if i'm wrong) it seems like this wouldn't fulfill our needs of locking the git mirror directory between competing agents.

i'm happy to work with you on finding a better solution though! i agree that what we have is less than ideal.

**Comment by moskyb** [comment]
> Our current build system uses flock https://linux.die.net/man/2/flock to implement locking for the exact same use case

i'd be really interested in knowing more about how this works - if it's something we could integrate into the agent, everyone wins :)

**Comment by KevinGreen** [comment]
Hi @moskyb, thanks for the quick response!

I hadn't used the gofrs/flock library before posting so I'm definitely not very used to it.

I was wondering if flock.Locked() was doing something to the lock itself so I added more logging and switch it to doing a read lock explicitly. I added logging and it looked like the go routine wasn't actually getting the lock before running the sleep call. It doesn't look like lock.TryLock() will block and since the main function grabs a read lock it may not be unlocked before it runs TryLock(). I think switching to Lock() would block until it can grab it but I tried the following code successfully.

```
package main

import (
        "fmt"
        "time"

        "github.com/gofrs/flock"
)

func main() {
        go func() {
                lock := flock.New("./cool.lock")
                locked, _ := lock.TryLock()
                fmt.Printf("We got the lock? %v\n", locked)
                fmt.Printf("Going to sleep\n")
                time.Sleep(5 * time.Second)
                fmt.Printf("Finished sleeping\n")
                lock.Unlock()
        }()

        lock := flock.New("./cool.lock")
        slept := time.Duration(0)
        for {
                if slept > 7*time.Second {
                        break
                }
                state := "unlocked"
                gotLock, _ := lock.TryRLock()
                if !gotLock {
                        state = "locked"
                }
                fmt.Printf("cool.lock is %s\n", state)
                lock.Unlock()

                time.Sleep(500 * time.Millisecond)
                slept += 500 * time.Millisecond
        }
}
```
With these changes I see:
```
$ go run main.go
cool.lock is unlocked
We got the lock? true
Going to sleep
cool.lock is locked
cool.lock is locked
cool.lock is locked
cool.lock is locked
cool.lock is locked
cool.lock is locked
cool.lock is locked
cool.lock is locked
cool.lock is locked
Finished sleeping
cool.lock is unlocked
cool.lock is unlocked
cool.lock is unlocked
cool.lock is unlocked
cool.lock is unlocked
```

**Comment by moskyb** [comment]
oooh that's very nice! that could be really useful.

@KevinGreen if you're keen you're more than welcome to submit a PR for this, otherwise, i'll add it to our backlog of things to do, and we'll get to it eventually.

**Comment by KevinGreen** [comment]
Hi Ben, I opened a PR to try this out https://github.com/buildkite/agent/pull/1624. We're seeing this pretty often as we're treating our buildkite infrastructure pretty roughly during testing.
