### ISSUE TITLE
Allow agents to drain their job before exiting without signal propagation 

### ISSUE THREAD

**Issue by dannyfallon** [buildkite/agent#1637]
## Is your feature request related to a problem? Please describe

EC2 offers two early notification systems for instances which are about to  be terminated:
* EC2 Spot Instance Termination notices which arrive 2 minutes before the instance is terminated
* EC2 Capacity Rebalancing notifications which are sent to the instance when the risk of being terminated is elevated. These arrived at least 2 minutes before the instance is terminated, usually more. They only fire if capacity balancing is enable.

We run over 2000 agents AWS EC2 Spot instances. We do not run in spawn mode, so we run multiple agent processes per machine. Our Buildkite jobs on this fleet take ~3 minutes from start to finish. The instance types we have chosen (m6i/r6i) are subject to high rates of churn. This churn has a large impact on our stability and results in jobs exiting mid-way through because right now our listener for these EC2 notices uses `systemd` to stop the agent with a SIGTERM signal but this sends a SIGTERM to the running job. This which is something we want to avoid. 

## Describe the solution you'd like

Sending a SIGUSR1/2 to the agent will result in the agent acknowledging the signal, stop polling for new jobs, disconnecting and exiting after all running jobs are finished. If no jobs are being run on receipt of the signal the agent should immediately disconnect and exit.

### Run in `disconnect-after-job` mode:

I have considered running all of our agents with `disconnect-after-job` enabled and leveraging `systemd` to restart the agent process. When we receive a notice we can just unload the systemd service, and the next time the agent finishes a job it'll disconnect, exit and not restart. I chose not to do this for two reasons, all around time delays:

1. Right now as soon as a job is finished the agent will request the next job from the queue without waiting for a ping interval but in this solution the agent needs to terminate, restart, reconnect and then ask for a job. 
2. There is a race condition I reported to Buildkite support where after an agent connects it takes the Buildkite Dispatcher time to realise there's a new agent available. This can result in the first ping from a newly started agent not receiving a job, even though there is work on the queue. The agent then waits for the next ping interval (10s) before trying again which is another delay we're trying to avoid.

### Trap the SIGTERM ourselves in our code

I have considered not making this the responsibility of the agent and instead trying to trap the SIGTERM sent by the agent to the in the command it's running. With this solution we need to make every command we run in our pipeline aware that if it gets a SIGTERM or some other cancellation signal from the agent that it _may_ need to be swallowed without action in the case of the cause of the signal being an EC2 notice. This doesn't feel like it should be the concern of the pipeline's commands/scripts though, since we're trying to make the agent drain existing jobs without taking new ones.

**Comment by dannyfallon** [comment]
This feature is so great you already built it. And the reason it doesn't work for us is because we aren't using an updated `systemd` service configuration that include the fix from https://github.com/buildkite/elastic-ci-stack-for-aws/pull/521. What a brutal discovery after I spent the time to write this up. Still, a happy result so maybe next time I'll land on a winning feature!

**Comment by moskyb** [comment]
what a shame to see such a good issue go to waste! very glad past buildkite solved this problem for you ^_^

**Comment by com6056** [comment]
Is there a way to do this in the buildkite agent docker image? We're seeing similar behavior with the agent just sending on the SIGTERM to the jobs which kills them before they can gracefully complete.

**Comment by com6056** [comment]
Created https://github.com/buildkite/agent/issues/1758 actually to track it, think I narrowed down the issue
