### ISSUE TITLE
Feature Request: setproctitle support.

### ISSUE THREAD

**Issue by byroot** [buildkite/agent#169]
Context:

I noticed an agent was reported as `lost` and SSHed into the box, but we're running 16 agents per box so identifying who's who is complicated:

```
buildki+   1506  0.9  0.0 542756 15028 ?        Sl   18:18   1:34 /usr/bin/buildkite-agent start
buildki+   1507  0.8  0.0 542756 13060 ?        Sl   18:18   1:20 /usr/bin/buildkite-agent start
buildki+   1511  1.8  0.0 542756 16288 ?        Sl   18:18   2:59 /usr/bin/buildkite-agent start
....
```

A relatively common practice for task oriented daemons is to report their key state thought the proc title.

It would really be nice to see from `ps aux` the agent id, as well as maybe it's state and if it's processing something.

Ref: https://github.com/ErikDubbelboer/gspt which handle X-platform setproctitle.

cc @xthexder

**Comment by keithpitt** [comment]
Ah nice! I've always wanted to do this - but I hadn't found a package that let me do it. Thanks for the link! Expect to see it in the agent soon! :+1:

**Comment by keithpitt** [comment]
Behold!

<img width="1221" alt="screen shot 2015-07-29 at 6 33 44 pm" src="https://cloud.githubusercontent.com/assets/25882/8971674/9a15b38c-3620-11e5-9432-b853fa81d878.png">

**Comment by byroot** [comment]
\o/ :heart:

**Comment by keithpitt** [comment]
@byroot sorry to be the bearer of bad news, but I had to get rid of it. It required `CGO`, which means I can't cross compile anymore (boo). There doesn't seem to be a way to do in Go at the moment :cry:

**Comment by toolmantim** [comment]
Is there a way to scope it so it's for the linux build only?

**Comment by wolfeidau** [comment]
Yeah this will only work if you build ON linux because CGO.

**Comment by keithpitt** [comment]
Yeah, trying now. The issue is compiling for ARM and 386. @wolfeidau this is what I'm trying: https://github.com/buildkite/agent/commit/ead3024f287c33044c579de00e531e433f5b4001

**Comment by wolfeidau** [comment]
Make sure you scope it ONLY for your main arch first i reckon, so linux/x64

**Comment by keithpitt** [comment]
Can you do that with the `+// +build !linux` directive?

**Comment by keithpitt** [comment]
Ok, looks like I can scope it to just linux/amd64 - which is pretty much everyone anyway. I'll ship it with support for this platform only for now! :dancers:
