### ISSUE TITLE
Ability to change `git clean` behaviour to also include `-x`

### ISSUE THREAD

**Issue by keithpitt** [buildkite/agent#173]
`-x` will also remove files that are included in the `.gitignore` list. So essentially a `-x` clean is a true clean of the repo.

**Comment by tommeier** [comment]
:+1: (also submodule commands using clean) (they may also require a `reset --hard` also)

**Comment by wolfeidau** [comment]
:+1: looking forward to this

**Comment by floatplane** [comment]
Yes please! This just bit us at FiftyThree today. I had to forcibly enqueue clean builds across our fleet to dig myself out.

**Comment by keithpitt** [comment]
@floatplane that sucks, sorry!! This will be a feature in the next release of the agent

**Comment by floatplane** [comment]
Thanks @keithpitt! BuildKite has been pretty dreamy otherwise! :smile:

**Comment by keithpitt** [comment]
<3 @floatplane

**Comment by toolmantim** [comment]
This is being discussed in #240
