### ISSUE TITLE
Feature Request: Agent startup hook.

### ISSUE THREAD

**Issue by donallfg** [buildkite/agent#1770]
**Is your feature request related to a problem? Please describe.**
I want to run some code on agent startup, and on agent shutdown to acquire/release storage resources. There is already an agent-shutdown hook that is executed that we can use for releasing resources, but we would like a startup hook to acquire them.

**Describe the solution you'd like**
https://buildkite.com/docs/agent/v3/hooks#agent-lifecycle-hooks - An additional agent lifecycle hook, `agent-startup` that gets triggered during the agent startup process.

**Describe alternatives you've considered**
Job lifecycle hooks aren't suitable because they run on every job. 
We oculd wrap the buildkite-agent start in our custom code, and launch from there, but we need to deploy code to do that, _and_ code to handle the shutdown in that case too
We could use infrastructure lifecycle hooks, e.g. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_lifecycle_hook which will likely be our fallback.

**Comment by moskyb** [comment]
🤔 i think i quite like this idea. we currently have [something similar](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/linux/conf/bin/bk-install-elastic-stack.sh#L209-L213) in the elastic-stack called (confusingly enough) the bootstrap script, which does something similar, but outside the bounds of the agent itself.

I think that given the existence of the `pre-exit` hook, it probably makes sense to have something symmetrical for agent startup. I'll raise this with the team internally :)

**Comment by donalmacc** [comment]
Hey. Original requester here (although on my personal account rather than my work account.) I took a stab at implementing this last night, and sent a PR https://github.com/buildkite/agent/pull/1778

**Comment by moskyb** [comment]
amazing, thanks so much @donalmacc! awesome work, i'll get reviewing :)
