### ISSUE TITLE
Query meta-data by build_id

### ISSUE THREAD

**Issue by simonbyrne** [buildkite/agent#1776]
**Is your feature request related to a problem? Please describe.**
It is not possible to query meta-data by build id (like [`buildkite-agent artifact download`](https://buildkite.com/docs/agent/v3/cli-artifact#downloading-artifacts)). Instead one has to use the `--job` option (which uses job id). 

**Describe the solution you'd like**
Add a `--build` keyword option to `meta-data get`, `meta-data exists` and `meta-data keys`.

**Describe alternatives you've considered**

**Additional context**
I [asked on the forum](https://forum.buildkite.community/t/query-meta-data-by-build-id/2289) and it was suggested I open an issue here. #1590 appears to implement this for `meta-data get`.

**Comment by tessereth** [comment]
Looks like this has been implemented in https://github.com/buildkite/agent/pull/2025 and released in v3.46.0.

Thanks for the suggestion!
