### ISSUE TITLE
Collect timestamp lines alongside log temp file

### ISSUE THREAD

**Issue by agates4** [buildkite/agent#1799]
**Is your feature request related to a problem? Please describe.**
When the `BUILDKITE_ENABLE_JOB_LOG_TMPFILE` environment variable is set to true, 
and `BUILDKITE_TIMESTAMP_LINES` is also set to true, 
then the generated tmp file **does not** include the timestamp lines that we'd expect it to have.

**Describe the solution you'd like**
I would like the log tmpfile to have the timestamp lines that we'd also see normally in the UI output.

**Describe alternatives you've considered**
Actually, using the `curl` api DOES include the timestamp lines. 

**Additional context**
This would be great so that we can upload and associate logs with our Datadog CI/CD pipelines!

**Comment by agates4** [comment]
BTW I think #758 is complete

**Comment by triarius** [comment]
Hey we agree this should be fixed. We'll attempt to get to it but can't guarantee a time-frame. In the mean time, any pull request would be welcome.

**Comment by triarius** [comment]
We are now tracking this internally in our backlog. As always, PRs are welcome.
