### ISSUE TITLE
Premature exit from Hook scripts

### ISSUE THREAD

**Issue by dekz** [buildkite/agent#180]
Due to [this exit](https://github.com/buildkite/agent/blob/master/templates/bootstrap.sh#L112), if the `command` hook fails, then no `post-command` hooks or `artifact` hooks are executed.

I usually have my clean up in `post-command` which means on a failed build, my containers might not get stopped and cleaned up.

It also makes it impossible to upload artifacts if a test has failed, i.e a screenshot of a browser integration test.

**Comment by toolmantim** [comment]
We had to revert how this works @dekz — but the artifact upload should work regardless of hook script exit statuses. We're gonna look into using an exit trap for artifact uploading…

**Comment by dekz** [comment]
Ah yeah I understand. 

We're going to want to trap a docker compose clean up as well as artifact upload.
