### ISSUE TITLE
agent v3.39.1 incorrectly parses special Windows environment variables when running bash hooks

### ISSUE THREAD

**Issue by staticfloat** [buildkite/agent#1804]
**Is your feature request related to a problem? Please describe.**
When running bash plugin hooks on windows, the new `buildkite-agent env` tool incorrectly parses some special environment variable names such as `=C`, which results in JSON entries such as the following:

```
.\buildkite-agent.exe env --pretty
{                                                                                                                                            
  "": "C:=C:\\Users\\Administrator",
...
}
```

This later surfaces with very strange "environment variable changed" messages in our build logs such as the following:
<img width="207" alt="image" src="https://user-images.githubusercontent.com/130920/197858350-254fa91a-105c-4678-9a74-7945a24aa28e.png">

Note that I am showing the `buildkite-agent env` invocation by setting `set -x` in our bash hook script, and to show that since we're using bash hooks, we don't use the typical powershell environment collector, which hasn't changed in v3.39.1.  To get these environment variables, you need to invoke `cmd.exe` at some point, [which will automatically create the variables](https://devblogs.microsoft.com/oldnewthing/20100506-00/?p=14133).  An easy reproducer is here, launched from within `bash` since it provides a convenient way of stripping out most variables:

```
$ env -i C:\\Windows\\System32\\cmd.exe /c ".\buildkite-agent.exe env --pretty"
{
  "": "C:=C:\\Users\\Administrator\\AppData\\Local\\Temp\\bk",
  "COMSPEC": "C:\\Windows\\System32\\cmd.exe",
  "MSYSTEM": "MINGW64",
  "PATH": "C:\\Program Files\\Git\\usr",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.JS;.WS;.MSC",
  "PROMPT": "$P$G",
  "SYSTEMROOT": "C:\\Windows",
  "WINDIR": "C:\\Windows"
}
```

I don't have much `go` experience, so I'm not certain what happens to the data after this point, but I can say that my updates to `PATH` do not get properly merged from this point on, despite the fact that there's no error in the build UI.

**Describe the solution you'd like**
[I would like the special variables that start with `=`](https://ss64.com/nt/syntax-variables.html#:~:text=Undocumented%20Dynamic%20variables%20(read%20only)) to be parsed correctly, or dropped.  These variables are not necessary for my use cases, but since they are _technically_ legal (you can't set them via `set` in the cmd terminal, but you _can_ set them via `SetEnvironmentVariable`, so a parent process could set these and then launch `buildkite-agent start`).  I personally am fine with them being dropped.

**Describe alternatives you've considered**
It is somewhat difficult to ensure that these variables are not set when I invoke `buildkite-agent`, so at the moment I am locking our infrastructure to using `buildkite-agent v3.39.0`.

**Comment by moskyb** [comment]
hi there @staticfloat! thanks for your report. this is something that we've noticed in the process of [using `buildkite-agent env` for bash and powershell hooks](https://github.com/buildkite/agent/pull/1791). I develop the agent on macOS, and imagine my surprise when i find out that windows has environment variables that start with `=` 🙃

rest assured that we'll come up with a solution here. dropping stuff that starts with an `=` is probably the easiest, but it's also possible that other people are relying on this, so i'll have a good think about this and ship a change when i get back to the PR linked above.
