### ISSUE TITLE
Create api command

### ISSUE THREAD

**Issue by tetienne** [buildkite/agent#1806]
**Is your feature request related to a problem? Please describe.**
I want to easily call the Buildkite API without dealing with headers, token, and any other curl relative parameters.

**Describe the solution you'd like**
Something similar to the Github CLI: https://cli.github.com/manual/gh_api

```
buildkite-agent api "/user"
buildkite-agent api "organizations/{org.slug}/pipelines/{pipeline.slug}/builds/{number}"

buildkite-agent api graphql ...
```

**Describe alternatives you've considered**
Use plain raw http request with curl.

**Additional context**
N/A

**Comment by moskyb** [comment]
hey, this is probably out of scope for the agent; the bk API is kind of its own thing, and i think we're keen to keep them separate for now. 

This command is probably suitable for the [bk cli](https://github.com/buildkite/cli) though! if you're interested in implementing something like this, the CLI would be the place to do it.
