### ISSUE TITLE
buildkite-agent should recursively clone plugins with submodules

### ISSUE THREAD

**Issue by staticfloat** [buildkite/agent#1807]
**Is your feature request related to a problem? Please describe.**
Plugins that use submodules (e.g. to share common functionality between plugins) should be recursively cloned if the agent would clone the main repository recursively.

**Describe the solution you'd like**
Proper application of `--recursive` to the clone flags of plugins.

**Describe alternatives you've considered**
Currently, I work around this by manually performing a `git submodule update --init` within the `post-checkout` hook of affected plugins.  Example: https://github.com/staticfloat/coppermind-buildkite-plugin/commit/527fd1f754527e598c401b7ddf4da6d21e3697c2

**Comment by moskyb** [comment]
hi @staticfloat, that seems like a good thing to have in plugins! we'll add a ticket for this to our backlog. In the meantime, PRs are very welcome :)
