### ISSUE TITLE
When uploading artifacts, output the uuid of the artifact 

### ISSUE THREAD

**Issue by mcgain** [buildkite/agent#183]
During a build, I want to upload an artifact and record the uuid so that in an external script I can download the artifact directly without having to page through all the artifacts via the api. 

This information is available via `--debug` but it's probably not a good idea to rely on debug output. 

If the uuid were to be output in `[INFO]` that would make this possible. 

@keithpitt

**Comment by keithpitt** [comment]
![image](https://cloud.githubusercontent.com/assets/25882/9978759/03971f2c-5efc-11e5-8533-b3033e947d74.png)

**Comment by keithpitt** [comment]
This new output will be available in the next beta! Thanks for the suggestion!
