### ISSUE TITLE
Security vulnerability in golang.org/x/crypto/ssh

### ISSUE THREAD

**Issue by mattdillon100** [buildkite/agent#1856]
Have just built `buildkite/agent:3.41.0-ubuntu-20.04` and ran a security scan using Snyk. There is a very high vulnerability [found here](https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXCRYPTOSSH-551923) affecting [golang.org/x/crypto/ssh](https://security.snyk.io/package/golang/golang.org%2Fx%2Fcrypto%2Fssh) package, versions <0.0.0-20200220183623-bac4c82f6975.

**Comment by moskyb** [comment]
hi there @mattdillon100! thanks for the report.

though the agent does use the `crypto/ssh` library, it never uses it to verify keys of any sort as laid out in the issue you've linked, so luckily the agent shouldn't be affected by this issue.

i've made a PR to update the dependency regardless though, always a good thing to keep things updated :)
