### ISSUE TITLE
New hook invocation method prevents exporting of env vars

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#188]
Commit 2f064eae4d940877ba04b0a65df4d621315a8568 (#180) changed how hooks are invoked, and it's no longer possible to have a hook that modifies the `$PATH`, such as:

```bash
#!/bin/sh

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```

**Comment by keithpitt** [comment]
I realised I did this half way through trekking. I was like: "doh, that change I made has borked ENV variables" :)
