### ISSUE TITLE
No BSD support?

### ISSUE THREAD

**Issue by essen** [buildkite/agent#190]
Docs here say Linux/BSD: https://buildkite.com/docs/agent/linux

Installer really is Linux/OSX. Produced executable is of course not working on FreeBSD (and others), since it's a Linux executable.

Is BSD really supported somehow or are the docs wrong?

**Comment by keithpitt** [comment]
Hey @essen - looks like the docs are wrong - sorry about that! I've just pushed out a beta FreeBSD release. I've done some initial testing, and it all seems to work well. Here are the installation instructions: https://gist.github.com/keithpitt/61acb5700f75b078f199

I'll get those added to our production docs when we release a stable! Sorry again about the confusion!

**Comment by essen** [comment]
Works, thanks.

**Comment by keithpitt** [comment]
Awesome, that's great @essen! :dancers:
