### ISSUE TITLE
Windows pull request issues

### ISSUE THREAD

**Issue by essen** [buildkite/agent#191]
On the same build, on Linux/FreeBSD I get:

```
mkdir -p "/home/essen/.buildkite-agent/builds/archlinux-1/ninenines/erlang-dot-mk"
$ cd "/home/essen/.buildkite-agent/builds/archlinux-1/ninenines/erlang-dot-mk"
$ git clean -fdq
$ git submodule foreach --recursive git clean -fdq
$ git fetch -q
$ git fetch origin "+refs/pull/383/head:"
From https://github.com/ninenines/erlang.mk
 * branch            refs/pull/383/head -> FETCH_HEAD
$ git checkout -qf "ea973ce662f8d4216c9610679c566b6b332918da"
$ git submodule sync --recursive
$ git submodule update --init --recursive
$ git submodule foreach --recursive git reset --hard
```

And on Windows (latest beta):

```
> MKDIR "builds\windows7-1\ninenines\erlang-dot-mk"
> CD /D "builds\windows7-1\ninenines\erlang-dot-mk"
> git clone https://github.com/ninenines/erlang.mk
Cloning into '.'...
POST git-upload-pack (552 bytes)
> git clean -fdq
> git fetch -q
> git reset --hard origin/pkg-reload.mk
fatal: ambiguous argument 'origin/pkg-reload.mk': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

The PR is from a third party user, and therefore not in the same repository, which is why it fails. If I run the command 'git fetch origin "+refs/pull/383/head:"' manually it runs fine, so I am not sure why the difference here.

**Comment by keithpitt** [comment]
Hey @essen, sorry that it's taken me a while to get around to this. I've just pushed a fix for this to master https://github.com/buildkite/agent/blob/master/templates/bootstrap.bat. All you should need to do is download that file, and replace the one you have locally, then it should all work! Let me know how you go!

**Comment by essen** [comment]
Works for me. Perfect, thanks!

While testing I noticed canceling running tasks on Windows is not possible; you probably already know, though.

**Comment by keithpitt** [comment]
Yeah, there are a few bugs around cancellation (I think the signal we send to child processes isn't the right one for Windows or something). I hope to iron out that bug in an upcoming release. Would you be able to create a GitHub issue for that one for me! Thanks @essen!
