### ISSUE TITLE
Uploaded build pipelines have wrong environment/config

### ISSUE THREAD

**Issue by tonyarnold** [buildkite/agent#192]
I'm currently uploading a build pipeline to an agent running on OS X installed via homebrew.

The initial (and only) step configured for the project (`buildkite-agent pipeline upload buildkite.yml`) gets the correct environment from `/usr/local/etc/buildkite-agent/hooks/environment`, but all the following steps show:

```
~~~ Running global environment hook
[90m$[0m ."/etc/buildkite-agent/hooks/environment"
```

Subsequently, and git checkouts fail (I assume because the environment is improperly configured).

**Comment by tonyarnold** [comment]
As I mentioned on Slack, it's also lost the correct paths. It's trying to use 

```mkdir -p "/var/lib/buildkite-agent/builds…```

When it should be:

```mkdir -p “/usr/local/var/lib/buildkite-agent/builds…```

**Comment by toolmantim** [comment]
Looks like it was something else after all!
