### ISSUE TITLE
run buildkite-flags-reset after sourcing hooks

### ISSUE THREAD

**Issue by lachie** [buildkite/agent#193]
Just noticed that hook scripts can change the expected bash flags for the whole bootstrap, now they're sourced.

Especially if folks follow the examples in the docs :) They all have `set -e`, which would make bootstrap not work as expected (because `set +e`).

Doco says:
```sh
#!/bin/bash

set -eu
```

fwiw I'm not having this problem, but thought I'd point it out

**Comment by toolmantim** [comment]
Ah, good catch! Thanks Lachie.

**Comment by keithpitt** [comment]
Ah, yes! Good one @lachie :dango:
