### ISSUE TITLE
Improve error log when configuration file is poorly formatted

### ISSUE THREAD

**Issue by YanivAssaf-at** [buildkite/agent#1936]
**Is your feature request related to a problem? Please describe.**
In `/etc/buildkite-agent/buildkite-agent.cfg` I accidentally set the token to:
```
token="{
    "ARN": "<arn>",
    "Name": "<name>",
    "VersionId": "<version>",
    "SecretString": "<secret>",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": 1234567890.123
}"
```

That's an obvious error on my end for not parsing the secret out and setting it.

The report is that the buildkite-agent failed with this log:
```
Jan 31 05:04:28 systemd[1]: Started Buildkite Agent.
Jan 31 05:04:28 buildkite-agent[7046]: Can't separate key from value
Jan 31 05:04:28 systemd[1]: buildkite-agent.service: Main process exited, code=exited, status=1/FAILURE
```

I believe it's trying to [load](https://github.com/buildkite/agent/blob/2dda4e362f4fabd986e21f54f9dba91306d94e13/cliconfig/file.go#L20-L59) the `buildkite-agent.cfg` and failing to parseLine: [code](https://github.com/buildkite/agent/blob/2dda4e362f4fabd986e21f54f9dba91306d94e13/cliconfig/file.go#L123).

Unfortunately the [Can't separate key from value](https://www.google.com/search?q=can%27t+separate+key+from+value&oq=Can%27t+separate+key+from+value) error message is a common docker failure which is misleading.

**Describe the solution you'd like**
I'd appreciate that the failure included 'Can't separate key from value while parsing buildkite-agent.cfg' or so.

**Describe alternatives you've considered**
N/A

**Comment by moskyb** [comment]
hey, this is a really good callout - we should probably be wrapping this (and other) errors with a little bit more context so that they're easier to debug. i'll make a change to fix this up.

thanks for your issue!

**Comment by moskyb** [comment]
hey @YanivAssaf-at! the pr above ☝️ should change that error message to:
```
Error loading config: loading config file: parsing config line: can't separate key from value in string "        \"AWSCURRENT\"", no valid separators (= or :) found
```
