### ISSUE TITLE
ansi-timestamps mismatch with short groups

### ISSUE THREAD

**Issue by toote** [buildkite/agent#1957]
When you run the following pipeline:

```
steps:
  - label: ":pipeline:"
    command: |-
      echo '--- starting with 3'
      echo sleep 14
      sleep 14
      echo sleep 2
      sleep 2
      date
      echo '--- continue with 2'
      date
      sleep 8
      sleep 3
      date
      echo '+++ continue expanded with 1'
      echo sleep 6
      sleep 6
      echo '--- finish with 3'
      echo sleep 7
      date
      sleep 7
      date
```

When running in an agent with `ansi-timestamps` enabled, the `continue with 2` group in the step's output will show the correct output for the dates 11 seconds apart before and after sleeping, but the timestamps will be the same. What's more, the expanded group with just one line in it will have the exact same timestamp until the last group heading:

```
_bk;t=1676441529752--- continue with 2

_bk;t=1676441529752Wed Feb 15 06:12:09 UTC 2023

_bk;t=1676441529753Wed Feb 15 06:12:20 UTC 2023

_bk;t=1676441540756+++ continue expanded with 1

_bk;t=1676441540756sleep 6

_bk;t=1676441540756--- finish with 3

_bk;t=1676441546757sleep 7

_bk;t=1676441546757Wed Feb 15 06:12:26 UTC 2023

_bk;t=1676441546758Wed Feb 15 06:12:33 UTC 2023

_bk;t=1676441553759
```

**Comment by toote** [comment]
The issue is solved in the `edge` version of the agent. From what I can see, it was fixed by PR #1940

**Comment by xxchan** [comment]
What is the `edge` version? 👀

**Comment by toote** [comment]
It is the docker image built on every push to master on this repository: `buildkite/agent:edge`
