### ISSUE TITLE
Yum Repo does not contain old releases

### ISSUE THREAD

**Issue by scottharrisaus** [buildkite/agent#199]
When a new package is added to your repo you are removing the old version.  This stops us locking to a specific rpm version until we can test newer versions in our test environment.

ie
 yum --showduplicates list buildkite-agent
Installed Packages
buildkite-agent.x86_64                                                                                    2.1.1-886                                                                                     @Buildkite
Available Packages
buildkite-agent.x86_64                                                                                    2.1.1-886                                                                                     Buildkite

I would expect the above command to show older packages the equivalent to this :  
yum --showduplicates list docker-compose
Loaded plugins: priorities, update-motd, upgrade-helper
971 packages excluded due to repository priority protections
Installed Packages
docker-compose.x86_64                                                                                    1.4.0-1.amzn1                                                                                     @hooroo
Available Packages
docker-compose.x86_64                                                                                    1.3.3-2.amzn1                                                                                     hooroo 
docker-compose.x86_64                                                                                    1.4.0-1.amzn1                                                                                     hooroo

**Comment by keithpitt** [comment]
This is fixed now and all previous releases are available! Thanks for submitting the bug report! :+1:
