### ISSUE TITLE
buildkite-agent 3.44.0 breaks on submodule mirrors with older git versions

### ISSUE THREAD

**Issue by adamsb6** [buildkite/agent#1999]
Version 3.44.0 includes https://github.com/buildkite/agent/pull/1959, which creates mirror directories for submodule repos. This PR guards against adding duplicate remotes by catching `git` exit code 3, which is what should be thrown according to the docs. Unfortunately, in earlier git versions, duplicates will result in exit code 128.

This includes at least version 2.25.1, the latest distributed with Ubuntu 20.04 LTS.

In our environment this meant that running more than one job for the same repo on an agent would break. We worked around by installing a later git version than was available in Ubuntu's repo.

See here for a repro case using the Ubuntu 20.04 Docker image: https://gist.github.com/adamsb6/29c3bf4cc81a6e59fff3955440d455c3

**Comment by moskyb** [comment]
hi there! we're looking into the various intricacies of submodule/git mirror interactions. we recently merged [a change](https://github.com/buildkite/agent/pull/1991) from @jonahbull which removes the exit code 3  handling entirely - does this change resolve your issue?

**Comment by adamsb6** [comment]
Thanks for the quick response! That PR should take care of this problem for us, if we're not adding remotes then we can't encounter the issue.
