### ISSUE TITLE
If a pull request is open from source_branch -> target_branch all builds for target_branch are associated with that PR

### ISSUE THREAD

**Issue by jmdeon** [buildkite/agent#2033]
This is causing our conditionals containing BUILDKITE_PULL_REQUEST_BASE_BRANCH to be inaccurate as we do not want certain steps to run when the BUILDKITE_PULL_REQUEST_BASE_BRANCH is target_branch. We are using github.

**Comment by moskyb** [comment]
hi @jmdeon! this is probably something to do with the buildkite backend, rather than the agent, so we recommend getting in touch with support@buildkite.com.
