### ISSUE TITLE
Parallel Artifact Uploads

### ISSUE THREAD

**Issue by tonyarnold** [buildkite/agent#204]
So I'm on a terrible (1Mbps upload) connection, and when I specify 8-10 artefacts to upload, the agent currently tries to upload them all in parallel. This saturates the upload bandwidth on my connection meaning all internet traffic comes to a standstill (and often the uploads just fail or time out). 

I'd love a way to say "only upload X files in parallel" — in my instance, I'd probably always set that 1.

Thanks guys!

**Comment by keithpitt** [comment]
This makes sense! I'll try and get it into the next release (probably 2.2)

**Comment by keithpitt** [comment]
As a workaround for now, anyone reading this issue can try this:

```bash
find . -name “*.zip" -type f -print0 | xargs -0 -I {} buildkite-agent artifact upload {}
```

So instead of using the built-in automatic artifact uploading, just manually upload files one by one (replace `"*.zip"` with the file pattern you want to upload)

**Comment by keithpitt** [comment]
We're just doing some spring cleaning, and since this issue has been around for a while - I might close it for now and revisit it later on. If anyone is running into issues with this regularly, please re-open so we can re-prioritise it!
