### ISSUE TITLE
Allow uploading artifacts to a Google Cloud Storage bucket

### ISSUE THREAD

**Issue by grosskur** [buildkite/agent#206]
I'm working on a PR to allow uploading artifacts to a Google Cloud Storage bucket. When the agent creates the artifact, it sends a POST to `https://agent.buildkite.com/v3/jobs/:job_id/artifacts` with `upload_destination` set to a path like `gcs://my-bucket/foo`.

The Buildkite API doesn't like this, and responds with a 400:

```json
{
  "message": "Unknown upload destination prefix `gcs://my-bucket/foo`"
}
```

Am I correct in my understanding that the Buildkite API currently only allows filesystem or `s3://` paths for `upload_destination`? If so, would it be possible to also allow `gcs://` paths? Thanks!

**Comment by keithpitt** [comment]
Hey @grosskur - we can absolutely support that for you in the Agent API! I just double checked the URI scheme, and https://cloud.google.com/storage/docs/gspythonlibrary?hl=en seems to suggest that `gs://` is what Google suggest?

**Comment by keithpitt** [comment]
This line specifically:

```
# URI scheme for Google Cloud Storage.
GOOGLE_STORAGE = 'gs'
```

**Comment by grosskur** [comment]
Yup, you're totally right---the proper URI scheme is indeed `gs://`. Thanks!

**Comment by keithpitt** [comment]
Cool cool, I'll add that new prefix shortly then let you know when it's up!

**Comment by keithpitt** [comment]
Also, sorry in advance about the agent artifact code, I wrote most of it about 2 years ago when I didn't really know how to Golang very well :P Any improvements you can make would be rad!

**Comment by keithpitt** [comment]
@grosskur ok, just pushed this to production, you should be able to use `gs://` now! Let us know if you need any help with the PR! :+1:

**Comment by grosskur** [comment]
Wow, thanks for doing this so fast! Just tested a `gs://` upload and it works great. :ok_hand:

For the download code, it looks like the trick of generating a signed URL and passing it to `download.go` won't work because Google Cloud Storage signing requires a special `.p12` certificate downloaded from the admin console. But I have another idea that might work---passing an `http.Client` in that transparently adds the `Authentication` header. Will let you know how it goes.

**Comment by keithpitt** [comment]
:+1:
