### ISSUE TITLE
Support multi-line secrets redaction 

### ISSUE THREAD

**Issue by mstifflin** [buildkite/agent#2062]
**Is your feature request related to a problem? Please describe.**
The redactor does not support redacting multiline secrets. We heavily use multiline secrets for various agent set up scripts, like distributing SSH keys for git access.

**Describe the solution you'd like**
https://sourcegraph.com/github.com/buildkite/agent/-/blob/redaction/redactor.go?L240
Update the redactor to support redacting multiline secrets. 

**Describe alternatives you've considered**
We could clean up the env vars immediately after using them (eg SSH_KEY >> ssh_file; unset SSH_KEY). 
However, our customers are distributed and empowered to freely create new CI workflows to suit their needs. It would be impossible to enforce this clean up in a maintainable way.

**Comment by moskyb** [comment]
hey @mstifflin! this is a really good callout - we should absolutely be redacting multiline secrets. this is a result of a limitation within our redactor - its input is line-buffered, so we have no way to redact multiline secrets at the moment without a significant rewrite.

we're going to put some thought into how we might make this happen though - as you say, it's an important thing to do, and the assumption that "all passwords are one line" in the code is obviously untrue. 

we'll back to you soon™, but we're not 100% sure of the timeline on that, unfortunately. please reach out either here or via support@buildkite.com if you have any more questions :)
