### ISSUE TITLE
Y U NO print out artefact upload progress?

### ISSUE THREAD

**Issue by orj** [buildkite/agent#208]
Large artefacts can take a while to upload (especially on slow connections).  Without any progress being printed it is very hard to tell if anything is happening (or how slow it is, or when to expect it to finish).

Progress updates for artefact uploads would be 
![giphy](https://cloud.githubusercontent.com/assets/34415/10806715/f1934c02-7e2b-11e5-81a7-3d8afe4fb52e.gif)

**Comment by lox** [comment]
Closing due to age, feel free to re-open if required.
