### ISSUE TITLE
Windows: Can't cancel tasks

### ISSUE THREAD

**Issue by essen** [buildkite/agent#213]
When clicking Cancel in the UI, the Windows agent reports:

```
[Process] Failed to send signal: terminated to PID: 6540 (syscall.Errno: not supported by windows)
```

And the build subsequently continues to run.

**Comment by essen** [comment]
How about a temporary solution using `TASKKILL /PID %d`?

**Comment by keithpitt** [comment]
Hrm..the beta version of the agent (v3.0) _should_ be able to cancel tasks in Windows now. Are you using that version by chance?

**Comment by essen** [comment]
I'm on v3.0 beta.12 and it does not cancel my tasks. I'll check if the error message changed since then.

**Comment by essen** [comment]
I don't suppose the Windows build logs its output anywhere? I can't see it in the documentation.

**Comment by keithpitt** [comment]
The build logs should be getting streamed to Buildkite - is that what you mean? Or the actual logs from the agent themselves. We don't log them anywhere, so they'll be coming from STDERR in the agent. How are you running the Agent on Windows?

**Comment by essen** [comment]
The logs from the agent. I'm running it as a Task Scheduler task. Apparently I need to redirect it myself to a file, so I'll do that and try again, see what error I get.

**Comment by essen** [comment]
Yep I still get the same error message as the OP.

**Comment by kamalaknn** [comment]
Still seeing this in 3.0-beta.23. Any updates?

**Comment by lox** [comment]
I believe this is related to https://github.com/buildkite/agent/issues/345. I'll see what I can do.

**Comment by lox** [comment]
This is fixed in 2-6-stable, still need to port it to master / v3.

**Comment by lox** [comment]
Fixed in https://github.com/buildkite/agent/commit/9b8a0b922f312ace8a2df1ef1cbae63e79ef494d
