### ISSUE TITLE
Would be nice if agent name was automatically set as metadata

### ISSUE THREAD

**Issue by floatplane** [buildkite/agent#214]
For quick things it can be useful to just target a build to a specific host. Having that ability without any explicit setting of metadata on our part would be nice!

**Comment by lox** [comment]
Agreed!

**Comment by keithpitt** [comment]
👋 We're just doing some spring cleaning, and we're going to close this issue for now. Sorry we haven't gotten around to implementing this yet. If anyone wants this re-prioritised, please re-open the issue!
