### ISSUE TITLE
BuildkiteAgentTimestampLines not working in 3.48.0

### ISSUE THREAD

**Issue by andrewlarry** [buildkite/agent#2149]
I'm testing version 3.48.0 of _buildkite-agent_ with [v5.21.0](https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v5.21.0) of _elastic-ci-stack-for-aws_. We've always used `BuildkiteAgentTimestampLines=true` in the template. After upgrading _buildkite-agent_, the timestamps have disappeared.  

I saw that the timestamp experiment graduated in the latest release. Is there additional configuration needed?

**Comment by triarius** [comment]
Hi @andrewlarry, thanks for raising this. We are going to release a version of the Elastic CI Stack that includes agent v3.48.0 and allows you to choose between [ansi-timestamps](https://buildkite.com/docs/agent/v3#experimental-features-ansi-timestamps) and [timestamp-lines](https://buildkite.com/docs/agent/v3/cli-start#timestamp-lines). This should mean they appear in your logs when we set `BuildkiteAgentTimestampLines=true`.

In the meantime, you can set `BuildkiteAgentTimestampLines=false` and use ansi-timestamps instead. There are a few benefits to them over timestamp-lines such as the ability to toggle them on and off and toggle between UTC and the local timezone when we display the logs on buildkite.com. ANSI timestamps are the way we want timestamping to work going forward, and timestamp-lines is something we are considering to deprecate.

Let us know if you have specific reasons to want the older style timestamp-lines.
