### ISSUE TITLE
Agent runs commands with non-standard PATH.

### ISSUE THREAD

**Issue by hearnden** [buildkite/agent#216]
I think this is a bug: https://github.com/buildkite/agent/blob/master/templates/bootstrap.sh#L142

Commands run by the agent should have an unsurprising PATH.  In an Ubuntu environment, probably one of:
 - `PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin` (the same PATH that the agent has)
 - `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games` (the PATH from `/etc/environment`)
 - `PATH=/sbin:/usr/sbin:/bin:/usr/bin` (the PATH of init)

However, since the agent bootstrap inserts `/usr/bin` at the front of `PATH`, the result is something non-standard, because it's promoting `/usr/bin` over `/usr/local/bin`.  That can give surprising results when there are binaries in `/usr/local/bin` that are intended to override those in `/usr/bin`.

Would it be possible to remove lines 141-142?

**Comment by 007lva** [comment]
+1
