### ISSUE TITLE
$BUILDKITE_JOB_ID not substituted in artifact upload destination

### ISSUE THREAD

**Issue by rayh** [buildkite/agent#222]
The docs here: https://buildkite.com/docs/agent/build-artifacts say that I should set the upload destination as follows:

```bash
export BUILDKITE_ARTIFACT_UPLOAD_DESTINATION=s3://name-of-your-s3-bucket/$BUILDKITE_JOB_ID
```

However, the $BUILDKITE_JOB_ID is not substituted, so I end up with urls with the literal string $BUILDKITE_JOB_ID in the path.  This results in all artifacts for all builds ending up in the same directory in S3.

**Comment by keithpitt** [comment]
Hey Ray! Where abouts are you doing that export?

**Comment by rayh** [comment]
In my ECS task definition for the container

**Comment by keithpitt** [comment]
Ah! You need to put it in an agent hook - usually the 'environment' one works pretty well.

**Comment by toolmantim** [comment]
This is related to buildkite/feedback#152 — going to close this one here
