### ISSUE TITLE
Exporting environment variables for next pipeline steps

### ISSUE THREAD

**Issue by mprimi** [buildkite/agent#2233]
The [documentation](https://buildkite.com/docs/agent/v3/cli-env#setting-a-jobs-environment-variables-description) for `buildkite-agent env set` says:

> Sets environment variables in the current job execution environment. Changes to the job environment variables only apply to subsequent phases of the job. This command cannot unset Buildkite read-only variables.

However if I try to `env set` I get: 
```
Could not create Job API client: BUILDKITE_AGENT_JOB_API_SOCKET empty or undefined
This command can only be used from hooks or plugins running under a job executor where the "job-api" experiment is enabled.
```

Is the doc wrong/misleading, or am I doing it wrong?

Full example and more details here: https://stackoverflow.com/questions/76733433/buildkite-set-environment-variables-for-downstream-steps

Using `buildkite-agent version 3.49.0, build 6166`

**Comment by DrJosh9000** [comment]
Hey @mprimi, 

I think the documentation could be clearer, and the situation is not particularly easy to explain, but I'll try.

`buildkite-agent env set` relies on the `job-api` experiment, i.e. you need to pass `--experiment job-api` to `buildkite-agent start`, or add `experiment=job-api` in your `buildkite-agent.conf`. 

But before you enable that, we should explain what it is for:

Using the local job API is one of two ways to pass environment variables _between phases of a job_. 
So it is possible to pass variables from, say, a pre-command [hook](https://buildkite.com/docs/agent/v3/hooks) to the command that way.

Looking at your StackOverflow question, and I'm guessing a bit here, but it looks like you're trying to use `FOO` within the _same_ phase, i.e. it looks like you want to interpolate `$FOO` into `.buildkite/pipeline.matrix.yml`. 

Unfortunately the local job API can't modify the environment of the script after it's started - that's a constraint imposed by the operating system.

But it doesn't need to do that. The command or commands run within a shell, typically Bash. If you want the env var to be usable by the subsequent commands in the same script (you want `$FOO` to be visible to `buildkite-agent pipeline upload ...`), then you should [`export`](https://www.man7.org/linux/man-pages/man1/export.1p.html) the variable instead:

```yaml
- command: |
    export FOO="$(buildkite-agent meta-data get foo_param)"
    echo "FOO = $FOO"
    buildkite-agent pipeline upload .buildkite/pipeline.matrix.yml
```

**Comment by mprimi** [comment]
Thank you @DrJosh9000 

Confirmed that the error is due to an attempt to use the jobs API which was disabled. Error goes away after enabling it.

Confirmed that using the job API does indeed not propagate the environment to the following steps (your comment makes sense about the two being in the same phase)

Confirmed `export` does the trick, with one caveat:

In the pipeline uploaded on the last line, I can say `echo "FOO = $FOO"` and it will work (my original ask)

However your code snippet requires one escape in order to print $FOO. i.e.:

```
    export FOO="$(buildkite-agent meta-data get foo_param)"
    echo "FOO = $$FOO" # Note the double dollar sign
```

 Thank you very much for your help
