### ISSUE TITLE
Update grandparent pipeline status when uploaded block step finishes in child pipeline

### ISSUE THREAD

**Issue by BillBrower-Shopify** [buildkite/agent#2237]
**Is your feature request related to a problem? Please describe.**
If you have a pipeline A that triggers a pipeline B; pipeline B conditionally uses `pipeline upload` from a bash script, that is run from a `run` step, to activate a `block` step; and the `block` step is triggered the status of pipeline B will show as passed when you manually click through the `block` step but pipeline A will show pipeline B as `running` indefinitely.

**Describe the solution you'd like**
Adding a final step to pipeline B that executes after the `block` step resolves this - presumably because it triggers a status update on pipeline A - but it would be nice not to have to have an empty final step. That is, it would be nice if `block` steps triggered status updates in grandparent parent pipelines.

**Describe alternatives you've considered**

**Additional context**

**Comment by moskyb** [comment]
hey @BillBrower-Shopify! this is more of a backend feature request, but our PM @ozdenyilmaz will reach out to you on slack to chat more about your request :)

because this isn't strictly speaking an agent thing, i'm going to close this issue.
