### ISSUE TITLE
Feature request: `buildkite-agent status` command

### ISSUE THREAD

**Issue by blueimp** [buildkite/agent#224]
Hi,

it would be great if the `buildkite-agent` CLI would provide a `status` command that returns an exit code corresponding to the connection to the agent.buildkite.com server:

``` sh
if buildkite-agent status; then
  echo 'Buildkite agent is up.'
else
  echo 'Buildkite agent is down.'
fi
```

It could also provide additional textual status output, though that would be only secondary priority.

The use case for me is to expose a health endpoint, which is related to this issue: https://github.com/buildkite/agent/issues/111#issuecomment-165489146

I think providing the status command gives the most flexibility and does not require the buildkite-agent itself to implement an HTTP server.

Thanks for considering this!

**Comment by lox** [comment]
Closing due to age. Feel free to re-open if still relevant.
