### ISSUE TITLE
Clean Checkout Fails on Windows

### ISSUE THREAD

**Issue by Preecington** [buildkite/agent#229]
The agent is unable to remove any git read-only files on Windows. This is due to a limitation in Golang's os.RemoveAll being unable to deal with read only files. See [here](https://github.com/golang/go/issues/9606) for discussion on fixing it in Golang & workarounds. The line in question in the agent is [here](https://github.com/buildkite/agent/blob/master/agent/bootstrap.go#L768).

Cryptically, the Windows Delete API reports ERROR_ACCESS_DENIED when deleting read-only files unless they are forced deleted, so Buildkite reports that it doesn't have the required permissions to do a clean up.

**Comment by keithpitt** [comment]
Ah right, thanks for pointing this out, and showing me the fix! I'll make sure it's included in the next version of the agent.

**Comment by ramijarrar** [comment]
Has this been fixed in the latest release?

**Comment by keithpitt** [comment]
Not yet @ramijarrar unfortunately, I'll try and get it into the next beta though (v2.2-beta.2)

**Comment by ramijarrar** [comment]
Is there an easy way to workaround this right now?

**Comment by keithpitt** [comment]
Hey @ramijarrar, there's a few things you could do in the mean time, depending on why you want to clean your directory. Do you want a clean directory for each build? Or do you want to be able to clean the directory from time to time via the UI? If it's the former, there may be something we can try, but for the latter, it may be easier to wait until the beta release.

**Comment by ramijarrar** [comment]
Yeah, I ended up just adding a command to wipe the directory before each build. Thanks for the help.

**Comment by lox** [comment]
This should be fixed in recent golang releases, so the recent v3 betas.
