### ISSUE TITLE
Feature Request: auto-expand groups with errors

### ISSUE THREAD

**Issue by tarragon** [buildkite/agent#23]
It would be great if there was a way to only expand, or auto-expand, the sections of the build output where errors have occurred.

As far as implementing it goes, perhaps another special string can be checked for by buildbox for sections of interest, similar to the way buildbox currently looks for ---, e.g. if the build script hits an error it could trap and output something *** or similar, and buildbox would treat that as an erroring section.

**Comment by keithpitt** [comment]
Almost a year later, I finally got around to doing this :D:D

![image](https://cloud.githubusercontent.com/assets/25882/7775391/0a077a2a-00b3-11e5-9d5b-e1d2ad139a23.png)

`echo "^^^ +++"` will open the previously defined group! :dancer:
