### ISSUE TITLE
Setting BUILDKITE_ARTIFACT_UPLOAD_DESTINATION in environment hook not working

### ISSUE THREAD

**Issue by rayh** [buildkite/agent#230]
In the buildkite console, I can see that the environment variable is being picked up and set:

```bash
Running global environment hook    0.4s
# Executing "/buildkite/hooks/environment"
Applying environment changes    0s
# BUILDKITE_ARTIFACT_UPLOAD_DESTINATION=s3://intelematics-sydney-buildkite-artifacts/171f9634-26f8-4bdc-b7b8-4feb08301eee
# BUILDKITE_S3_DEFAULT_REGION=ap-southeast-2
```

But when artefacts are uploaded, they are sent to the default build kite bucket.  @keithpitt has some context here

**Comment by keithpitt** [comment]
Cool, this should be fixed now. The fix will be available in the next version of the ECS docker images, which I'm told should be out soon! Thanks for letting me know!
