### ISSUE TITLE
Support repository-less builds

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#233]
In some you just want to run a pipeline that executes a script on a machine… there's actually no repository attached.

One way to support this, without any changes to the web UI, would be to allow people to `export BUILDKITE_REPO=""` in a pre-checkout hook. In this case the build would just `mkdir -p $BUILDKITE_PROJECT_SLUG; cd $BUILDKITE_PROJECT_SLUG`, so the build directory is the same as the checked out ones (`builds/my-org/my-builds`)

**Comment by toolmantim** [comment]
To do this now you can create an agent with a customized `checkout` hook that simply has:

```
#!/bin/bash

echo "--- Skipping code checkout"
```

and with meta-data `no-checkout=true`. Then you can target this in a pipeline, and it'll ignore whatever was set as the repository URL (which could just be `"skip"`)

**Comment by solemnwarning** [comment]
I would also find this useful.

I have a pipeline that has a build step which uploads the build as an artefact for multiple test steps (different environments) to run. Having to check out doesn't break anything, but it is unnecessary and does mean poking another hole in the sandbox so the test host(s) can reach Github.

**Comment by keithpitt** [comment]
Just slated this for a 4.0 release, gotta have it!

**Comment by dch** [comment]
As an example, I have an ansible task that runs in a *different* repo (the ansible one) after each successful commit/tests on the active projects. 

Currently I do a little hack:

```
  - command: |
      cd /home/buildkite/src/ansible
      buildkite-agent artifact download "_build/w*.txz" pkg/
      make app
```

which works, but unfortunately triggers another source code checkout.  Having  metadata `no-checkout=true` set at the agent level stops this working, as then the ansible repo never gets updated.

Ideally repository-less pipeline steps could co-exist in the same build agent config as git-triggered builds, which @toolmantim 's hack would block, I think. Is there an alternative arrangement?

**Comment by lox** [comment]
Implemented in https://github.com/buildkite/agent/pull/909.
