### ISSUE TITLE
Default to the init.d process manager for Amazon Linux AMI's

### ISSUE THREAD

**Issue by keithpitt** [buildkite/agent#234]
The current version of `upstart` that's installed on Amazon Linux AMI's is `0.6.5` - which is super old and incompatible with our current upstart script. We need to change our installer to default to the `init.d` version of the process manager.

As a workaround for now, after you've installed the agent run these commands:

```
sudo rm /etc/init/buildkite-agent.conf
sudo cp /usr/share/buildkite-agent/lsb/buildkite-agent.sh /etc/init.d/buildkite-agent
sudo /etc/init.d/buildkite-agent start
```

This will remove the installed `upstart` script, and replace it with an `init.d` version. We'll change this to the default in the next version of the agent.

**Comment by lox** [comment]
Is this still a thing?

**Comment by lox** [comment]
Also, as a reminder this issue is referenced from https://buildkite.com/docs/agent/redhat

**Comment by keithpitt** [comment]
Yeah, I think this is still an issue.

**Comment by keithpitt** [comment]
We need to special case it here: https://github.com/buildkite/agent/blob/master/packaging/linux/scripts/after-install-and-upgrade.sh#L50

**Comment by sj26** [comment]
I've pushed a fix for this in agent [version 2.1.5 to GitHub](https://github.com/buildkite/agent/releases/v2.1.5) and to the unstable package channels. Will give it a test and, if all good, promote it to stable.

**Comment by toolmantim** [comment]
Cool, this will be out in the next release

**Comment by jnewbigin** [comment]
This is also an issue for RHEL6/CentOS-6.
I would recommend running start --version and checking the upstart version as appropriate
You must also register the init script with chkconfig --add
```
# cat /etc/system-release
CentOS release 6.7 (Final)
# /sbin/start --version
start (upstart 0.6.5)
Copyright (C) 2010 Canonical Ltd.

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I am happy to supply or test a patch.

**Comment by keithpitt** [comment]
@jnewbigin a patch would be great! We don't have any testing processes around this stuff at the moment, so it's currently "lets spin up some boxes and try the latest version". We hope to automate that process in the future though. So if you submit a patch, we'll spin up a RHEL6/CentOS-6 machine and give it a run!

**Comment by jnewbigin** [comment]
https://github.com/buildkite/agent/pull/290
