### ISSUE TITLE
Bootstrap script doesn't fetch correctly with Git < v1.9

### ISSUE THREAD

**Issue by ab9** [buildkite/agent#249]
> TL;DR: In version 2.1.5, the bootstrap script runs ```git fetch origin --tags``` to update all heads and tags. In some older versions of Git, that command will only update the tags, which can cause the subsequent checkout to fail.

We upgraded to version 2.1.5 on Ubuntu 12.04 LTS and the new bootstrap script failed. The [problematic command](https://github.com/buildkite/agent/blob/v2.1.5/templates/bootstrap.sh#L254) is ```git fetch origin --tags```. It seems to have been introduced in #243.

The relevant comment in the bootstrap script reads: "we fall back to fetching all heads and tags, hoping that the commit is included." [With Git 1.9 and later, ```git fetch origin --tags``` will indeed fetch all heads and tags](https://github.com/git/git/blob/d7aced95cd681b761468635f8d2a8b82d7ed26fd/Documentation/RelNotes/1.9.txt#L18-L20), assuming the remote is configured in the usual way. With Ubuntu 12.04 LTS's version of Git (v1.7.9.5), the command will run cleanly – that is, it will give a successful exit code and won't print error messages – but it will fetch only the tags. As a result, the ```git checkout``` command that follows it may fail and complain about "bad object".

We worked around this issue by adding a custom checkout hook that uses the command ```git fetch origin --tags +refs/heads/*:refs/remotes/origin/*```.

**Comment by ab9** [comment]
#250 may have fixed this.

**Comment by toolmantim** [comment]
Yep, you're right, this is fixed in #250. Thanks for the report!
