### ISSUE TITLE
Golang SDK support for Agent Locks

### ISSUE THREAD

**Issue by jmandel1027** [buildkite/agent#2518]
**Is your feature request related to a problem? Please describe.**

We're working on a feature at Square that requires Agent Locks within our Polyglot Golang hooks, but we currently don't have an API for locks yet.

**Describe the solution you'd like**

It would be amazing if we could get a Golang API for the agent locks in one of the buildkite go SDKs. This would be much more ergonomic than calling `os/exec` to run the lock commands. The os calls are workable but very crusty. It'd be much better to have an API baked into the SDK for opening and closing agent locks.

**Comment by DrJosh9000** [comment]
Hi @jmandel1027, do you mean something like https://pkg.go.dev/github.com/buildkite/agent/v3/lock ?

**Comment by jmandel1027** [comment]
@DrJosh9000  Ahh finally got around to taking a closer look at this link. That is exactly what I was looking for, thanks! 🚀
