### ISSUE TITLE
Ability to upload and download artefacts from different pipelines

### ISSUE THREAD

**Issue by ChildishhAlbino** [buildkite/agent#2527]
**Is your feature request related to a problem? Please describe.**
When two uncoupled but related pipelines - i.e build and deploy - are attempting to share artefacts but not enough information can easily be shared to determine where to download them from.

**Describe the solution you'd like**

The ability to specify that I am downloading artefacts from a different pipeline. Something like `--pipeline <PIPELINE_ID>` as an option to say _find me all artefacts that match this glob for this specific pipeline_

Additionally it would be even better to have the ability to filter the pipeline builds by commit like `--build-vcs-ref <GIT_HASH>` so that we only get builds that match the commit/tag we're deploying from.

**Describe alternatives you've considered**

1. Tried uploading to a shared S3 bucket that both pipelines and their agents have access to. This doesn't work as it can't find the artefacts, I assume because they aren't from the same pipeline. No options I have been able to provide resolve this issue. We aren't really in a position to be providing the specific `--build` flag because the deploy job could be triggered for many different versions at the same time. i.e. production might be deploying  `v1.0` and one of our development environments might be deploying by the git hash `2437f62`
3. Joining the pipelines - this is currently how I've solved this issue but it causes pain points if the pipeline contains a docker build step - as now the image tag already exists.

**Comment by triarius** [comment]
Also, many customers use trigger jobs to create a build on a second pipeline that deploys the built artifacts. If that's the case for you, you can use something like
```
buildkite-agent artifact download "*.jpg" images/ --build $BUILDKITE_TRIGGERED_FROM_BUILD_ID
```
to bypass the step of finding the build id. See [here](https://buildkite.com/docs/pipelines/artifacts#download-artifacts-with-the-buildkite-agent-example-download-an-artifact-from-a-triggering-build) for more context.

**Comment by ChildishhAlbino** [comment]
Thanks for responding. @triarius I will liaise with my team to see if the first option is viable.

The second option is not viable as we do not want to couple the build and deploy jobs.
