### ISSUE TITLE
Bug: Windows install script missing default value for $version

### ISSUE THREAD

**Issue by jhpierce** [buildkite/agent#2557]
---
 about: There is a broken url in the windows install script
 title: Missing default value for $version in buildkite-agent url in `install.ps1`
 ---

#1805 introduced a breaking change in a url. Instead of:

```"https://buildkite.com/agent/releases/latest?platform=windows&arch=$arch"```

the script uses

```"https://buildkite.com/agent/releases/$version?platform=windows&arch=$arch"```

if you don't provide a $url parameter. That's an issue for current users who haven't defined a $version.

 **Steps To Reproduce**
 1. Run the windows installer script without a $url parameter
 2. See error

 **Expected behavior**
Installer script should pull the latest agent release

 **Actual behaviour**
Installer script fails

cc @DrJosh9000 :) Thanks!

**Comment by sean-simmons-progress** [comment]
Following
