### ISSUE TITLE
Buildkite build script is broken

### ISSUE THREAD

**Issue by amir-khatibzadeh** [buildkite/agent#2558]
Hi,

Since December 12, the build script has been broken because of the missing $version parameter.
by default, it should be "latest" but missed on the script as an input parameter or a value from an environment variable.

https://github.com/buildkite/agent/blame/89e8ed27ec8a1a2d041ac0b1d0928e41b86e4169/install.ps1#L39

**Comment by sean-simmons-progress** [comment]
Following

**Comment by amir-khatibzadeh** [comment]
created a PR for this ticket
https://github.com/buildkite/agent/pull/2559
