### ISSUE TITLE
Show how many jobs ahead of job in queue

### ISSUE THREAD

**Issue by IanButterworth** [buildkite/agent#2581]
**Is your feature request related to a problem? Please describe.**
Waiting for a job to start without any idea of position in the queue is quite frustrating.

**Describe the solution you'd like**
It would be great if on a pending job banner instead of just
```
Waiting for agent 6h 5m
```
It could say something like
```
Waiting for agent 6h 5m (4 jobs ahead, 6 active workers)
```

**Describe alternatives you've considered**
From the context of agents, a browsable queue of jobs that an agent can pick up.

**Additional context**

**Comment by moskyb** [comment]
hey there! this is a great idea - it'd be handy for me too.

we're working on some stuff kinda sorta similar to this at the moment - it's looking like it'll be a link to queue metrics from the `Waiting for agent` text, but not quite as fancy as you've described here.

this isn't really a feature that we can add agent-side, so i'd recommend raising this as feedback with your CSM - i'll close this issue for now, but happy to continue to chat here :)
