### ISSUE TITLE
Control the order of annotations

### ISSUE THREAD

**Issue by kormide** [buildkite/agent#2600]
**Is your feature request related to a problem? Please describe.**

Annotations are a great way to display information about an ongoing build. The information rendered can have different levels of importance ranging from minor suggestions to calls to action which can drastically improve developer productivity, e.g., "this test is failing, here are the logs so you can fix it before waiting 1hr for the build to finish". However, annotations are rendered in the order they are created with new ones appearing at the top. This can cause important annotations to get buried and require lots of scrolling to see.

**Describe the solution you'd like**

The ability to control the order of created annotations.

**Describe alternatives you've considered**

An additional idea is to group annotations by their job affinity.

**Comment by triarius** [comment]
Hi @kormide we've raised this as a feature request with our Product Management Team. I'm going to close the issue here, as it's not directly related to the agent, but I've let them know to email you when there's progress.

**Comment by LiamPClancy** [comment]
Just wanted to add a note here incase anyone come across this thread when searching for similar functionality. 
It is now possible to set the order of annotations using the priority option detailed in the [Buildkite Documentation](https://buildkite.com/docs/agent/v3/cli-annotate#priority)

**Comment by kormide** [comment]
Awesome! Thanks for following up.
