### ISSUE TITLE
Support matrix values in step keys and concurrency groups

### ISSUE THREAD

**Issue by apgrucza** [buildkite/agent#2633]
**Is your feature request related to a problem? Please describe.**
A typical pipeline at my organisation deploys infrastructure to multiple AWS regions simultaneously with Terraform, via multiple similar plan and deploy steps. We use a unique `concurrency_group` for each region, and a unique `key` on each plan step. We want to use the build matrix feature as it would vastly simplify our pipeline definitions, but we're unable to due to the lack of support for matrix values in these attributes.

**Describe the solution you'd like**
The ability to use matrix values (e.g. `{{matrix}}`) in the `key` and `concurrency_group` attributes.

**Comment by moskyb** [comment]
g'day @apgrucza! this is a reasonable request, but it's not directly related to the agent binary - matrix parsing (largely) happens in the buildkite backend. the suggested avenue for feature requests of this type is probably through support@buildkite.com, or through enterprise support, as it'll be easier for our product folks to get in touch with you with questions/updates. they should be able to dig deeper into your use case (and your yaml) to see how we could make things better.
