### ISSUE TITLE
Newer versions don't respect `BUILDKITE_CANCEL_GRACE_PERIOD`

### ISSUE THREAD

**Issue by etodd** [buildkite/agent#2748]
Somewhere in the last few releases, the Buildkite agent stopped respecting `BUILDKITE_CANCEL_GRACE_PERIOD`, which we currently set to `600`. Instead it kills the job after the default 10 second grace period.

I rolled back our agent to 3.65 and that version seems to respect it properly.

**Comment by tessereth** [comment]
Thanks for reporting this! It looks like this changed in https://github.com/buildkite/agent/pull/2654 in v3.66 when we extended signal grace period handling to all phases of a build. I'll look into the best way to make this more intuitive, but in the mean time, you can set `BUILDKITE_SIGNAL_GRACE_PERIOD_SECONDS` to slightly less than `BUILDKITE_CANCEL_GRACE_PERIOD` and you should get the behaviour you're after.

**Comment by tessereth** [comment]
This should be fixed in the next agent release (v3.74)
