### ISSUE TITLE
Downloading multiple artifacts with the same file name corrupts them.

### ISSUE THREAD

**Issue by colincoghill** [buildkite/agent#2774]
We've recently diagnosed a situation where artifacts appeared to be getting corrupted and discovered it's when multiple are created with the same name in different steps, then downloaded to a final step.

eg. 

Step 1:    Uploads artifacts:
 *   package_amd64.deb
 *   package_all.deb

Step 2:    Uploads artifacts:
 *   package_arm64.deb
 *   package_all.deb

Step 3:   Downloads all artifacts from step 1 and 2: 
 *   package_amd64.deb
 *   package_arm64.deb
 *   package_all.deb    <-  will be corrupted combination of the two.

This took a while to diagnose because the corrupted file is the correct size and because it's a mixing of two similar files (in our case they were supposedly identical but because some file date stamps were different, the compressed content was unusable).

The buildkite agent code that downloads artifacts from S3 appears to grab a list of all artifacts and downloads them in parallel, it looks likely that this is where the problem happens.

I realise creating multiple artifacts with the same name is not recommended, but it's a very easy mistake to make.

Is it possible to either fix this behaviour or at least make it clearer in the documentation that this is an easy to make mistake.

**Comment by moskyb** [comment]
hey @colincoghill! this is definitely not the intended behaviour - i suspect that the two artifacts are being erroneously downloaded into the same place and splinching with each other. i'll raise an escalation internally and try to get this fixed for you.
