### ISSUE TITLE
Error when bash posix mode is enabled

### ISSUE THREAD

**Issue by dkubb** [buildkite/agent#280]
If posix mode is turned on using `set -o posix` the `bootstrap.sh` script returns errors:

```
/buildkite/bootstrap.sh: line 29: `buildkite-flags-reset': not a valid identifier
```

A dash is not a valid character in an identifier. There are other functions in the script that have invalid identifiers too.

**Comment by keithpitt** [comment]
Ah boo, thanks for pointing that out @dkubb! So the `bootstrap.sh` file is currently in maintenance mode. We've actually rewritten it in Golang recently as you can see here: https://github.com/buildkite/agent/blob/master/agent/bootstrap.go

In the process of the rewrite, we were able to fix a ton of bugs and add a ton of new features that were previously very difficult/impossible to write in Bash. The rewritten bootstrap is available in the latest beta of the agent.

If you'd like to give that a try, after installing the agent, change the `bootstrap-script` config option to just `buildkite-agent bootstrap` and everything should just work! We've still got a few quirks to work out with it, but we've been using it for the last few months and it's been working pretty well.

Out of interest, how is posix mode getting turned on in the bootstrap? Is it something you're manually adding?

**Comment by lox** [comment]
Closing this as it's quite old now. Let us know if it's still an issue.
