### ISSUE TITLE
Branches filter doesn't seem to work on 'manual' steps

### ISSUE THREAD

**Issue by d11wtq** [buildkite/agent#286]
We have this in our pipeline.yml, so we only run steps after this one if a developers unblocks the build.

``` yaml
  - type: manual
    branches: "!master"
```

However, this seem to still show up on our master branch and requires us to manually continue the build.

Are we trying to do something unsupported? :)

**Comment by keithpitt** [comment]
Ah! Yeah, the `branches` check doesn't currently apply to `wait` or `manual` step types - but it's something we definitely want to allow in the future!

In the mean time, you could write a simple script that read your existing `.buildkite/pipeline.yml` file, read each step, check the branches, and the STDOUT a new yml with the steps removed. You'd then change your pipeline upload step to be:

`ruby .buildkite/parse-pipeline.rb | buildkite-agent pipeline upload`

**Comment by keithpitt** [comment]
Happy to help you write the script on Slack if you get stuck :) I'll close this for now, but we'll announce when we do add support for that (we've got some other stuff we want to add as well)

**Comment by d11wtq** [comment]
:+1: - implemented and working, thanks for the suggestion :octocat:

**Comment by keithpitt** [comment]
Awesome! Glad you got it all working :) One day we'll just support it out of the box!
