### ISSUE TITLE
Specifying an absolute path to a script breaks

### ISSUE THREAD

**Issue by keithpitt** [buildkite/agent#287]
When you specify an absolute path to a script on the filesystem you need to run, it currently breaks since we append an additional `/` to the command (`./"path"`).

When we make this change, we should introduce a new flag "--only-repo-scripts" - which will disallow running scripts that don't exist in the repo.

**Comment by kcroaker** [comment]
Prepending the script that you want to run with `sh ` 
So that:
`    command: "/absolute/path/to/script.sh"`
Becomes:
`    command: "sh /absolute/path/to/script.sh"`
