### ISSUE TITLE
buildkite-agent meta-data set crash

### ISSUE THREAD

**Issue by daveoxley** [buildkite/agent#288]
Since about 1:30pm 14/4 buildkite-agent has been crashing at the end of our builds while doing `buildkite-agent meta-data set`.

https://buildkite.com/intelematics/android-module-ubi/builds/199#ca493f25-c730-4fc5-8043-976746821594

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x7c2e6c]
 
runtime stack:
runtime.throw(0xaa5e40, 0x2a)
	/usr/local/go/src/runtime/panic.go:530 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
 
goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x7c2db0, 0xc82004bdf8, 0xc800000000)
	/usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc82004bda8 sp=0xc82004bd78
github.com/ErikDubbelboer/gspt._Cfunc_spt_init2(0x5, 0x130f740)
	github.com/ErikDubbelboer/gspt/_obj/_cgo_gotypes.go:89 +0x3a fp=0xc82004bdf8 sp=0xc82004bda8
github.com/ErikDubbelboer/gspt.init.1()
	/go/src/github.com/buildkite/agent/vendor/src/github.com/ErikDubbelboer/gspt/gspt.go:53 +0x427 fp=0xc82004bf18 sp=0xc82004bdf8
github.com/ErikDubbelboer/gspt.init()
	github.com/ErikDubbelboer/gspt/_obj/_cgo_import.go:1 +0x4a fp=0xc82004bf20 sp=0xc82004bf18
github.com/buildkite/agent/proctitle.init()
	/go/src/github.com/buildkite/agent/proctitle/proctitle_linux_amd64.go:21 +0x40 fp=0xc82004bf28 sp=0xc82004bf20
github.com/buildkite/agent/agent.init()
	/go/src/github.com/buildkite/agent/agent/version.go:22 +0x7e fp=0xc82004bf48 sp=0xc82004bf28
main.init()
	/go/src/github.com/buildkite/agent/main.go:101 +0x45 fp=0xc82004bf50 sp=0xc82004bf48
runtime.main()
	/usr/local/go/src/runtime/proc.go:177 +0x27f fp=0xc82004bfa0 sp=0xc82004bf50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82004bfa8 sp=0xc82004bfa0
 
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
 
goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x7c2e6c]
 
runtime stack:
runtime.throw(0xaa5e40, 0x2a)
	/usr/local/go/src/runtime/panic.go:530 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
 
goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x7c2db0, 0xc82004bdf8, 0xc800000000)
	/usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc82004bda8 sp=0xc82004bd78
github.com/ErikDubbelboer/gspt._Cfunc_spt_init2(0x5, 0x25b2740)
	github.com/ErikDubbelboer/gspt/_obj/_cgo_gotypes.go:89 +0x3a fp=0xc82004bdf8 sp=0xc82004bda8
github.com/ErikDubbelboer/gspt.init.1()
	/go/src/github.com/buildkite/agent/vendor/src/github.com/ErikDubbelboer/gspt/gspt.go:53 +0x427 fp=0xc82004bf18 sp=0xc82004bdf8
github.com/ErikDubbelboer/gspt.init()
	github.com/ErikDubbelboer/gspt/_obj/_cgo_import.go:1 +0x4a fp=0xc82004bf20 sp=0xc82004bf18
github.com/buildkite/agent/proctitle.init()
	/go/src/github.com/buildkite/agent/proctitle/proctitle_linux_amd64.go:21 +0x40 fp=0xc82004bf28 sp=0xc82004bf20
github.com/buildkite/agent/agent.init()
	/go/src/github.com/buildkite/agent/agent/version.go:22 +0x7e fp=0xc82004bf48 sp=0xc82004bf28
main.init()
	/go/src/github.com/buildkite/agent/main.go:101 +0x45 fp=0xc82004bf50 sp=0xc82004bf48
runtime.main()
	/usr/local/go/src/runtime/proc.go:177 +0x27f fp=0xc82004bfa0 sp=0xc82004bf50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82004bfa8 sp=0xc82004bfa0
 
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
 
goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by sj26** [comment]
Sorry this has failed your build. :-(

It looks like we got a segmentation fault within the code updating the process title. 

How long is your metadata? setproctitle manipulates the argv array. Perhaps if you're passing large metadata it has a very large argv and it's bigger than the c code can handle?

**Comment by daveoxley** [comment]
The metadata being passed in is sometimes quite large and I wondered if that might be the issue, but it was happening on all builds, even builds where I expected the metadata to be fairly short.

However it doesn't appear to be happening anymore. It was happening with every build for the day but hasn't happened since. I was wondering if anything was changed server side? Anyway, I think this issue can probably be closed now.

**Comment by sj26** [comment]
Weird! I don't think we changed anything related server-side. Maybe just a perfect storm of memory issues.

I'll close it for now, let us know if it re-occurs. :-)

**Comment by daveoxley** [comment]
Below is example metadata we are trying to set in the JSON env variable using the command: buildkite-agent meta-data set "buildMetadata_v2" "$JSON"

`
    {"module":[{"artifact":[],"dependency":[{"target":"com.intelematics.android.lib:IAWebServices-debug:1.0.1-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:HereToThere-debug:1.1.20-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:TripLog-debug:1.1.25-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CarHealth-debug:1.1.13-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:IntelematicsUtils-debug:1.1.10-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:ERS-prodDebug:0.5.22-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CMActivation-debug:1.0.4-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:cardframework-debug:1.0.56-SNAPSHOT","transitive":false},{"target":"com.google.ui:SlidingTab-debug:1.2.14-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:HubSpokeWidget-debug:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IntelematicsUtils-debug:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-debug:1.0.2-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:Cache-debug:1.1.6-SNAPSHOT","transitive":true},{"target":"com.google.ui:SlidingTab-debug:1.2.13-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:ViewpagerWidget-debug:1.1.5-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:cardframework-debug:1.0.56-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-drivers-debug:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-commands-debug:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-manager-debug:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-release:1.0.1-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:HereToThere-release:1.1.20-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:TripLog-release:1.1.25-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CarHealth-release:1.1.13-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:IntelematicsUtils-release:1.1.10-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:ERS-prodRelease:0.5.22-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CMActivation-release:1.0.4-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:cardframework-release:1.0.56-SNAPSHOT","transitive":false},{"target":"com.google.ui:SlidingTab-release:1.2.14-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:HubSpokeWidget-release:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IntelematicsUtils-release:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-release:1.0.2-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:Cache-release:1.1.6-SNAPSHOT","transitive":true},{"target":"com.google.ui:SlidingTab-release:1.2.13-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:ViewpagerWidget-release:1.1.5-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:cardframework-release:1.0.56-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-drivers-release:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-commands-release:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-manager-release:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-debug:1.0.1-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:HereToThere-debug:1.1.20-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:TripLog-debug:1.1.25-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CarHealth-debug:1.1.13-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:IntelematicsUtils-debug:1.1.10-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:ERS-stageDebug:0.5.22-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CMActivation-debug:1.0.4-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:cardframework-debug:1.0.56-SNAPSHOT","transitive":false},{"target":"com.google.ui:SlidingTab-debug:1.2.14-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:HubSpokeWidget-debug:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IntelematicsUtils-debug:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-debug:1.0.2-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:Cache-debug:1.1.6-SNAPSHOT","transitive":true},{"target":"com.google.ui:SlidingTab-debug:1.2.13-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:ViewpagerWidget-debug:1.1.5-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:cardframework-debug:1.0.56-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-drivers-debug:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-commands-debug:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-manager-debug:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-release:1.0.1-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:HereToThere-release:1.1.20-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:TripLog-release:1.1.25-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CarHealth-release:1.1.13-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:IntelematicsUtils-release:1.1.10-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:ERS-stageRelease:0.5.22-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CMActivation-release:1.0.4-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:cardframework-release:1.0.56-SNAPSHOT","transitive":false},{"target":"com.google.ui:SlidingTab-release:1.2.14-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:HubSpokeWidget-release:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IntelematicsUtils-release:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-release:1.0.2-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:Cache-release:1.1.6-SNAPSHOT","transitive":true},{"target":"com.google.ui:SlidingTab-release:1.2.13-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:ViewpagerWidget-release:1.1.5-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:cardframework-release:1.0.56-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-drivers-release:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-commands-release:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-manager-release:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-debug:1.0.1-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:HereToThere-debug:1.1.20-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:TripLog-debug:1.1.25-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CarHealth-debug:1.1.13-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:IntelematicsUtils-debug:1.1.10-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:ERS-stageDebug:0.5.22-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CMActivation-debug:1.0.4-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:cardframework-debug:1.0.56-SNAPSHOT","transitive":false},{"target":"com.google.ui:SlidingTab-debug:1.2.14-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:HubSpokeWidget-debug:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IntelematicsUtils-debug:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-debug:1.0.2-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:Cache-debug:1.1.6-SNAPSHOT","transitive":true},{"target":"com.google.ui:SlidingTab-debug:1.2.13-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:ViewpagerWidget-debug:1.1.5-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:cardframework-debug:1.0.56-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-drivers-debug:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-commands-debug:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-manager-debug:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-release:1.0.1-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:HereToThere-release:1.1.20-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:TripLog-release:1.1.25-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CarHealth-release:1.1.13-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:IntelematicsUtils-release:1.1.10-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:ERS-stageRelease:0.5.22-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CMActivation-release:1.0.4-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:cardframework-release:1.0.56-SNAPSHOT","transitive":false},{"target":"com.google.ui:SlidingTab-release:1.2.14-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:HubSpokeWidget-release:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IntelematicsUtils-release:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-release:1.0.2-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:Cache-release:1.1.6-SNAPSHOT","transitive":true},{"target":"com.google.ui:SlidingTab-release:1.2.13-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:ViewpagerWidget-release:1.1.5-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:cardframework-release:1.0.56-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-drivers-release:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-commands-release:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-manager-release:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-debug:1.0.1-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:HereToThere-debug:1.1.20-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:TripLog-debug:1.1.25-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CarHealth-debug:1.1.13-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:IntelematicsUtils-debug:1.1.10-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:ERS-preprodDebug:0.5.22-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CMActivation-debug:1.0.4-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:cardframework-debug:1.0.56-SNAPSHOT","transitive":false},{"target":"com.google.ui:SlidingTab-debug:1.2.14-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:HubSpokeWidget-debug:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IntelematicsUtils-debug:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-debug:1.0.2-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:Cache-debug:1.1.6-SNAPSHOT","transitive":true},{"target":"com.google.ui:SlidingTab-debug:1.2.13-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:ViewpagerWidget-debug:1.1.5-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:cardframework-debug:1.0.56-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-drivers-debug:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-commands-debug:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-manager-debug:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-release:1.0.1-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:HereToThere-release:1.1.20-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:TripLog-release:1.1.25-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CarHealth-release:1.1.13-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:IntelematicsUtils-release:1.1.10-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:ERS-preprodRelease:0.5.22-SNAPSHOT","transitive":false},{"target":"com.intelematics.android:CMActivation-release:1.0.4-SNAPSHOT","transitive":false},{"target":"com.intelematics.android.lib:cardframework-release:1.0.56-SNAPSHOT","transitive":false},{"target":"com.google.ui:SlidingTab-release:1.2.14-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:HubSpokeWidget-release:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IntelematicsUtils-release:1.1.11-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:IAWebServices-release:1.0.2-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:Cache-release:1.1.6-SNAPSHOT","transitive":true},{"target":"com.google.ui:SlidingTab-release:1.2.13-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:ViewpagerWidget-release:1.1.5-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:cardframework-release:1.0.56-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-drivers-release:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-commands-release:1.0.0-SNAPSHOT","transitive":true},{"target":"com.intelematics.android.lib:device-manager-release:1.0.0-SNAPSHOT","transitive":true}]} ]}
`

**Comment by daveoxley** [comment]
I've tracked down the issue to ErikDubbelboer/gspt. Line 101 in setproctitle.h has this line:
```
    limit = ptr - 8192; // TODO: empiric limit: should use MAX_ARG
```
The number 8192 is too small for the command line being passed in I assume. Making it much larger fixes the issue but not sure what it should ideally be set to.
I'm thinking of fixing this issue by allowing the metadata value to be optionally read from a file.

**Comment by sj26** [comment]
I was just about to look into this for you! The process title gear is pretty fragile. I've reported this upstream as erikdubbelboer/gspt#7. In the meantime we'll see  if we can make metadata set also accept values from stdin, like pipeline upload.

You also might like to consider storing this data as an artifact. Metadata is intended for smaller pieces of data, not necessarily large chunks of structured data like this. :-)

**Comment by daveoxley** [comment]
I considered storing it as an artifact but it wouldn't be ideal. We have a gradle plugin that reads the latest builds and uses the metadata to decide on and run downstream builds. Storing it as an artifact would slow our builds down due to the need to make additional requests. Also the artifacts are on a url that requires authentication (Using BUILDKITE_S3_ACCESS_URL env variable) so the plugin would have have to pull directly from the S3 bucket rather than the url that buildkite returns.

I've opened a pull request to read the metadata value from a file (https://github.com/buildkite/agent/pull/327). I'm happy for you or me to change it to read from stdin instead of or as well as.

**Comment by sj26** [comment]
Oh, are you consuming this externally later via the API? That makes more sense.

I've just updated your PR with some experimental binary links. Maybe double-check it solves this problem?

**Comment by daveoxley** [comment]
Yea

**Comment by daveoxley** [comment]
Yeah, we're consuming it via the API to trigger rebuilds of projects that are dependent on the project currently building. I'm aiming to open source this gradle plugin but I need to separate out some bits from the plugin that are proprietary and not really useful to the community.

The experimental binary resolved this issue. Thanks :+1:
