### ISSUE TITLE
Agent cannot be run under most recent amazon linux / Trace/breakpoint trap

### ISSUE THREAD

**Issue by mbj** [buildkite/agent#291]
The latest amazon linux release disables the `modify_ldt` systemcall golang used.

> The kernel config CONFIG_MODIFY_LDT_SYSCALL, which control
> enable/disable modify_ldt, is disabled on Amazon Linux 2016.03.

Golang fixes this in: https://github.com/golang/go/commit/0f86d1edfb87fddb2c7f50d177b67f48219151f3

I'd hope you could do a new agent release build with a fixed golang.

**Comment by keithpitt** [comment]
Oh! Thanks for letting us know. I just checked the latest Golang release and it looks like they haven't done an official release yet with this fix?

**Comment by mbj** [comment]
@keithpitt AFAIK there is no such release yet. I wounder if golang master is stable enough to use it? Their review process seems to be strict enough. Right now I downgraded to the 2015.09 AMIs but these need to get security fixes applied that need a reboot to get fully active (else the fixed glibc is not globally used), so not a very nice workaround.

**Comment by mbj** [comment]
@lox Was this fixed?

**Comment by lox** [comment]
Actually, now I double check and it's golang 1.9.2. We build with `golang:1.9`, which might be older.

**Comment by lox** [comment]
I'll update the image and the next release should work.

**Comment by lox** [comment]
This is in Beta 36!
