### ISSUE TITLE
Failing chmod for each hook execution

### ISSUE THREAD

**Issue by apparentlymart** [buildkite/agent#294]
In our environment we have the Buildkite hooks installed by configuration management and not owned by the buildkite agent user.

As a result, each time the agent runs a hook (or, more accurately, [the bootstrap script](https://github.com/buildkite/agent/blob/d905a3da31d8b1bc08d97253642206c95ffaaa63/templates/bootstrap.sh#L93) runs a hook) it produces an error in the log:

```
chmod: changing permissions of ‘/etc/buildkite-agent/hooks/environment’: Operation not permitted
```

The error doesn't prevent the build from completing since configuration management already made these scripts executable by the agent user, but it does worry people to see this in the log output, and can be a red herring for people trying to debug why builds are failing.

**Comment by apparentlymart** [comment]
Perhaps the bootstrap script could use `if [ ! -x "$HOOK_SCRIPT_PATH" ]` to run `chmod` only if the file isn't already executable?

**Comment by lox** [comment]
We've stopped the agent marking these as executable.
