### ISSUE TITLE
Command output is printed twice in debug mode

### ISSUE THREAD

**Issue by francoiscampbell** [buildkite/agent#3107]
Hi,

Somewhere between 3.65.0 and 3.87.0, a change caused logs to be printed twice when running in debug mode (`BUILDKITE_AGENT_DEBUG=true`).

3.65.0:
![image](https://github.com/user-attachments/assets/11cab9a1-c755-47e2-993a-c5dba6242990)

3.87.0 with `BUILDKITE_AGENT_DEBUG=true`:
![image](https://github.com/user-attachments/assets/cf1c571e-83f3-41a6-9edf-6940fce90521)

3.87.0 with `BUILDKITE_AGENT_DEBUG=false`:
![image](https://github.com/user-attachments/assets/8c51740a-792b-4fbe-b402-71a86f7ae585)

Notably, this doesn't affect log output coming from the agent itself:
![image](https://github.com/user-attachments/assets/9fbe1496-a34d-4893-b5e6-6fbb46f3d537)

We're running the agent from the `buildkite/agent:3.87.0-ubuntu-22.04` Docker image.

**Comment by DrJosh9000** [comment]
Thanks for raising @francoiscampbell! I think this happened during the large refactor in #3068.
