### ISSUE TITLE
Agent builds for darwin use direct network dns

### ISSUE THREAD

**Issue by sj26** [buildkite/agent#319]
When installing official builds for Mac OS the agent uses direct network DNS instead of OS X's DNS mechanisms. This means resolvers using the `/etc/resolver/X` mechanism or through directory services are not honoured. Maybe because the agent is cross compiled?

For example, using Pow or another similar tool which causes `*.dev` to resolve to `127.0.0.1`, requests for `*.dev` still lookup via network DNS and resolve to `127.0.53.53` instead.

There's more information about Go's name resolution here:

https://golang.org/pkg/net/#hdr-Name_Resolution

**Comment by toolmantim** [comment]
Oh weird, this must have been my previous issue. But I think it works on my machine now… but maybe I'm using a funky build of the agent, I'll have to check.

**Comment by sj26** [comment]
For posterity: we're using go's netdns, not linking against Apple's networking frameworks, so `/etc/resolver/*` won't be honoured (but `/etc/resolv.conf` will). Most folks seem to be abandoning `*.dev` anyway now that Google have their claws in it. `*.localhost` works great!

**Comment by lox** [comment]
Thanks @sj26!
