### ISSUE TITLE
Not obvious how to run as a Windows service

### ISSUE THREAD

**Issue by fdstevex** [buildkite/agent#329]
I checked the documentation and the command-line output from buildkite-agent, and I can't see how to start the agent as a Windows service, so that it runs as a daemon.  Not sure if this is a documentation issue or the agent itself needs to add support for this.

**Comment by keithpitt** [comment]
@fdstevex howdy! I'm actually not sure how to run it as a service! I'm not super knowledgable about Windows, so any help here would be greatly appreciated :)

**Comment by fdstevex** [comment]
Here's what I'm doing - so far it's working for me:
https://gist.github.com/fdstevex/52da0d7e5892fe2965eae105b8cf3883

**Comment by toolmantim** [comment]
@fdstevex thanks so much for those clear instructions! That sounds like the best way to set it up. I'll updated the Windows docs with exactly that method.

**Comment by yeungda-rea** [comment]
I did some work to automate those instructions, and wrote up what I learnt in [a comment on that gist](https://gist.github.com/fdstevex/52da0d7e5892fe2965eae105b8cf3883#gistcomment-2090570)

**Comment by DuBistKomisch** [comment]
Highly recommend using http://nssm.cc/ as a simple solution for this, really lives up to its name.

**Comment by lox** [comment]
Thanks @yeungda-rea and @fdstevex, I expanded upon that a bit for https://gist.github.com/lox/e627d6749c8f212a5cf90158f0e8f9e3.

**Comment by keithpitt** [comment]
We've got an internal TODO to track writing this guide for the 3.0 release which is happening very soon!
