### ISSUE TITLE
Windows graceful exit

### ISSUE THREAD

**Issue by sj26** [buildkite/agent#345]
Windows beta agent doesn't seem to exit gracefully when sent an interrupt signal. The job is finished and it says `[JobRunner] Waiting for all other routines to finish` but this never seems to complete, it just keeps heartbeating and pinging.

**Comment by lox** [comment]
> // Sending Interrupt on Windows is not implemented.

https://golang.org/src/os/exec.go?s=3842:3884#L110

**Comment by lox** [comment]
Closing in favour of #213.
