### ISSUE TITLE
Buildkite should have clean builds out of the box

### ISSUE THREAD

**Issue by emmby** [buildkite/agent#367]
https://github.com/buildkite/agent/issues/173 and subsequent tickets added support for BUILDKITE_GIT_CLEAN_FLAGS to allow users to customize the behavior of git clean.  This is important because, by default, buildkite uses `git clean -fdq`, which does not truly clean the directory before starting a build.  It should use `git clean -fdqx`, which ensure that even ignored files are cleaned before starting a build.

For example, in my repo I ignore the node_modules directory.  Because node_modules wasn't getting cleaned before every build, I was not starting with a fresh set of dependencies before every build and subsequently discovered that a fresh checkout of my project broke, even though it seemed to be fine on the build machine.

**Comment by keithpitt** [comment]
Totally! @emmby we 100% agree :) 

Adding that option was the first step in actually making it the default. Currently it's `fdq` in the `2.x` series, but in `3.0` it now defaults to `fdqx` just like you described :) Check it out:

https://github.com/buildkite/agent/blob/master/clicommand/bootstrap.go#L165

3.0 should drop probably next month! Thanks for the reminder that this is important.

**Comment by keithpitt** [comment]
You'll note here btw that that in 3.0 we've ditched the `bootstrap.sh` file and replaced it with a version written in Golang.
