### ISSUE TITLE
To ensure clean builds, every buildkite user must manually override BUILDKITE_GIT_CLEAN_FLAGS env on every machine in their build fleet

### ISSUE THREAD

**Issue by emmby** [buildkite/agent#368]
https://github.com/buildkite/agent/issues/173 and subsequent tickets added support for BUILDKITE_GIT_CLEAN_FLAGS to allow users to customize the behavior of git clean.  

However, because this is supported in an environment variable and [not in a config file](https://buildkite.com/docs/agent/configuration), this means that every build machine across the fleet must have its BUILDKITE_GIT_CLEAN_FLAGS set the same way manually.  If any machine neglects to set BUILDKITE_GIT_CLEAN_FLAGS, you can run into hard to repro situations such as https://github.com/buildkite/agent/issues/367

This is not a big deal on virtualized/containerized build fleets, but it can be hard to manage on machines that aren't easily virtualized (such as macs used for ios builds)

Either this should be configurable in build config files so that all machines will have the same config, or https://github.com/buildkite/agent/issues/367 should be fixed so that by default machines are properly cleaning their build directories.  Or both would also work.

**Comment by keithpitt** [comment]
@emmby this should already be configurable in your `buildkite-agent.cfg` check this commit: https://github.com/buildkite/agent/commit/5c50c5544fb88454f81b5dbd97b035011ff21acd

```
# Flags to pass to the `git clone` command
# git-clone-flags=-v

# Flags to pass to the `git clean` command
# git-clean-flags=-fdq
```

You should be able to configure both using that syntax, and by the looks of it they should be present (commented out) already in your `buildkite-agent.cfg` file - do you see them?

**Comment by keithpitt** [comment]
(Also, thanks again for submitting these issues! <3)

**Comment by emmby** [comment]
Ah, thank you.  Is the documentation on the website out of date?  It says here that BUILDKITE_GIT_CLEAN_FLAGS is only configurable via env: https://buildkite.com/docs/agent/configuration

**Comment by keithpitt** [comment]
@emmby great find - yeah those docs were 100% wrong. Sorry about that confusion!! @toolmantim has updated them now :)

I'll close this issue now - thanks again for reporting it! 👍
