### ISSUE TITLE
Linking statically to glibc causes segfaults

### ISSUE THREAD

**Issue by grosskur** [buildkite/agent#370]
We're seeing a segfault when running `buildkite artifact download` on a `gs://` URL:

    2016-08-12 13:32:57 INFO   Found 7 artifacts. Starting to download to: /app
    fatal error: unexpected signal during runtime execution
    fatal error: unexpected signal during runtime execution
    fatal error: unexpected signal during runtime execution
    fatal error: unexpected signal during runtime execution
    fatal error: unexpected signal during runtime execution
    fatal error: unexpected signal during runtime execution
    [signal 0xb code=0x1 addr=0xe5 pc=0x7fc6d418c8cc]
    
    runtime stack:
    runtime.throw(0xb67de0, 0x2a)
            /usr/local/go/src/runtime/panic.go:547 +0x90
    runtime.sigpanic()
            /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
    
    goroutine 33 [syscall, locked to thread]:
    runtime.cgocall(0x83cf90, 0xc8204a7658, 0x0)
            /usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc8204a7600 sp=0xc8204a75d0
    os/user._Cfunc_mygetpwuid_r(0x0, 0xc82038a000, 0x7fc6c4000b20, 0x400, 0xc8204b2000, 0x0)
            ??:0 +0x44 fp=0xc8204a7658 sp=0xc8204a7600
    os/user.lookupUnix(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
            /usr/local/go/src/os/user/lookup_unix.go:95 +0xcd8 fp=0xc8204a77f0 sp=0xc8204a7658
    os/user.current(0x40e7c0, 0x0, 0x0)
            /usr/local/go/src/os/user/lookup_unix.go:38 +0x42 fp=0xc8204a7830 sp=0xc8204a77f0
    os/user.Current(0x4ffe2d, 0x0, 0x0)
            /usr/local/go/src/os/user/lookup.go:9 +0x24 fp=0xc8204a7850 sp=0xc8204a7830
    github.com/buildkite/agent/vendor/golang.org/x/oauth2/google.guessUnixHomeDir(0x0, 0x0)
            /go/src/github.com/buildkite/agent/vendor/golang.org/x/oauth2/google/sdk.go:163 +0x28  fp=0xc8204a7888 sp=0xc8204a7850
    github.com/buildkite/agent/vendor/golang.org/x/oauth2/google.wellKnownFile(0x0, 0x0)
            /go/src/github.com/buildkite/agent/vendor/golang.org/x/oauth2/google/default.go:107 +0x36 fp=0xc8204a7920 sp=0xc8204a7888
    github.com/buildkite/agent/vendor/golang.org/x/oauth2/google.DefaultTokenSource(0x7fc6d5d86658, 0xc8200114b8, 0xc8204a7c38, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
            /go/src/github.com/buildkite/agent/vendor/golang.org/x/oauth2/google/default.go:72 +0x307 fp=0xc8204a7ac8 sp=0xc8204a7920
    github.com/buildkite/agent/vendor/golang.org/x/oauth2/google.DefaultClient(0x7fc6d5d86658, 0xc8200114b8, 0xc8204a7c38, 0x1, 0x1, 0x0, 0x0, 0x0)
            /go/src/github.com/buildkite/agent/vendor/golang.org/x/oauth2/google/default.go:34 +0x68 fp=0xc8204a7b38 sp=0xc8204a7ac8
    github.com/buildkite/agent/agent.GSDownloader.Start(0xc8203de100, 0x3e, 0xc82011a460, 0x4, 0xc8202a44d0, 0x6d, 0x5, 0x0, 0x0, 0x0)
            /go/src/github.com/buildkite/agent/agent/gs_downloader.go:32 +0xdf fp=0xc8204a7d30 sp=0xc8204a7b38
    github.com/buildkite/agent/agent.(*ArtifactDownloader).Download.func1()
            /go/src/github.com/buildkite/agent/agent/artifact_downloader.go:82 +0x692 fp=0xc8204a7f80 sp=0xc8204a7d30
    github.com/buildkite/agent/pool.(*Pool).Spawn.func1(0xc8204344c0, 0xc8203de300)
            /go/src/github.com/buildkite/agent/pool/pool.go:43 +0x44 fp=0xc8204a7fa0 sp=0xc8204a7f80
    runtime.goexit()
            /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8204a7fa8 sp=0xc8204a7fa0
    created by github.com/buildkite/agent/pool.(*Pool).Spawn
            /go/src/github.com/buildkite/agent/pool/pool.go:44 +0x80

After digging around, it seems the root cause is linking statically to glibc:

https://sourceware.org/bugzilla/show_bug.cgi?id=19341

See also golang/go#13470 for more background. CockroachDB apparently works around this by linking dynamically to glibc per cockroachdb/cockroach#3392. And the glibc bug mentions that Docker also dynamically links glibc for this reason. I've also verified that linking dynamically fixes the problem in our environment.

So perhaps `scripts/utils/build-binary.sh` should be modified to only use `-ldflags "-extldflags '-static'` when the platform is not `linux`.

**Comment by keithpitt** [comment]
This sort of thing is a little bit out of my depth here - so I'll probably need to get either @toolmantim or @sj26 to weigh in on this one!

**Comment by sj26** [comment]
Oh dear! This seems tricky.

We originally started static linking to restore Debian 7 compatibility in #255. Avoiding segfaults seems more important than Debian 7 compatibility, though.

I think maybe we should default to dyamic linking. Perhaps we can add a static build for folks who want it? I'm not sure.

**Comment by sj26** [comment]
I've reverted the static linking [on 2-1-stable](https://github.com/buildkite/agent/commit/5ee1842938dc3e5cfaa31f34a8fded163973f438) and [on master](https://github.com/buildkite/agent/commit/bd0e42b567ced63c5880100ffafbd9b9b26795f4). Sorry it caused you grief!

The next release should be dynamically linked.

**Comment by sj26** [comment]
It sounds like glibc just doesn't like being statically linked.

Maybe we could try musl? http://dominik.honnef.co/posts/2015/06/go-musl/

**Comment by grosskur** [comment]
One more piece of information, FWIW---I hit this error on Ubuntu 14.04.

My experience with glibc in the past has been that if you build a binary against an old glibc, it will run properly against that glibc or any newer glibc. But, conversely, if you build against a newer glibc, you may reference newer symbols, and you'll get an error when running against an old glibc.

What OS do you build the release binaries on, and what was the error with running a dynamically-linked binary on Debian 7? I'm not that familiar with how this works in Go, but if you haven't already, it might be worth trying to build the release binaries on the oldest platform you want to support, e.g., Debian 7.

**Comment by toolmantim** [comment]
So I was just checking this, and we rely on this for Alpine Linux (and our Docker images) because it uses musl and doesn't include glibc. Hrmm.

**Comment by toolmantim** [comment]
So I think this is a good new default, we'll just need to publish a statically linked version against musl for environments that don't use libc

**Comment by sj26** [comment]
We've found a good workaround for anybody else hitting this issue: you can switch on the pure go dns resolver so that it doesn't attempt to use glibc:

```
GODEBUG=netdns=go buildkite-agent start
```

This worked for somebody else recently~

**Comment by sj26** [comment]
After a lot of umming and ahhing we believe that the best course is to remove glibc entirely and disable CGO. An entirely static binary is the portability promise of Go, and is what we're after. We'll worry about secondary network configurations and process titles separately.

Thanks so much for your thorough report and wisdom, @grosskur. <3
