### ISSUE TITLE
Windows build agent not pulling .buildkite/pipeline.yml

### ISSUE THREAD

**Issue by trashhalo** [buildkite/agent#371]
When I set it to upload the pipeline it kept uploading a empty body causing the backend to return 422 configuration is empty. Worked around it by changing it to upload with the path to `.buildkite/pipeline.yml`

os: windows 10
agent: 2.1.17

**Comment by keithpitt** [comment]
Hey @trashhalo - thanks for the report! Would you be able to try with the latest beta version of the agent? (v3.0-beta.8) I think it may be fixed in that version!

**Comment by trashhalo** [comment]
Confirmed fixed in beta9.

**Comment by codeandcats** [comment]
Hmmm, unless I'm mistaken, this still seem to be an issue today. It seems even though my pipeline file is using the default path of `.buildkite/pipeline.yml` I still have to explicitly specify the path when uploading it.
