### ISSUE TITLE
BK Warning on git version when > 2.x

### ISSUE THREAD

**Issue by tommeier** [buildkite/agent#383]
hola!

<img width="1193" alt="screen shot 2016-09-28 at 1 49 59 pm" src="https://cloud.githubusercontent.com/assets/19973/18900220/f60a8818-8582-11e6-9478-4a711fb364c9.png">

> (git version 2.10.0) and you need version 1.7.6 and above.

**Comment by tommeier** [comment]
Actual bug was that commit no longer exists, but the warning threw me off a bit ;)

**Comment by lox** [comment]
Yup, this is unclear. Given git has moved on quite considerably since then, this error is probably rarely useful.

**Comment by keithpitt** [comment]
I think we should just remove the warning.
