### ISSUE TITLE
JSON pipelines should be able to support string concatenation to support multiple commands per step

### ISSUE THREAD

**Issue by npaufler** [buildkite/agent#390]
It appears it is possible to have multiple commands in a single step when using YAML (i.e. the example here: https://github.com/yoshuawuyts/playground-docker-buildkite/blob/master/.buildkite/pipeline.yml)

i have not been able to make this work when using JSON pipeline files. Ideally, you should be able to do something like this:

```
{
  "steps": [
   {
      "name": "Rspec %n",
      "command": [
        "echo '--- sourcing buildkite-utils.sh'",
        ". script/buildkite-utils.sh",
        "prepare_buildkite_environment_bundle",
        "prepare_buildkite_environment_npm",
        "reset_buildkite_datastores",
        "echo '--- running Rspec;'",
        "script/test.d/70_rspec",
      ],
      "artifact_paths": "log/*.log",
      "parallelism": 11,
      "timeout_in_minutes": 20
    }
  ]
}
```

And have the command array interpreted correctly. Ideally without needing to have semicolons after each line, but if that was a requirement it wouldn't be terrible.

**Comment by keithpitt** [comment]
@npaufler hey! So the...

```yaml
    command: >
      version=$(jq -r '.version' < package.json);
      buildkite-agent meta-data set version-dev "$version";
```

...syntax you see is actually built into YAML itself. YAML has the ability to define strings over multiple lines - which is actually one of the reasons why we recommend as the default (JSON doesn't support that and it doesn't allow comments, which is super useful for adding helpful tips inside Pipeline definitions).

Probably a silly questions...is it possible for you to just use YAML instead of JSON?

**Comment by keithpitt** [comment]
@npaufler I just caught up on the chats in Buildkite Chat, that gave a bit more context at to what's going on here :)

Supporting the array syntax should be pretty straight forward I think! `commands.join("\n")` I think pretty much will solve the issue!

**Comment by keithpitt** [comment]
(that's something we'd need to add on our end)

**Comment by lox** [comment]
Did this end up getting added @keithpitt?

**Comment by lox** [comment]
Pretty sure it did, so closing it.
