### ISSUE TITLE
Multiple commands error detection on Windows

### ISSUE THREAD

**Issue by essen** [buildkite/agent#391]
Hello,

A followup to #223, this time on Windows 7. Agent version: 3.0-beta.11

I have setup a pipeline with the following two commands to run:

```
cat badfile
cat Makefile
```

Output is:

```
> cat badfile
cat: badfile: No such file or directory
> cat Makefile
# See LICENSE for licensing information.
 
PROJECT = ranch
[snip]
```

Despite the failure of the first command, the build succeeds.

Putting the commands in reverse order makes the build fail, hinting that maybe only the last command matters on Windows.

While the above commands run MSYS2 programs, this seems to be unrelated to MSYS2, because the exact same problem can be observed with the following commands:

```
set abc
set
```

And reversing those also makes the test fail instead of succeeding.

**Comment by keithpitt** [comment]
Hey @essen, thanks for reporting!

I just had a quick look into this, and the script we generate for *nix machines is done here: https://github.com/buildkite/agent/blob/master/agent/bootstrap.go#L1135 The `set -e` ensures that the script stops if any of the commands fail.

Here we generate the script we run on Windows: https://github.com/buildkite/agent/blob/master/agent/bootstrap.go#L1126

Is there an equivalent `set -e` type directive we can use in Batch to make it bail if a command fails?

**Comment by essen** [comment]
I have no idea but I will look into it.

**Comment by essen** [comment]
I got it working for the simple case (set abc; set). Now trying against a full test suite with many commands, and will open a PR if all goes well.

**Comment by essen** [comment]
PR is open! #392 

For future reference (mostly for me I guess), I had to do the following to get the environment setup under MSYS2 and properly test the builds:

* Install Go 1.7 from the official site
* export GOROOT=/c/Go (where Go was installed)
* export GOPATH=/mingw64 (though any folder would do)
* export PATH=$PATH:/c/Go/bin
* go get github.com/buildkite/agent
* cd /mingw64/src/github.com/buildkite/agent
* go build
* mv agent.exe buildkite-agent.exe
* PATH=$PATH:. buildkite-agent.exe start --debug --token "mytoken" --build-path /tmp/ --meta-data "os=dev" (PATH because I had path issues otherwise, and metadata to easily select the agent I was testing)

It took me a little of trial and error and is probably not the most efficient way to do it but at least I could debug from SSH. Had to stop the agent from the Web UI in between tries though.

**Comment by keithpitt** [comment]
Merged! Thanks for the PR @essen!
