### ISSUE TITLE
Expose default bootstrap hooks

### ISSUE THREAD

**Issue by sj26** [buildkite/agent#400]
Say I want to override checkout for certain repositories, but not others. Maybe it's an optimization, maybe some repos use mercurial or another source control mechanism. I create a checkout hook on my agent, and implement my custom behaviour. But I also have to copy the [original git hook](https://github.com/buildkite/agent/blob/f9f4573af6430d75f952cb48096bd1769c0122f0/templates/bootstrap.sh#L214-L335) into my hook for the "else" case. And this problem gets worse with the new beta agent — there is no default hook which is easily copyable, although we can still grab the old bash version for now.

It would be great if we exposed hooks a little more and instead I could do something like `buildkite-agent hook --default checkout` or something.

**Comment by lox** [comment]
Sounds like a neat idea!

**Comment by lox** [comment]
When I discussed this with @keithpitt he was concerned that this exposes additional api that we'd then have to support. Feels @keithpitt?

**Comment by keithpitt** [comment]
I think we came to an alternative solution for this? (just in talking about it, not implementing it).

A pre-checkout hook could say `BUILDKITE_CHECKOUT=false` which would tell the agent "don't checkout plz". And that pre-checkout hook could do it's own checkout before we go to ours.

Checkout-less builds is something we've wanted to do anyway, so `BUILDKITE_CHECKOUT=false` would solve both problems I think!

**Comment by lox** [comment]
Yup, I think I agree. 👌🏻

**Comment by sj26** [comment]
Nice.

**Comment by keithpitt** [comment]
Will close for now, since this feature matches really well into "repository-less checkouts". The idea would be in the `pre-checkout` hook, set `BUILDKITE_REPOSITORY=""`, and then do the checkout yourself in the `pre-checkout` hook.
