### ISSUE TITLE
Misleading error when command eval disabled

### ISSUE THREAD

**Issue by yeungda-rea** [buildkite/agent#416]
We are getting a number of questions where people are mistyping their script paths and being confused by a message about command eval. Here's an example:

**Given** I have an agent command eval disabled
**And** I have a repo with the script `bar`
**And** I have a pipeline step with the mistyped command `baz`
**When** my agent runs the step
**Then** my step fails with the message:
> "This agent is not allowed to evaluate console commands. To allow this, re-run this agent without the `--no-command-eval` option, or specify a script within your repository to run instead (such as scripts/test.sh)."

A message such as this would be much easier to diagnose:

> no such file: ./baz
> This agent is not allowed to evaluate console commands. To allow this, re-run this agent without the `--no-command-eval` option, or specify a script within your repository to run instead (such as scripts/test.sh).

**Comment by yeungda-rea** [comment]
I believe the implementation for this error message [here](https://github.com/buildkite/agent/blob/9959825f61a3525b110e60d6f63a27de06c742e6/agent/bootstrap.go#L1110).

**Comment by keithpitt** [comment]
@yeungda-rea oh yes! I do believe @sj26 just changed the code in that area this morning, I'll poke him and see if he can sneak this wording change in as well.;

**Comment by keithpitt** [comment]
I just added that additional line like you suggested @yeungda-rea
