### ISSUE TITLE
Agent should git clean before *and* after checking out commit to be built

### ISSUE THREAD

**Issue by jgavris** [buildkite/agent#417]
The agent does a `git clean` prior to doing `git checkout`. When another build comes around that doesn't have that submodule anymore, git will not remove the directory of the submodule because it's not empty. We enforce that the repository is clean prior to doing a build, and caught this.

```shell
$ mkdir -p /usr/local/var/buildkite-agent/builds/dasher/butterfly-network/software
$ cd /usr/local/var/buildkite-agent/builds/dasher/butterfly-network/software
$ git remote set-url origin git@github.com:ButterflyNetwork/software.git
$ git clean -ffxd
Removing ...
$ git submodule foreach --recursive git clean -ffxd
Entering ...
$ git fetch -v origin 075ae9e4ba832b7bceceef9f217877b699559be8
From github.com:ButterflyNetwork/software
 * branch            075ae9e4ba832b7bceceef9f217877b699559be8 -> FETCH_HEAD
$ git checkout -f 075ae9e4ba832b7bceceef9f217877b699559be8
```

I don't have the logs for those builds readily available, but this is essentially what will happen.

Build 1: With new submodule

```shell
deimos:software (develop) λ git checkout firmware-pod
Switched to branch 'firmware-pod'
deimos:software (firmware-pod) λ git submodule update --init --recursive
Submodule path 'submodules/firmwareimage': checked out 'dad0f5c650c75f6a39548d0f81c31b3dfcb07d7a'
```

Build 2: Without submodule

```shell
deimos:software (firmware-pod) λ git clean -ffxd
deimos:software (firmware-pod) λ git checkout develop
warning: unable to rmdir submodules/firmwareimage: Directory not empty
Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.
deimos:software (develop) λ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        submodules/firmwareimage/

nothing added to commit but untracked files present (use "git add" to track)
```

I believe it is enough to just perform the `git clean` before *and* after the checkout of the commit to be built. We've added this to the beginning of all our pipeline steps anyway, but it would be great to get this into the agent.

**Comment by keithpitt** [comment]
Hey @jgavris, thanks so much for taking the time to submit this issue! The fact that "git will not remove the directory of the submodule because it's not empty" definitely sounds like a problem we should fix! 

However, the fact that the agent doesn't do a `git clean` after the job is by design I'm afraid! It's a little edge-casey, but the idea is we clean _before_ not after, so that if something goes wrong on the agent, or you need to get some information out of the build folder, you can SSH to the agent after a build and see the state of the filesystem.

Let's say you're monitoring for flakey tests, and you finally hit one. You can shut down that agent, SSH to the server it's running on, and see what files are sitting on there. You can even run your tests again manually on the server to try and debug what's going on. If we were to `git clean` afterwards, you'd have no hope of getting to the agent in time.

Perhaps there's another way to fix the submodule problem without doing a git clean? I don't suppose there's a `git remove submodules from filesystem that don't exist anymore` command? :)

**Comment by jgavris** [comment]
The clean is just after the checkout, not after your build script. Whatever artifacts your build leaves behind will be intact so long as you don't start another build.

**Comment by jgavris** [comment]
I've also opened two pull requests with implementation to fix (to stable and master).

**Comment by keithpitt** [comment]
Ohhhhhhhhhhhhh, sorrrryy! I obviously haven't had enough ☕️ today, doh! Let me get a fresh brew and I'll take another look!!

**Comment by jgavris** [comment]
After a checkout, many things can change that would affect what `git clean` will clean up (`.gitignore`, `.gitmodules`) etc.

**Comment by keithpitt** [comment]
I might need to poke @sj26 on this one to see what he thinks (he's our resident Git expert :P)

**Comment by jgavris** [comment]
👋  @sj26 What are your thoughts on this?

**Comment by sschaetz** [comment]
Would be great if we could have this.

**Comment by sj26** [comment]
Hi @jgavris! Sorry for the delays, we've all been on holidays and catching up.

Thank you for writing this up, and for the contributions!

I'm not sure how I feel about this, though. I have some questions:

 - Is this correct in the default case?
 - Are folks relying on the current behaviour?
 - Will it slow down large repositories?
 - Could you achieve the same thing in your specific case with a post-checkout hook?

I'm a fan of [fresh working trees for every job run](https://github.com/sj26/git-worktree-buildkite-hooks). Starting from a guaranteed clean tree seems more sane. We'd need to do a lot more with git to keep large repositories speedy, and provide better guidance and tooling for caching dependencies etc. But it's a fairly big change to how the agent acts now.

Some folks rely on the working tree persisting between jobs for caching. This is why our default git clean doesn't clean git ignored files by default (yet). And I'm concerned your proposed change might also start to clean more than folks relying on this behaviour expect.

**Comment by jgavris** [comment]
Good questions...

- Could you elaborate on what you mean by the default case? I believe this behavior brings us closer to what I would expect `git clean` to do as a build user. If I were trying to build, did a `git clean`, checked out my commit to build, saw the working tree was dirty, I would `git clean` again. 

- Potentially, though unlikely as it depends on switching between commits that have very different ignored files / submodules.

- Sure, in the worst case, the clean time will be doubled. Git is pretty fast though...I've tested `git clean -dffx` in the webkit repository (~10 GB, ~180K commits) and it can clean in about half a second on a retina macbook pro.

```shell
deimos:webkit (master) λ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        test.py

nothing added to commit but untracked files present (use "git add" to track)

deimos:webkit (master) λ time git clean -dffx
Removing test.py

real	0m0.453s
user	0m0.271s
sys	0m0.173s
```

- We are doing this in our use case now as we've hit it a handful of times.

Your worktree implementation is very cool. Unfortunately we have some very large submodules and worktrees do not play nicely with them (yet).

**Comment by jgavris** [comment]
The way I've thought about this...the clean really only *needs* to happen *after* the checkout, because that will clean from the point of view of the revision you're trying to build. It's only a consequence of not necessarily being able to checkout the revision that you also have to clean before.

**Comment by sj26** [comment]
Neat, you've convinced me! Let's give it a go.

I'll merge in those PRs and see what happens.
