### ISSUE TITLE
meta-data get could support a default value

### ISSUE THREAD

**Issue by Akkuma** [buildkite/agent#426]
Using `meta-data exists x` in `set -eu` is cumbersome due to the error codes and I think `meta-data get x || $default` could be simplified to just `meta-data get x $default`.

**Comment by keithpitt** [comment]
Hey @Akkuma - oh right! That's actually a really good point... If you've got `set -eu` then default meta data values would definitely be a pain.

What if it was something like this?

```
buildkite-agent meta-data get "foo" --default "lollies"
```

**Comment by Akkuma** [comment]
I think that would work fine.

**Comment by keithpitt** [comment]
@Akkuma I won't be able to get to this for a few weeks, but if you wanted to take a crack of it yourself - the code you'd need to change is right here! https://github.com/buildkite/agent/blob/master/clicommand/meta_data_get.go#L80

I'd happily accept a pull request on it!

**Comment by keithpitt** [comment]
@Akkuma I've just released `v2.5` of the agent (and another `v3.0` beta) that now has this feature!
