### ISSUE TITLE
Add support for Gitter notification

### ISSUE THREAD

**Issue by prudhomm** [buildkite/agent#427]
Gitter is a chat room system very much like slack but more adapted to development teams.
They already provide quite a lot of integrations (github, docker hub, travis, ...) it would be awesome to have buildkite being one of them ! I would love having buildkite status for our platform showing in the room activity eg in this room  https://gitter.im/feelpp/feelpp

**Comment by keithpitt** [comment]
Hey @prudhomm - thanks for getting in touch! Would you be able to open the same issue over at http://github.com/buildkite/feedback/issues for me? There may even be an existing one there!
