### ISSUE TITLE
trigger is not documented and trigger name has to be lowercase. 

### ISSUE THREAD

**Issue by SydOps** [buildkite/agent#444]
Hi 

Two things waiting your help. 

1) feature `trigger` in pipeline is not documented.

I got help from buildkite Slack, that buildkite does support to trigger other pipelines. 

https://github.com/buildkite/agent-tests/blob/master/tests/trigger-pipeline/.buildkite/pipeline.yml

But I can't find any formal document to talk about this feature. If you have, please point the url for me. 

I think it should be documented at this page https://buildkite.com/docs/pipelines/defining-steps

If you are fine to accept pull request to update this document, I can. But let me know where I can found the repo and which file I need target. 

2)  trigger name has to be lowercase. 

Because there is only one example for me, I have to guess the problem when I have issue with trigger pipeline step. 

If I define a job with uppercase letters, I have to change to lowercase when I put in `pipeline.yml`. That takes me for a while to understand this is the issue.

For example: 

This doesn't work

      - trigger: "API-build"

Error message is: No pipeline with slug "API-build" could be found

This works

      - trigger: "api-build"

**Comment by keithpitt** [comment]
@SydOps thanks for this! I've just moved your comment over to here https://github.com/buildkite/docs/pull/100 as we've got some WIP docs on the go :)
