### ISSUE TITLE
Using BUILDKITE_COMMIT in pipeline.yml files

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#456]
It's common to use `BUILDKITE_COMMIT` in a pipeline.yml file, but with builds that start with using `HEAD` this isn't possible if the `buildkite-agent pipeline upload` is the first step in the pipeline, because although the agent has calculated what the actual git commit is, it hasn't updated the `BUILDKITE_COMMIT` env before the command is run.

For example, this echo:

<img width="237" alt="echo" src="https://cloud.githubusercontent.com/assets/153/25158505/5fa878bc-24ec-11e7-91f9-17c704fdabba.png">

outputs:

<img width="817" alt="untitled 4" src="https://cloud.githubusercontent.com/assets/153/25158430/b27337c2-24eb-11e7-8586-7b623557f3ec.png">

Another example, a [this pipeline.yml example](https://gist.github.com/toolmantim/a5e31805a44e1a6381882658d461dbbb):

```yml
steps:
  - command: echo "$BUILDKITE_COMMIT"
```

<img width="827" alt="pipeline-example" src="https://cloud.githubusercontent.com/assets/153/25158481/12c3bb88-24ec-11e7-99b1-e84f4bc79662.png">

It be great if the buildkite-agent updated the `BUILDKITE_COMMIT` env, as soon as it became aware of the true value in the "Preparing build" step.

I had a quick look at implementing this a few months back, but it looks like it just sends the entire commit up to the agents API. Perhaps the Agents API could return the parsed commit info, and then the agent can update it's local env values?

**Comment by lox** [comment]
Unfortunately this would require parsing the git commit locally in the agent, which ends up being pretty involved. Let's look at this for a future version!

**Comment by reidab** [comment]
For the purposes of interpolating the current commit into pipeline.yml, I've found just changing the pipeline upload step to `GIT_COMMIT=$(git rev-parse HEAD) buildkite-agent pipeline upload` and then referencing `$GIT_COMMIT` in pipeline.yml seems to work fine. 

Overriding `BUILDKITE_COMMIT` in the same way seems like it would work as well.

**Comment by nullobject** [comment]
This issue just bit me too. It would be awesome if `BUILDKITE_COMMIT` was what you expect it to be 😄

**Comment by nullobject** [comment]
I totally forgot about this and it stung us again. Any ETA for a real fix?

**Comment by lox** [comment]
Apologies @nullobject, no ETA yet. It's an annoying issue that we don't have an easy fix for.

**Comment by nullobject** [comment]
> Apologies @nullobject, no ETA yet. It's an annoying issue that we don't have an easy fix for.

That's okay, I understand there are complexities I may not be aware of.

We're using the workaround which overrides the `BUILDKITE_COMMIT` env var as the pipeline is loaded. I'm just worried I'll forget to do this another 6 months down the track 😄 

For future me (and anyone else who has this issue), chuck this in your pipeline settings:

![screen_shot_2018-11-01_at_10_40_46_am](https://user-images.githubusercontent.com/3614/47825399-d5cbd000-ddc5-11e8-8b99-575016f89164.png)

**Comment by lox** [comment]
Lemme have another look and see if I can think of a simpler fix than the one I had in mind. 👀

**Comment by conorgil** [comment]
I just got bit by this too. This behavior is totally unintuitive, so bumping the priority of a fix would make ramping up on buildkite much more user friendly.

**Comment by MFProduction** [comment]
The override fix doesn't work if you trigger a build from another build.

**Comment by Emeline1818** [comment]
Emeline Martinat
