### ISSUE TITLE
environment read sequence in pipeline.yml

### ISSUE THREAD

**Issue by ozbillwang** [buildkite/agent#471]
I’d like to set different environment variables for qa and prod build stack.

For QA, I set the environmennt variables on the top level. 

For PROD, I set environment in its step. 

But when run the build, I found the environment variables in `PROD` still points to QA environment. 

My understanding, the environment on top level will be a lower priority than the environment in each step. But seems not. Will this be a bug in buildkite? 

Buidkite version is 2.5.1

```
$ cat pipeline.yml

---
env:
  AWS_REGION: ap-southeast-2
  STACK_NAME: stack
  ENVIRONMENT: qa
  VARFILE: qa.tfvars

steps:
  - label: qa plan
    command:
      - 'terraform plan'
    agents:
      queue: 'stack-qa’ 

  - block

  - label: prod plan
    command:
      - 'terraform plan'
    env:
      ENVIRONMENT: prod
      VARFILE: prod.tfvars
    agents:
      queue: 'stack-prod'
```

**Comment by lox** [comment]
This was fixed in v3 beta 34.

**Comment by pmunin** [comment]
See the same issue on agent  v3.22.1
