### ISSUE TITLE
"Concurrency" setting in pipeline.yml is ignored when "Global Concurrency Limit" is not set in UI

### ISSUE THREAD

**Issue by SydOps** [buildkite/agent#472]
There are two places to set `concurrency`. The document, [Controlling Concurrency](https://buildkite.com/docs/builds/controlling-concurrency),  doesn't mention, set "Global Concurrency Limit" to 1 in UI is mandatory. 

I set  `concurrency:`  and `concurrency_group: ` in pipeline.yml file only at first, and found the pipeline doesn't work as I expected. 

After digging the problem, I realized finally, I have to manually set  "Global Concurrency Limit"  in UI, then the concurrency in step of pipeline.yml works. 

Please confirm if this is a bug or not. If not, please update related document that you have to set `Global Concurrency Limit` first if you need to enable concurrency feature. 

buildkite version is v2.5.1

**Comment by toolmantim** [comment]
Sorry you're having a problem with that. You don't have to set the concurrency limit in the UI at all, it should work just fine from your `pipeline.yml` regardless of what you've set in the UI. If you find there's a build that's not behaving, can you email your pipeline.yml and a link to the build to support? And we can look into it for you!
