### ISSUE TITLE
Concurrency per host

### ISSUE THREAD

**Issue by eredi93** [buildkite/agent#473]
I have cluster of ~10 workers with 3 agents each having multiple agents allows me to have a better utilisation of the machine resources.
By having multiple agents on one host may run multiple steps of a build on a machine, this some times can be a problem eg if you try to pull the same docker image at the same time the daemon may hung
would be nice to set a per-host concurrency for every build where steps how a build must run in separate machines

**Comment by toolmantim** [comment]
Sounds like you've got a weird bug for docker pull there! You shouldn't get a hung process… is that a Docker bug?

As for limiting concurrency per host, it's somewhat in your control based on whether you run multiple agent processes, and what targeting rules you use.

Perhaps you need a "single-agent=true" agent meta-data/tag, and then target `single-agent=true` in any steps that are sensitive to multiple agents running.

**Comment by toolmantim** [comment]
I'm going to close this for now
