### ISSUE TITLE
Retry/sleep Git checkouts

### ISSUE THREAD

**Issue by keithpitt** [buildkite/agent#477]
Sometimes GitHub web hooks sender faster than the time it takes for their Git servers to update. So builds end up starting before the commit exists.

This often surfaces as this error:

```
$ git checkout -f <hash>
fatal: reference is not a tree: <hash>
```

It would be good if the agent could "guess" if the checkout failed because of this, and do an automatic sleep/retry (with a sensible "give up" limit).

This should be pretty straight forward since we moved the Bootstrap to "Golang" - we already have a `retry` package that can help here too.

**Comment by keithpitt** [comment]
I actually think the first step to fixing this is to determine under what circumstances should we try a "retry". I think @lox you had some ideas on this?

**Comment by keithpitt** [comment]
(Also @sj26)

**Comment by jeremy** [comment]
This can also happen when a branch is force-pushed after the webhook is triggered but before the build is performed. The commit really is gone, then. In this case, we'd prefer the build to be skipped instead of retrying and failing.

**Comment by caarlos0** [comment]
I'm having this issue in a few repos. Sometimes it takes hours for the commits to show up on the `pull/NUMBER/head` ref. 

I just sent an email to github support to see if they can help with anything... waiting for a response

**Comment by rafaelmagu** [comment]
We have been seeing this issue as well, but only on the `develop` branch (the default), after a PR is merged. Retrying doesn't seem to fix it. I "fix" it when it happens by logging onto the agent and issuing a `git fetch` on the build's working directory. But that's hardly a solution.

**Comment by sj26** [comment]
@rafaelmagu that sounds like a related issue with pull request caching. Send us an email to support@buildkite.com with a link to a failing build and we can probably fix that up for you. :-)

**Comment by jgavris** [comment]
This might also fix an issue we're seeing where Xcode locks (immutable flag) and the prepare build folder git checkout fails. One or two retries automatically would be nice!

**Comment by jgavris** [comment]
Just to reiterate, we hit this issue (git checkout fails due to locked files) a few times a day. The next git checkout is fine after a few seconds pass. This would be really big value for us, and hopefully a fairly small change to the agent.

**Comment by dch** [comment]
@jgavris maybe you should raise this also with github support? The work-around in buildkite seems to be required due to timing issues at their end.

**Comment by jgavris** [comment]
@dch Our issue is with `git checkout` / `git clean` exiting non-zero due to build products from the previous build that are still present and locked. Slightly different issue that could also be taken care of by implementing 'retry checkout after a few seconds'.

**Comment by lox** [comment]
We have a feature in development at the minute that will allow automatic retries on certain exit codes. That will provide a general solution to this without agent changes. I think that would be our preference, but we're still keen on feedback on this one!

**Comment by keithpitt** [comment]
We've got checkout retry gear in the agent already, behind an "experiment" feature flag. We're gonna roll this up into the standard behaviour, which will solve this issue.
