### ISSUE TITLE
Apt server misconfigured - `Packages` reports wrong sizes/hashes

### ISSUE THREAD

**Issue by mistydemeo** [buildkite/agent#481]
When configuring an aptly server to pull from `https://apt.buildkite.com/buildkite-agent`, I noticed that the filesizes reported by `Packages` don't match up with the actual files being served. For example, https://apt.buildkite.com/buildkite-agent/pool/b/bu/buildkite-agent_2.0.1_x86_64.deb is reported by `Packages` as being 2363890 bytes with an sha1 of d2da301771a5ae42b3bdda7c2cde9ae907699abb, but the actual file being served is 2364026 bytes with an sha1 of 4f0363e1489be194c15070ca28f516f74fdda611.

**Comment by keithpitt** [comment]
Thanks for the heads up @mistydemeo! I removed the broken packages (they were very old) so you should be able to mirror `apt.buildkite.com` now without any issues. I tried mirroring myself and it all seems to work fine!

```
aptly mirror update buildkite-experimental
Downloading https://apt.buildkite.com/buildkite-agent/dists/experimental/InRelease...
Downloading https://apt.buildkite.com/buildkite-agent/dists/experimental/Release...
Downloading https://apt.buildkite.com/buildkite-agent/dists/experimental/Release.gpg...
gpgv: Signature made Tue 30 May 2017 03:30:03 AM UTC using RSA key ID 6452D198
gpgv: Good signature from "Buildkite <dev@buildkite.com>"
Downloading & parsing package files...
Downloading https://apt.buildkite.com/buildkite-agent/dists/experimental/main/binary-amd64/Packages.gz...
Downloading https://apt.buildkite.com/buildkite-agent/dists/experimental/main/binary-arm/Packages.gz...
Downloading https://apt.buildkite.com/buildkite-agent/dists/experimental/main/binary-arm64/Packages.gz...
Downloading https://apt.buildkite.com/buildkite-agent/dists/experimental/main/binary-armhf/Packages.gz...
Downloading https://apt.buildkite.com/buildkite-agent/dists/experimental/main/binary-i386/Packages.gz...
Building download queue...
Download queue: 0 items (0 B)

Mirror `buildkite-experimental` has been successfully updated.
```
