### ISSUE TITLE
Buildkite agent token environment variable is misdocumented

### ISSUE THREAD

**Issue by mistydemeo** [buildkite/agent#490]
The buildkite-agent documentation [suggests](https://buildkite.com/docs/agent/configuration) that the `BUILDKITE_AGENT_ACCESS_TOKEN` environment variable is used to configure the agent's token. That documentation seems to be incorrect though; while [clicommand/global.go](https://github.com/buildkite/agent/blob/7030a06f701df661d7ef4d9a332611d86d290915/clicommand/global.go#L15-L20) does use that name, [clicommand/agent_start.go](https://github.com/buildkite/agent/blob/7030a06f701df661d7ef4d9a332611d86d290915/clicommand/agent_start.go#L99-L104) uses a different environment variable - `BUILDKITE_AGENT_TOKEN`. In testing, I can't configure an agent using `BUILDKITE_AGENT_ACCESS_TOKEN`, but `BUILDKITE_AGENT_TOKEN` does work.

It looks like this confusion was brought up in #143, but it wasn't resolved at that time.

**Comment by lox** [comment]
You are absolutely correct, that one tripped me up ages ago and I'd completely forgotten about it.

**Comment by mistydemeo** [comment]
Thanks!

Are these two tokens different things, or the same thing being used under two names?

**Comment by lox** [comment]
They do different things. The `BUILDKITE_AGENT_TOKEN` is used for an agent to initially connect, at which point a per-agent `BUILDKITE_AGENT_ACCESS_TOKEN` is issued to the agent. It's not something that should need to be configured. Sorry for the confusion and thanks for the report!
