### ISSUE TITLE
Unbounded memory usage in artifact uploads (2.x series)

### ISSUE THREAD

**Issue by ticky** [buildkite/agent#493]
It appears that uploading artifacts is memory-inefficient, [reading the whole file into RAM](https://github.com/buildkite/agent/blob/16a9807a91c4dd1388649557108d4092ae4860a4/agent/s3_uploader.go#L99-L105) so it can be uploaded.

On a cursory glance [it looks like using `PutReader`](http://godoc.org/github.com/AdRoll/goamz/s3#Bucket.PutReader) might be the better approach.

**Comment by lox** [comment]
I believe this should be fixed with the new aws sdk stuff!

**Comment by ticky** [comment]
When was that added?

**Comment by lox** [comment]
https://github.com/buildkite/agent/pull/474 and then beta 29.

**Comment by ticky** [comment]
Ah, okay, looks like https://github.com/buildkite/agent/pull/474/files#diff-562b716c383b110626cb55c1c9f83252R87 might well have changed it. 😄

Can we somehow test this use case?

**Comment by lox** [comment]
Yup, that's probably a good idea. I will do some memory profiling.

**Comment by lox** [comment]
Re-opening, as this is still an issue in the 2.x series.

**Comment by npaufler** [comment]
Any word on this being backported to the 2.x agent series?

**Comment by lox** [comment]
I don't think we will port this to the 2.x series, apologies @npaufler. Upwards and onwards! Stable 3.x release is soon.

**Comment by lox** [comment]
This will land in the latest stable release via #604, thanks @sj26.

**Comment by jeffparsons** [comment]
❤️ 

This is currently affecting us. (Trying to use `buildkite-agent artifact upload` to store very large virtual machine images.) Is there an ETA on v2.6.9?

**Comment by lox** [comment]
Sorry about the delay @jeffparsons! It's been all hands on deck for the v3 agent! Let us know how you go with https://github.com/buildkite/agent/releases/tag/v2.6.9.
