### ISSUE TITLE
Provide SHA256 checksums for releases

### ISSUE THREAD

**Issue by rnaveiras** [buildkite/agent#500]
Please provide SHA256 checksums for the releases, and make them available at  https://github.com/buildkite/agent/releases so that the downloads can be verified

**Comment by lox** [comment]
Given we'd be making the checksums available from the same spot, what would be being accomplished? Can you let us know a bit more about your use case?

**Comment by toolmantim** [comment]
Hi @rnaveiras. Sorry we don't offer them on the GitHub releases just yet!

We do have SHA256 checksums via our download.buildkite.com URL. For example:

https://download.buildkite.com/agent/stable/2.6.4/buildkite-agent-darwin-386
https://download.buildkite.com/agent/stable/2.6.4/buildkite-agent-darwin-386.sha256
https://download.buildkite.com/agent/unstable/3.0-beta.28/buildkite-agent-darwin-386
https://download.buildkite.com/agent/unstable/3.0-beta.28/buildkite-agent-darwin-386.sha256

and also via the 'latest' URL:

https://download.buildkite.com/agent/stable/latest/buildkite-agent-darwin-386
https://download.buildkite.com/agent/stable/latest/buildkite-agent-darwin-386.sha256
https://download.buildkite.com/agent/unstable/latest/buildkite-agent-darwin-386
https://download.buildkite.com/agent/unstable/latest/buildkite-agent-darwin-386.sha256

They're also served from a CDN, so much faster than the GitHub releases.

**Comment by rnaveiras** [comment]
@toolmantim thanks, that is just what I need.
