### ISSUE TITLE
Pipeline Env Variables availability

### ISSUE THREAD

**Issue by benoit-dupuis** [buildkite/agent#513]
Hello!

I'm having an issue but I'm not sure if it's a bug or by design but I'm running into this problem: I'm trying to access an environment variable defined in my pipeline from a pipeline pre-command hook and I'm getting a `unbound variable ` message.

```
.buildkite/pipeline.yml:

env:
   MYVAR: "value"
```
```
.buildkite/hooks/pre-command:

echo "${MYVAR}"
```

It'd be great if the agent would fetch and load the pipeline before executing hooks.

Thanks!

**Comment by lox** [comment]
Sorry for the late reply @benoit-dupuis, this certainly sounds like unexpected behaviour. Are you still seeing this?

**Comment by lox** [comment]
We've fixed this in Beta 34!
