### ISSUE TITLE
bootstrap.sh should check out submodules by default

### ISSUE THREAD

**Issue by MSch** [buildkite/agent#52]
basically

```
buildbox-run "git checkout -qf \"$BUILDBOX_COMMIT\""
buildbox-run "git submodule update --init"
```

**Comment by keithpitt** [comment]
@ahawkins are you doing a `git submodule update --init` in your bootstrap.sh file?

**Comment by keithpitt** [comment]
I've added it to our `bootstrap.sh` for the upcoming 1.0 release of the agents: https://github.com/buildkite/agent/blob/master/templates/bootstrap.sh#L107

**Comment by keithpitt** [comment]
If you'd like similar behaviour now, just copy those 3 lines into your current `bootstrap.sh`

Thanks everyone for your help!! :dancers:

**Comment by blueimp** [comment]
Sorry to comment on a closed issue, but would it be possible to disable the git submodule calls with a buildkite configuration setting or an environment variable?

This would be useful for minimal agents without perl installed (git submodules require perl).

Tasks on an agent without perl don't break, but they still display error messages like this:
```sh
/usr/libexec/git-core/git-submodule: line 1: /usr/bin/perl: not found
```

Currently I'm disabling git submodule calls with the following command, but that's rather brittle:
```sh
sed -i 's/\(git submodule\)/true \1/g' /buildkite/bootstrap.sh
```

**Comment by toolmantim** [comment]
@blueimp can you give the bootstrap from #168 a go? I've added a `BUILDKITE_DISABLE_GIT_SUBMODULES` environment variable for disabling the git submodule checkout commands.

**Comment by blueimp** [comment]
Thanks, I've added my comment to #168
