### ISSUE TITLE
Add BUILDKITE_GCS_ACCESS_URL env variable

### ISSUE THREAD

**Issue by mcgain** [buildkite/agent#528]
There doesn't seem to be an equivalent of `BUILDKITE_S3_ACCESS_URL` for GCS. At the moment, GCS returns a url of `storage.googleapis.com` which are designed for API usage. Humans can fetch objects on GCS with a `storage.cloud.google.com` url. Respecting `BUILDKITE_GCS_ACCESS_URL` would allow human users to just click on the links in buildkite and be able to download artifacts. 

For machine users, we would still have to substitute `storage.googleapis.com` for `storage.cloud.google.com` but that's ok. To solve the problem completely, it would be nice to differentiate human download urls from machine ones. `BUILDKITE_GCS_ACCESS_URL` vs `BUILDKITE_GCS_API_ACCESS_URL` for example. This is a secondary concern though.

(GCS was added in #207 so cc @grosskur )

**Comment by lox** [comment]
Closing now that we have #532, @mcgain let me know if this doesn't provide a workable solution in the short term.
