### ISSUE TITLE
Issue with code checkout on buildkite agents

### ISSUE THREAD

**Issue by notana** [buildkite/agent#533]
There seems to be an issue with code checkout on agents on rare occasion where the .git folder is not created correctly. When this happens on an agent, it means that every build for that pipeline on that agent will fail.

This can be fixed by adding a global hook to check and fix the workspace if it detects it is in this state, but it should really be resolved at the root of the issue.

I have attached a snippet of one of my build logs for reference. I am unsure how it gets into this state (possibly cancelling a build at a bad time) but it is inconvenient non-the-less.

```

$ mkdir -p /var/lib/buildkite-agent/builds/buildkite_agent-0d36ebbf02a599f51/company/pipeline
$ cd /var/lib/buildkite-agent/builds/buildkite_agent-0d36ebbf02a599f51/company/pipeline
$ git remote set-url origin git@bitbucket.org:company/repository.git
fatal: Not a git repository (or any of the parent directories): .git

```

**Comment by keithpitt** [comment]
@notana thanks for the report! Hrm...this is an odd one! Do you have any logs of when the git checkout failed?

**Comment by notana** [comment]
What kind of logs are you looking for? I have attached logs in the initial issue

**Comment by toolmantim** [comment]
@notana I think @keithpitt wanted to know what the root cause of the issue might be? As in, what caused the corrupt checkout in the first place?

In the mean-time, here's a `pre-checkout` hook I've written and tested, that should help you:

```bash
#!/bin/bash

set -euo pipefail

# Sometimes checkouts can become corrupt, invalid git repositories.
#
# This hook checks to see if the cached checkout is a valid git repository, and
# if it isn't, then it removes the directory so we can have a clean checkout

if [[ -d "$BUILDKITE_BUILD_CHECKOUT_PATH" ]] && ! git --git-dir="$BUILDKITE_BUILD_CHECKOUT_PATH/.git" rev-parse > /dev/null 2>&1; then
  echo "~~~ Cleaning invalid git checkout"
  rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH"
fi
```

**Comment by notana** [comment]
I have no idea what the root cause is unfortunately. If I find it, I will post it here.

**Comment by lox** [comment]
I've implemented a check for some forms of corrupted checkouts here: https://github.com/buildkite/agent/pull/556
