### ISSUE TITLE
Batched artifact uploads share an upload authorisation timeout

### ISSUE THREAD

**Issue by ticky** [buildkite/agent#559]
It appears that when multiple artifacts are uploaded in one `buildkite-agent artifact upload` call, they must all be finished uploading within 10 minutes (soon to be longer; buildkite/buildkite#2390), or they will begin to be rejected by s3.

This mostly affects customers with slow upload speeds to, or who are very far from our lone s3 bucket in North America. It might be better to get upload authorisation for each file individually, so this issue can be mitigated!

**Comment by keithpitt** [comment]
Gonna close this. We tweaked the timeout to 30 minutes which should hopefully help in those scenarios.

**Comment by ticky** [comment]
I mean, that’s good but we should probably still look into getting an upload authorisation per file instead, so this issue _can’t_ happen?
