### ISSUE TITLE
Pull request support for remote repos

### ISSUE THREAD

**Issue by mwbrooks** [buildkite/agent#56]
Hi all,

Should the agent support pull requests for remote repositories? Personally, I think it should.

I've noticed that the pull request [phonegap/ios-deploy/pull/68](https://github.com/phonegap/ios-deploy/pull/68) is failing because the commit cannot be found. From the looks of it, the agent is trying to checkout the commit from the `origin` repository, rather than adding the remote's repository.

I haven't dug into the code, but I'm open to adding support for remotes. However, I want to make sure this is a legit bug and desired feature of the agent :)

**Comment by keithpitt** [comment]
Hey @mwbrooks! Sorry for the late reply to this, it just came back up on our radar. I've been doing some thinking about this, and just wanted to open it up for discussion. I think these are steps for allowing this:

- [ ] Option to toggle pull requests triggering from different GitHub repos 
- [ ] Send through the correct repository in the `BUILDBOX_REPOSITORY` ENV variable
- [ ] Agent magic

Currently, on the build server, we scope the builds by the agent name, so: `~/.buildbox/builds/[agent-name]/[account-name]/[project-name]` - this has tripped us up a couple of times, especially when changing the repository location.

Perhaps we need to change how we scope the folders, and include the repository? `~/.buildbox/builds/[account-name]/[project-name]/git-at-github-com-slash-user-project` or something?

**Comment by keithpitt** [comment]
The other idea is to just use the repository `~/.buildbox/builds/git-at-github-com-slash-user-project`. Or...even... `~/.buildbox/builds/1234`, and keep the last 20 or so build folders, and do a fresh checkout on each build and use the git `--depth` option.

**Comment by mwbrooks** [comment]
Hi @keithpitt,

Thanks for the following up! It would certainly be nice if pull requests "just worked" when it was enabled on the Github hook. Following that workflow, it makes sense that build folder scoping applies to both the default project's URL and the pull request URLs.

`~/.buildbox/builds/[account-name]/[project-name]/[github-username]/[github-project-name]/`

The above creates a predictable directory path that should work for both Github and Bitbucket. The downside is that projects with a large number of pull requests may accumulate a large number of stale directories.

`~/.buildbox/builds/1234`

When I first started using Buildbox, I ran into a few issues with file permissions and git ignored files. I quickly patched the file permissions by updating the files Buildbox's git repository. I also manually created the required (but git ignored) files. Afterwards, the builds started to work and started to pass. A few weeks later, a team member cleared the Buildbox cache and immediately the builds started to fail because of the file permissions and missing git ignored files. The whole point of this story is that if Buildbox checked out a fresh repository each time, I wouldn't have been able to monkey patch the Buildbox repository :P There are certainly downsides to having Buildbox checkout a new project each time (bandwidth and time) but quality would go up a little.

**Comment by keithpitt** [comment]
Could you could probably create the missing files and fix the permissions in your build script?

**Comment by mwbrooks** [comment]
@keithpitt sorry, I think I describe the scenario poorly.

The ignored files and permissions were my own fault. The point of the story is that by having Buildbox use a fresh clone on each build, the developer cannot alter the build cache instead of the repo's source.

You're right, a good solution would be to either:
- Check the proper permissions into Git
- Or have the build script update the required permissions

An example where the git ignored files can lead to false positives in a build would be this:
- I have a node.js project that git ignores `node_modules/`
- The build script runs `npm install` before each build.
- All tests pass and are valid
- I remove a dependency from `package.json` but continue to reference it in the code
- The next Buildbox build will pass even though it should fail
  - This is because `node_modules/` is a git ignored directory that will persistent with each build
  - `npm install` only adds and updates files in `node_modules/` but will not remove dependencies
  - The result is that my removed dependency still exists in `node_modules/`

**Comment by keithpitt** [comment]
Hey @mwbrooks - I think i've got all of this figured out now. I've wrapped the config that'll allow pull request builds from forked repos around a feature flag on Buildkite. Is this something you'd be interested in playing with?

**Comment by keithpitt** [comment]
Going to close this as we now have the option to turn this feature on for accounts.

**Comment by mwbrooks** [comment]
Nice @keithpitt thanks! Sorry I didn't reply above. It looks like the message was lost in my inbox.

**Comment by dmiluski** [comment]
Stepping through this PR now. Was there any options for forked branch support today?

**Comment by toolmantim** [comment]
@dmiluski we support third-party forks right now. But in your case, you should be able to setup webhooks from your fork directly into a separate Buildkite pipeline? I think that'd mean you can test it and not have it affect anything in the main repository or pipeline. 

We also support testing the fork on the pipeline of the fork’s target repository itself, and in that case we namespace the branch name to be the "username:branch". If that suits?

I might be missing some important info though sorry!

If you want to explain a little more about the context and describe the exact setup you have, perhaps we can help figure it out for you. You’re best to email support@buildkite.com so we can help ☺️

**Comment by toolmantim** [comment]
Ah, you're right, there's no real way to specify a fork build via the new builds dialog @dmiluski. That's a totally valid request though. Can you file a new issue here describing what you're trying to do (basically what you already wrote above) https://github.com/buildkite/feedback/issues — thanks!
