### ISSUE TITLE
bootstrap.sh and RSA key fingerprints

### ISSUE THREAD

**Issue by moltar** [buildkite/agent#57]
It seems like the default bootstrap.sh is not behaving well on CentOS 7. I don't have time to debug it, but it gets stuck on the "RSA key fingerprint" step. The "yes yes" piping does not help. The solution is to do this:

```
ssh -o StrictHostKeyChecking=no github.com ls
```

Which essentially tries to login without strict key checking, which will populate known_hosts file. Just pipe the output of IN/ERR to /dev/null, because the command will error out.

**Comment by keithpitt** [comment]
Hey @moltar just wanted to let you know that we've got a solution for this now and it's scheduled for release with our buildkite-agent 1.0. Thanks!! :muscle:
