### ISSUE TITLE
Pipeline parsing of "pipeline.yml" failed (Expected identifier to start with a letter)

### ISSUE THREAD

**Issue by mehdivk** [buildkite/agent#584]
Heya! 

Thanks for the great service! We really love it ❤️ 

We recently upgraded our agents from `v3.0-beta.34` to `v3.0-beta.35` and one of our build pipelines started failing. I get the following error:

```
2017-11-13 04:06:54 INFO   Searching for pipeline config...
--
  | 2017-11-13 04:06:54 INFO   Found config file ".buildkite/pipeline.yml"
  | 2017-11-13 04:06:54 FATAL  Pipeline parsing of "pipeline.yml" failed (Expected identifier to start with a letter)
```

We haven't change the `.buildkite/pipeline.yml` for some time and I wonder if this is result of a bug that is introduced via `v3.0-beta.35`.

We're not that comfortable to share the `.buildkite/pipeline.yml` file via Github but more than happy to email it to you. I just need the email address.

Cheers!

**Comment by lox** [comment]
Mind sending it to us at hello@buildkite.com?

**Comment by lox** [comment]
We introduced a new parser for identifier expansions in beta 35, so it's entirely possible it's related.

**Comment by mehdivk** [comment]
@lox Thanks for the quick response! I emailed the file to the mentioned address.

**Comment by lox** [comment]
I've replied to the ticket, and I'm investigating, but at a guess this is because the pipeline include `$(echo blah)` bash expansions. These need to be escaped, either `\$(echo blah)` or `$$(echo blah)`.

**Comment by mehdivk** [comment]
Just to confirm, The solution from @lox fixed our problem. Thanks!

**Comment by mehdivk** [comment]
Also, closing this one

**Comment by lox** [comment]
We'll follow up with a better error, something like "$( expansions need to be escaped" or similar.

**Comment by wpcarro** [comment]
Has the team updated these parsing error messages? I believe I'm encountering a similar error related to including a `"$@"` in a pipeline command.

Oddly enough my pipeline also includes subshells like `"$(pwd)"`, which -- to my knowledge -- haven't broken any of the parsing. So far only `"$@"` seems to be problematic.
