### ISSUE TITLE
Steps with only a newline error with "Is a directory"

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#591]
Because of an old quirk/bug in our pipeline web UI settings, some people have pipelines that contain an empty step at the start of their pipeline:

<img width="98" alt="untitled 4" src="https://user-images.githubusercontent.com/153/33051091-66292504-cebc-11e7-89d1-f6157e54bb07.png">

```
BUILDKITE_COMMAND="
"
```

For v2 agents, these would run fine:

```
Running build script
$
```

In v3, these steps now fail with the following error:

```
Running build script
$ ./"
"
$ /bin/bash -c /buildkite/builds/buildkite-agent-abc123/my-org/my-pipeline
/bin/bash: /buildkite/builds/buildkite-agent-abc123/my-org/my-pipeline: Is a directory
```

**Comment by keithpitt** [comment]
Just chatting with @lox, I think the plan here is to still error if no command is set - but show a better/helpful error message.
