### ISSUE TITLE
If a job fails to acquire known_hosts.lock it busy waits until the job times out

### ISSUE THREAD

**Issue by tessereth** [buildkite/agent#592]
I have a fair number of builds that are failing in the "Preparing build directory" step with:
```
# Could not aquire lock on "/var/lib/buildkite-agent/.ssh/known_hosts.lock" (Locked by other process)
# Trying again in 1s...
```
These builds then sit at this line and burn 100% CPU until the job times out or is cancelled. Looking through the code, this seems to be the culprit:
https://github.com/buildkite/agent/blob/0bfe5811eefd4e8d83a3cefa93725a54609b3482/bootstrap/shell/lockfile.go#L50-L56
I don't know Go super well but this looks like it's doing an infinite busy loop waiting for the thread to be cancelled. I would assume that this `for` loop shouldn't be there so if `ctx` is not done it attempts to acquire the lock again.

If there's any additional information you need or anything I can do to help fix this, please let me know. FYI, we're running buildkite agent version `v3.0-beta.35`. Thanks for your help!

**Comment by lox** [comment]
Sorry you've run into this! Just working on a fix presently.

**Comment by tessereth** [comment]
Commented, fixed and released with in a day! I'm impressed. Thanks so much!
