### ISSUE TITLE
Update command line documentation for Windows

### ISSUE THREAD

**Issue by keithpitt** [buildkite/agent#60]
It's currently UNIX specific.

**Comment by xdansmith** [comment]
Any update on this? I'm excited about trying Buildkite; a lot of our projects are built in .net though, so we need Windows support to run the msbuild builds.

**Comment by keithpitt** [comment]
Hey @xdansmith, we've got a beta we can add you to that will give you access to the Windows agent that we have working. If you email `hello@buildkite.com`, I can get you on it :)

**Comment by toolmantim** [comment]
The new agent now has windows support: https://buildkite.com/docs/agent/windows The configuration file is now platform agnostic too and works across all platforms :+1:
