### ISSUE TITLE
Make selective S3 artifacts 'private'

### ISSUE THREAD

**Issue by sinahwz** [buildkite/agent#603]
It would be really good to have a feature in order to be able to make selective S3 artifacts as 'private'

**Comment by toolmantim** [comment]
Thanks for the feedback! Do you have more details/context you could provide? Artifacts are "private" in the sense that only people with pipeline access can access them. You can also use your own S3 and gcloud buckets: https://buildkite.com/docs/agent/cli-artifact

**Comment by sinahwz** [comment]
My main concern is when uploading artifacts into our own S3 Bucket, and by setting "BUILDKITE_S3_ACL=private" all the artifacts are set as private. I was curious if it is possible to have something for example as a whitelist for those artifacts we don't need to be private(or vice versa), e.g. an html artifact among all the other artifacts which needs to be accessed publicly.
In other words apply "BUILDKITE_S3_ACL=private" only to the desired artifacts

**Comment by toolmantim** [comment]
Could you do something like this…

```shell
env BUILDKITE_S3_ACL=private buildkite-agent artifact upload "private/*"
```

Or perhaps make a script helper, say `/usr/local/bin/buildkite-agent-upload-private-artifact`:

```shell
#!/bin/bash

set -eu

export BUILDKITE_S3_ACL=private

buildkite-agent artifact upload "$@"
```

or vice versa for public?

**Comment by lox** [comment]
I'd love to hear what you are using `BUILDKITE_S3_ACL=public` for! Ideally it would always be private. We've talked about a way to have the Buildkite UI generate signed links to download them, would that solve your problem?

**Comment by sinahwz** [comment]
@toolmantim I will try the solution asap and will get back to you 👍 
@lox In our scenario a set of artifacts are generated, out of which we need only a generated html and css to be accessed publicly, not the rest

**Comment by keithpitt** [comment]
@sinahwz sorry for the late reply to this, lemme know if you need any more help on this one!
