### ISSUE TITLE
Beta-37 Agent Git Submodule Issue

### ISSUE THREAD

**Issue by Regner** [buildkite/agent#606]
We recently upgraded to the v3.0-beta.37 agent and have started getting this:

```
Warning: Failed to enumerate git submodules: Error running `/usr/bin/git submodule foreach --recursive git remote get-url origin`: exit status 1
```

It does not happen on a clean build, but does always happen when building a repo already checked out.

**Comment by lox** [comment]
Any idea what version of git you have? The `git remote get-url origin` turns out to have been added more recently than I thought.

**Comment by lox** [comment]
See https://github.com/buildkite/agent/issues/602

**Comment by Regner** [comment]
Sorry I missed that.

**Comment by lox** [comment]
No problems, I'm sorry you ran into this! Will get out a new beta soon with a fix. In the meantime if you are able, a git upgrade will also fix it.
