### ISSUE TITLE
Support retry w/ backoff for artifact downloads

### ISSUE THREAD

**Issue by lox** [buildkite/agent#608]
The agent should support retry with backoff for artifact downloads to avoid network or rate limiting issues.

**Comment by lox** [comment]
Sorry you're having issues @s01ipsist. We'll see what we can do.

**Comment by williamblevins** [comment]
Not sure if this is explicitly related, but I have a similar issue that happens frequently.

```
2021-08-17 21:00:03 INFO   Found 1 artifacts. Starting to download to: <redacted>
--
  | # Received cancellation signal, interrupting
```

This seems like the same issue. Is there any way to change the https client settings that the `buildkite-agent` uses? Set retry count or include a retry strategy such as exponential backoff.

**Comment by keithduncan** [comment]
Hi @williamblevins I’m not sure what issue you’re describing here, would you be able to get in touch with [Buildkite Support](https://buildkite.com/support) to provide more details and we can help you there?

**Comment by toote** [comment]
I was working on an artifact plugin request to implement this and found that this is already implemented https://github.com/buildkite/agent/blob/00f2048f77c0e2d6808d1f234b339150569b7279/agent/download.go#L58-L59

**Comment by moskyb** [comment]
thanks for pinging this @toote! will close ^_^
