### ISSUE TITLE
Add 'buildkite-runner env' command to get the job's environment variables.

### ISSUE THREAD

**Issue by sander-m** [buildkite/agent#615]
It would be useful if `buildkite-agent` has a command to output its current set of environment variables, without host/system variables mixed in. I am aware of the REST API to do this (https://buildkite.com/docs/rest-api/jobs#get-a-jobs-environment-variables). This API gives the desired functionality but requires an API call for every job we run.

For example, `buildkite-agent env` could return the current Buildkite environment associated to the running job.
```json
{
  "CI": "true",
  "BUILDKITE": "true",
  "BUILDKITE_TAG": "",
  "BUILDKITE_REPO": "git@github.com:my-great-org/my-repo.git",
  "BUILDKITE_BRANCH": "master",
  "BUILDKITE_COMMIT": "a65572555600c07c7ee79a2bd909220e1ca5485b",
  "BUILDKITE_JOB_ID": "bde076a8-bc2c-4fda-9652-10220a56d638",
  "BUILDKITE_COMMAND": "buildkite-agent pipeline upload",
  "BUILDKITE_MESSAGE": ":llama:",
  "BUILDKITE_BUILD_ID": "c4e312cb-e734-4f0a-a5bd-1cac2535c57e",
  "BUILDKITE_BUILD_URL": "https://buildkite.com/my-great-org/my-pipeline/builds/15",
  "BUILDKITE_AGENT_NAME": "ci-1",
  "BUILDKITE_COMMAND": "buildkite-agent pipeline upload",
  "BUILDKITE_BUILD_NUMBER": "15",
  "BUILDKITE_ORGANIZATION_SLUG": "my-great-org",
  "BUILDKITE_PIPELINE_SLUG": "my-pipeline",
  "BUILDKITE_PULL_REQUEST": "false",
  "BUILDKITE_BUILD_CREATOR": "Keith Pitt",
  "BUILDKITE_REPO_SSH_HOST": "github.com",
  "BUILDKITE_ARTIFACT_PATHS": "",
  "BUILDKITE_PIPELINE_PROVIDER": "github",
  "BUILDKITE_BUILD_CREATOR_EMAIL": "keith@buildkite.com",
  "BUILDKITE_AGENT_META_DATA_LOCAL": "true"
}
```

**Comment by lox** [comment]
Yup, I've always wanted this too :) What if it was more like the [meta-data](https://buildkite.com/docs/agent/cli-meta-data) command and allowed `get`/`set`/`list`?

**Comment by lox** [comment]
I've wanted this for passing all env into docker, interested what your use-case is @sander-m.

**Comment by sander-m** [comment]
Same use case @lox, for passing a clean env to Docker, as well as other container types (in our case, Anka Mac containers).

The process environment contains other variables that we don't want to pass to the container. In our Docker builds we are currently applying some filtering before passing the system env using `--env-file`, but this is tricky. We are looking at the REST API as a solution, but an agent command would be preferred.

**Comment by sander-m** [comment]
FYI @DazWorrall

**Comment by DazWorrall** [comment]
Bonus points if we can get the variables
from the agent without an API call somehow - it has them to hand, after all. I thought it could maybe write them to a file, but I guess you try not to make any artifacs on the machine? (the best way to not leave cruft is to not create it in the first place!)

**Comment by lox** [comment]
Yup, if we did this it would be entirely agent local for sure.

**Comment by lox** [comment]
The other option here (and would probably be an intermediate dependency) would be to expose an Agent API (using an agent token vs a personal API token) that gives this information.

**Comment by DazWorrall** [comment]
To sidestep figuring out IPC, a smaller change could be to write the build environment to a file, and expose the path to it in an environment variable (`BUILDKITE_JOB_ENV_FILE`?) - would you accept a patch for that?

**Comment by lox** [comment]
How about a parameter for `buildkite-agent start`?

```bash
buildkite-agent start --write-env-file
```

**Comment by lox** [comment]
We released the env-file in beta 40. I'm going to close this one for now, let us know if you aren't happy with where things ended up @DazWorrall / @sander-m.
