### ISSUE TITLE
Agent artifact upload too agressive with missing artifacts

### ISSUE THREAD

**Issue by bharrisau** [buildkite/agent#619]
I'm running agent v3.0-beta.38.

I'm having issues with multiple artifact targets. These two builds are identical except for the artifacts definition.

```
$ buildkite-agent artifact upload build/playBinary/reports/test/xml/*.xml;build/distributions/playBinary.zip
--
  | 2018-01-15 00:28:12 DEBUG  Debug mode enabled
  | 2018-01-15 00:28:12 DEBUG  Searching for build/playBinary/reports/test/xml/*.xml
  | 2018-01-15 00:28:12 DEBUG  Searching for build/distributions/playBinary.zip
  | 2018-01-15 00:28:12 INFO   No files matched paths: build/playBinary/reports/test/xml/*.xml;build/distributions/playBinary.zip
```

```
buildkite-agent artifact upload build/playBinary/reports/test/xml/*.xml
--
  | 2018-01-15 00:30:31 INFO   Found 3 files that match "build/playBinary/reports/test/xml/*.xml"
  | 2018-01-15 00:30:31 INFO   Creating (0-3)/3 artifacts
  | 2018-01-15 00:30:32 INFO   Uploading artifact 672b7d8b-f7f3-4863-848b-824f3b0cf9b6 build/playBinary/reports/test/xml/TEST-services.1.xml (932 bytes)
  | 2018-01-15 00:30:32 INFO   Uploading artifact 3ac216f4-0bb9-4f3a-890f-9a7925ba1c2a build/playBinary/reports/test/xml/TEST-controllers.1.xml (30005 bytes)
  | 2018-01-15 00:30:32 INFO   Uploading artifact 1057ffe2-21bc-405c-9c0d-a6b5353c60a9 build/playBinary/reports/test/xml/TEST-services.2.xml (619 bytes)
```

I think the issue is here (https://github.com/buildkite/agent/blob/master/agent/artifact_uploader.go#L86). Because the build failed at tests - the second artifact doesn't exist. That line I linked is a `return nil` so if any of the multiple artifacts is missing it will return `nil` for all the given paths. It should probably be a `continue`instead.

**Comment by bharrisau** [comment]
Temporary workaround is to change `build/distributions/playBinary.zip` to a glob `build/distributions/*.zip` so that `zglob` returns an empty list instead of `os.ErrNotExist`.

**Comment by lox** [comment]
Argh, you are absolutely correct @bharrisau. I'll put out a fix asap.

**Comment by lox** [comment]
Thanks for the report @bharrisau, will get out a new release once that PR is reviewed and merged.
