### ISSUE TITLE
libltdl missing, cannot run container inside buildkite/agent:3.0

### ISSUE THREAD

**Issue by hongyuanlei** [buildkite/agent#627]
Alpine based agent has libltdl missing causing: 

```
Error loading shared library libltdl.so.7: No such file or directory (needed by /usr/bin/docker)
--
  | Error relocating /usr/bin/docker: lt_dlclose: symbol not found
  | Error relocating /usr/bin/docker: lt_dlopen: symbol not found
  | Error relocating /usr/bin/docker: lt_dlinit: symbol not found
  | Error relocating /usr/bin/docker: lt_dlexit: symbol not found
  | Error relocating /usr/bin/docker: lt_dlsym: symbol not found

```
This happens when I am trying to run a docker container inside buildkite/agent:3.0. This seems to be a known issue with alpine. Following commands in the agent solve this problem:

`apk update &&  apk upgrade &&  apk add libtool`

Please confirm the problem and the solution(or am I missing something here)

**Comment by lox** [comment]
Hmmm, that is odd. I just ran the test suite on our docker images and I'm not able to replicate. Let me do some investigating. The repository for them is over here: https://github.com/buildkite/docker-buildkite-agent.

**Comment by lox** [comment]
I'm still not able to reproduce this, could you provide the commands that you used?

**Comment by hongyuanlei** [comment]
Thanks for your reply. Here's how I run the buildkite agent:

```
docker run -d --restart always \
           --hostname ${my_buildkite_hostname} \
           -v /tmp/buildkite/buildkite-secret/id_rsa:/root/.ssh/id_rsa \
           -v /tmp/buildkite/config:/root/.ssh/config \
           -v /etc/buildkite-agent:/etc/buildkite-agent \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v /usr/bin/docker:/usr/bin/docker \
           -v /buildkite/builds:/buildkite/builds \
           -v /deployer:/deployer \
           -v /dev/shm:/dev/shm \
           -v /tmp/.m2:/root/.m2 \
            buildkite/agent:3.0
```

**Comment by lox** [comment]
It looks like you are mounting in the docker binary from the host! Any reason for that? It's likely it's dynamically linked, Alpine needs statically linked. 

There is a docker binary in the container already, just drop the `-v /usr/bin/docker:/usr/bin/docker \` and it should work.

**Comment by hongyuanlei** [comment]
Thanks, You are right. It works fine after remove /usr/bin/docker mapping.
