### ISSUE TITLE
Changing repo URL

### ISSUE THREAD

**Issue by dekz** [buildkite/agent#64]
The default `bootstrap.sh` does not support changing git remotes. It will only check the existence of a `.git` folder and not if it is an related repository.

(I changed from github to gitlab with a project, had to destroy all `.git` folders to recover)

Remotes could be grepped from running `git remotes -v` in the clone condition.

**Comment by keithpitt** [comment]
In the 1.0 release of agents, you'll be able to trigger a "clean workspace" from Buildkite. So you'll be able to manually trigger a build, but before it starts, it'll `rm -rf` the checked out directory. That'll be our solution to this until we can do something smarter in the bootstrap.sh file :8ball:
