### ISSUE TITLE
is there a way to delete the old builds?

### ISSUE THREAD

**Issue by chardmd** [buildkite/agent#642]
Our disk size for our build server is just small, around 30GB, currently we have 3 agents running..
is it safe to delete these builds from this location: /var/lib/buildkite-agent/builds/ to free up some space?

If it is safe, what is the correct way to delete it? using hooks?
I am just new to buildkite, so i am trying to explore it to improve the speed of our build process.

**Comment by chardmd** [comment]
currently it is taking us ages, around 40 minutes to build a react project.

**Comment by toolmantim** [comment]
Sorry it’s taking so long! That sounds unusual.

Yep, you’re free to delete the folders inside `builds`.

Another option might be to check your git clean flags config option: https://buildkite.com/docs/agent/configuration#configuration-settings

Maybe there are files building up over time that are gitignored perhaps? Agent 3.0 has a new default for the git clean option: `"-fdqx”` which makes sure every checkout is clean.

Hope that helps!

You’re best to email support@buildkite.com with more details for more help on this. I’ll close this here, but feel free to reply or send an email to support and we’ll help you out.

**Comment by chardmd** [comment]
thanks mate, will take a look on this `git clean` option. cheers!
