### ISSUE TITLE
checkout submodule change

### ISSUE THREAD

**Issue by sschaetz** [buildkite/agent#645]
Hi,

in one of our repositories we changed the submodule remote from one repo to another in addition to changing the submodule hash (the other repo was further ahead).

When running the PR that contains this change on buildkite agent we see behaviour like this:

```
Fetched in submodule path 'ansible-role-airflow', but it did not contain 27511f5bb655b46876341181b23bf9a332c9c143. Direct fetching of that commit failed.
```

Even though the new remote contains that hash the checkout failed. And now for the interesting part: it seems that retrying the steps solves the problem (checkout does not fail). Maybe a combination of clean submodule update etc?

Thanks,
Sebastian

**Comment by keithpitt** [comment]
We're adding retrying to the default checkout behaviour, so this issue should be solved by that change (which is a bit brute-forcey, but works). We'll look into why this would happen though, and maybe add a test to see if we can replicate it.
