### ISSUE TITLE
Misnamed configuration option ssh fingerprint verification

### ISSUE THREAD

**Issue by mbj** [buildkite/agent#649]
This configuration option (and all its forms I'll not list here) is misnamed. It implies BK agent does something "good" as in verifying the integrity of the SSH fingerprint. Which it does not.

Instead it does the *inverse* it blindly accepts whatever fingerprint is scanned and persists it as expected for later use.

So the "secure" setup is to provision the `known_hosts` by yourself and "disabling" the misnamed option to "verify" ssh fingerprints.

I suggest to do a breaking change with BK agent 3 and rename it to something proper.

**Comment by lox** [comment]
We accept the host key the first time, and then throw big warnings if that key changes. I disagree that the feature is misnamed, this is standard approach of https://en.wikipedia.org/wiki/Trust_on_first_use, which is the security model the SSH uses for key interactions. It prevents the majority of MITM attacks, provided the initial exchange is safe. 

Do you have any suggestions other than requiring that folks provide their own `known_hosts` files?

**Comment by mbj** [comment]
> Do you have any suggestions other than requiring that folks provide their own known_hosts files?

No, and this is what we do.

> I disagree that the feature is misnamed

I have to disagree here, if you where to flip this flag you have to provide your own SSH host key, but the key verification (performed by SSH) is rightfully still active.

If I'd follow the name without prior knowledge about the ssh-keyscan BK potentially does, I'd assume this setting would disable the fingerprint verification entirely. Which is obviously a bad idea and not recommended.

What I'm saying here it: The name of the setting does not indicate BK would seed the trust on first use by itself. It indicates (at least to me) ssh host key verifcation can be switched off entirely, which is thankfully not the case.

OT: In a typical CI setup lots of new hosts are booted according to current capacity requirements, and often the entire CI cluster scales to 0. Which means that ssh-keyscan in the defaults happens way to often and there is a good time window to infect the entire fleet with "rouge" mithm host keys.

For my team I disabled ssh-keyscan on agent boot obviously and pre-seed the known hosts. But each time we do a code change related I do have to confirm to my awesome team on reviews: No this setting does NOT disable the hostkey verification, it disables the keyscan on first boot. Which is the main reason I'm raising the issue here. If the option would be named `automatic_ssh_keyscan` it would never raise this question.

**Comment by lox** [comment]
Yup, I think I agree after some thought. Any suggestions for a better name?

**Comment by mbj** [comment]
@lox `ssh_keyscan=yes|no`. Most precise, and does not hide the backend tool and its implied semantics to the user.

**Comment by lox** [comment]
> ssh_keyscan=yes|no

👌🏻

I will make this so.
