### ISSUE TITLE
Bootstrap in agent 3 does not inherit agent configuration on "ssh fingerprint verification"

### ISSUE THREAD

**Issue by mbj** [buildkite/agent#650]
SSH fingerprint verification (a misnamed feature as explained here: #649) configured at the agent level does not get inherited by the default settings to the new go based bootstrap.

You can currently workaroudn this via setting `buildkite-agent bootstrap --ssh-fingerprint-verification=false`. 

If this is expected behavior I expect to change the expectation ;) Took me a while of head scratching till I finally convinced myself to read the source.

**Comment by lox** [comment]
Hmm, I rememeber finding that the ENV var had changed. In the v3 Agent it is `BUILDKITE_AUTO_SSH_FINGERPRINT_VERIFICATION`, but seems to still be passing in `BUILDKITE_SSH_FINGERPRINT_VERIFICATION` to the bootstrap. We will get this fixed, thank you for the report.

**Comment by lox** [comment]
Closed in #671
