### ISSUE TITLE
rpc error: code = 2 desc = containerd: container not found

### ISSUE THREAD

**Issue by andreimc** [buildkite/agent#651]
Running the docker agent v3.0-beta.38

After a few jobs this happens when I try to exec into it. And the agent is no longer available.

How can I monitor the agent health ? Is there a command I can run inside the agent container to know that this particular agent is healthy ?

Kind regards,
Andrei

**Comment by lox** [comment]
That sounds like a docker issue, you should normally be able to exec into your running containers to troubleshoot them: 

```bash
docker exec -it buildkite_agent_1 sh
```

**Comment by lox** [comment]
I'm going to close this one as I don't believe it's related to the agent, but if you are still having issues, drop us an email at support@buildkite.com and we will help @andreimc!
