### ISSUE TITLE
Possible to have BUILDKITE_BRANCH slug?

### ISSUE THREAD

**Issue by shaneog** [buildkite/agent#653]
I use the BUILDKITE_BRANCH to name and tag my Docker images (`${BUILDKITE_BRANCH}-${BUILDKITE_COMMIT:0:7}`), and it turns out that if a branch has a character that is not permitted ( permitted: `a-z0-9-_.`) this leads to a really strange docker-compose error 
```sh
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
```

I would like to continue using the branch name in the Docker tag, so I'm wondering if it's possible to have a new environment variable which would "sluggify" the branch name?

Example:
```sh
BUILDKITE_BRANCH=feature/my-cool-feature
BUILDKITE_BRANCH_SLUG=feature-my-cool-feature
```

If there is a way to do this using hooks I'd be thrilled learn this also!

**Comment by lox** [comment]
Sounds a like a docker crash, might be worth checking the docker daemon logs.

Hmmm, we do this for docker-compose's project names: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/lib/shared.bash#L48-L52. We don't support the replace syntax in our interpolation gear, but you could had a post-checkout hook that set `BUILDKITE_BRANCH_SLUG` for you!

**Comment by shaneog** [comment]
It's definitely the `image-name` that caused the issue, due to the invalid characters.

The docker daemon logs showed the following, which allowed me to figure out the issue (we had some builds failing to start and some working fine).
```
level=error msg="Handler for POST /v1.30/build returned error: invalid reference format"
```

>  you could had a post-checkout hook that set BUILDKITE_BRANCH_SLUG for you!

Thanks, I'll check that out once I get the other issue (multiple build images) sorted 👍
