### ISSUE TITLE
Powershell hook hangs

### ISSUE THREAD

**Issue by gunndabad** [buildkite/agent#656]
I have an environment.ps1 inside my hooks directory which is being invoked but it hangs indefinitely. Agent version: 'buildkite-agent version 3.0-beta.39, build 2105' on Windows Server 2016 Datacenter.

It looks like the generated script is running 'call environment.ps1'. If I run the same command myself it opens the script inside notepad instead of invoking it. I believe powershell scripts have to be run via powershell.exe

**Comment by lox** [comment]
At present this is expected behavior. We support batch or bash scripts. Would like to support powershell, but considerable work needs to be done.

If you don’t care about exporting and capturing ENV, you can run powershell.exe environment.ps1 in your batch hooks.

**Comment by lox** [comment]
That said, we should at least warn to that effect!

**Comment by gunndabad** [comment]
+1 I’d rather have an error than have to debug hanging build!

**Comment by lox** [comment]
Sorry about that @gunndabad! I forgot to lead with that 😓

**Comment by keithpitt** [comment]
@gunndabad we're gonna add that error in for 3.0, and look at adding full powershell support in 3.1 or 4.
