### ISSUE TITLE
Feature request: on failure step

### ISSUE THREAD

**Issue by tarragon** [buildkite/agent#67]
Hi,

It would be great if we could introduce a on-build-failure step so we can add things like notifications or cleanup steps.

Case study: we had some code merged that left some assets that subsequently broke every build after that. I had to (temporarily) add an asset wiper to the bootstrap script to get around this, however we don't generally want to wipe the assets as these take time to generate and don't need to be completely recreated all the time. If there was an on-fail step we could add the asset wiper into this and only do this type of cleanup when a build has a problem. It would of course need to run on the same CI boxes that ran the broken build step(s).

Thanks.

**Comment by kouky** [comment]
@keithpitt yes for conventional `pre` and `post` hook files.

**Comment by keithpitt** [comment]
We have these in master now! Email hello@buildkite.com and I'll give you the lowdown if you're interested :)
