### ISSUE TITLE
Pretty command printing when not in debug mode

### ISSUE THREAD

**Issue by keithpitt** [buildkite/agent#677]
If you've got a command like this:

```
buildkite-agent --version
buildkite-agent artifact download "foo/bar.txt" .
```

You get output like this:

```
$ /bin/bash -e -c "buildkite-agent --version\nbuildkite-agent artifact download \"foo/bar.txt\" ."
```

We should show something more human friendly when in normal mode, and show the raw version when in debug mode.

**Comment by lox** [comment]
Fixed via #708
