### ISSUE TITLE
Docker & Fig implementations not as robust as could be

### ISSUE THREAD

**Issue by ahawkins** [buildkite/agent#69]
Your [docker & fig](https://github.com/buildbox/agent/blob/master/templates/bootstrap.sh#L87-131) related clean up is missing some things. You should use `--rm` here or provide an option to do so. If you do not use `--rm` here containers will build up on the host machine and may cause problems if people ever try `docker rmi`. You may also want to consider adding `-t`. I haven't seen any harm come from this and it will make people's test out put more similar their development environment. You should consider using `-v` here. `-v` will also remove docker volumes. It's unfortunate it's disable by default. Without `-v` the docker VFS will slowly grow over time (depending on how many images have volumes of course). This can create real pain over time because you run out space for when you don't expect it. This problem is definitely more pronounced on CI machines that have high container churn rate. The same issues apply to the default fig commands. `fig run` should most likely have `--rm` and `fig rm` should have `-v` as well. Also if you use `--rm` on `fig run` you do not need to trap and clean up. I offer these suggestion from my experience using docker/fig and various combinations for them for CI things in various arrangements. You maybe able to save less knowledgeable customers some pain.

**Comment by keithpitt** [comment]
Is there anything we should add to our bootstrap.sh to get this issue closed?

**Comment by dekz** [comment]
Probably adding a `fig rm -v` [here](https://github.com/buildkite/agent/blob/master/templates/bootstrap.sh#L161). This will remove `VOLUMES` as well as images created. 

So for every postgres a Volume is made (if you use the default postgres Dockerfile). This Volume only gets cleaned up with a `-v` to `fig rm`. If you have a lot of ephemeral postgres containers then without this option your disk will fill quickly.

On the other hand, there is probably someone out there who might not want this behaviour. 

IMO it's probably a good default to have.

Tim has done a bit of work on cleaning up at the end of fig runs anyway which now looks to be out of the beta and into master ( #63 ) . Which I believe at the time of this issue, wasn't public.

**Comment by keithpitt** [comment]
What would be an argument for not having it? (Just so I can understand if someone asks me) :P
