### ISSUE TITLE
Is there a way to detect if one of the steps was cancelled?

### ISSUE THREAD

**Issue by marcelas** [buildkite/agent#693]
I have a reporting step in the end of my pipeline that notifies our PR system if the build was successful or not. Right now, I set a metadata a step has failed. I am doing that on a post command script. But if the step times out, it gets auto-cancelled and no post scripts run. 
I would like to have a way to know if the build is successful so far, when running the notify step. So I would like to know if there is any hooks on cancelled that I could use or if any other environment variable or matadata is available at other steps.
Any help is appreciated.

**Comment by lox** [comment]
Hi @marcelas, are you able to drop us an email to support@buildkite.com? We try and keep the issue tracker for bugs and development!
