### ISSUE TITLE
debug output is going to STDOUT rather than STDERR

### ISSUE THREAD

**Issue by cap10morgan** [buildkite/agent#71]
Any logging or debug-type output from `buildbox-agent` commands should go to STDERR so that var setting (`MY_VAR=$(buildbox-agent build-data get my-var`) and redirection (`buildbox-agent build-data get my-var > my-var.txt`) still work as expected and the logging / debug output still shows up on the console running the script.

**Comment by keithpitt** [comment]
Ah yes, this is a good call. I'll make sure `v1.0` of the agents have this. Thanks!
