### ISSUE TITLE
Sometimes the buildkite agent will throw `No pipeline with slug "{pipeline-name}" could be found` error when one pipeline triggers another pipeline.

### ISSUE THREAD

**Issue by hongyuanlei** [buildkite/agent#710]
The triggered pipeline name "RW-homepage"

In pipeline.yml, I use lowercase pipeline name, such as `trigger: 'rw-homepage'`

But, sometimes the buildkite agent will throw `No pipeline with slug "rw-homepage" could be found` error when one pipeline triggers another pipeline.

**Comment by lox** [comment]
Could you drop us an email at hello@buildkite.com with an example failing build @hongyuanlei? This isn't related to the agent, so I'm going to close this here and we'll follow up over email!
