### ISSUE TITLE
Windows installer script exits with error if you don't use the `$path` option

### ISSUE THREAD

**Issue by keithpitt** [buildkite/agent#716]
https://github.com/buildkite/agent/blob/master/install.ps1#L70

If you don't use the $path option, then the $binDir never get's added to the path, so calling `buildkite-agent --version` from outside the bin dir throws an error.

I tried to fix it, but I don't know Powershell - and I was going around in circles :|

**Comment by keithpitt** [comment]
Also, is https://github.com/buildkite/agent/blob/master/install.ps1#L6 (the $path thing) supposed to be configurable?

**Comment by lox** [comment]
Sorry, I sneaky fixed this on master.
