### ISSUE TITLE
S3 artifact upload should support server-side encryption

### ISSUE THREAD

**Issue by carldjohnston** [buildkite/agent#727]
Hi Buildkiters,

We want to enforce server-side encryption for `s3:PutObject` calls by our Buildkite Agents, however the `buildkite-agent artifact upload` command doesn't support specifying SSE.

This might be a deal-breaker choosing Buildkite for some organisations who require encryption at rest in public cloud.

It would be great if the agent cli could support this, either through arguments and/or environment variables.

Thanks!

Carl

**Comment by lox** [comment]
Thanks, sounds like a great enhancement. Will see what is involved.

**Comment by venky999** [comment]
any update on this

**Comment by venky999** [comment]
looks like its implemented here https://github.com/buildkite/agent/pull/1072

**Comment by yob** [comment]
looks like you're right, thanks for flagging that we'd missed closing this.

On caveat that might be obvious but I'll mention anyway - the solution on #1072 is only for artifacts uploaded to a customer owned s3 bucket. I believe artifacts uploaded to the default buildkite-owned S3 bucket aren't encrypted at rest.
