### ISSUE TITLE
Add documentation for plugin ordering

### ISSUE THREAD

**Issue by mgoodings** [buildkite/agent#728]
Can you please add documentation on how to ensure plugins run in a specific order.

**Comment by lox** [comment]
Sure thing. I think it's probably a bug that ordering of plugins is random. YAML technically has unordered maps and Golang randomizes the traversal order, but I think this ends up being very surprising to users.

**Comment by lox** [comment]
Sorry it bit you @mgoodings!

**Comment by rcoup** [comment]
@lox yeah, would be nice to have them run in the defined order (even if plugins became a list?) for pre-command & command, and _reversed_ in post-command.

**Comment by toolmantim** [comment]
👋🏼 Plugins now run in the order they’re defined in the plugin.yml, even tho it’s a map, so you should have predictable behavior here now!

@rcoup what made you end up here on this issue? Are you seeing a problem?

**Comment by rcoup** [comment]
@toolmantim I have a support question open with Keith, and when I was digging about for a workaround stumbled across this and realised I'd written stuff that was apparently working by coincidence.

**Comment by toolmantim** [comment]
Sorry for closing this issue! I'll be fixing this the documentation shortly 🙌🏼

**Comment by toolmantim** [comment]
@rcoup ah, yes unfortunately there's no way to do hooks that run after plugin hooks… aside from another plugin itself. They are run in the order you defined in the YAML map though, so maybe that works for you?

**Comment by rcoup** [comment]
Yeah, just plotting my own evil plugins :)

Do the plugins run in reverse order _after_ the command step? (ie. inside out)

**Comment by toolmantim** [comment]
Sorry, nope they're not @rcoup. They're run in the same order before and after the command step:
https://github.com/buildkite/agent/blob/master/bootstrap/bootstrap.go#L516-L530
