### ISSUE TITLE
v3.0.0 is picking up PATH differently than v2.6.10

### ISSUE THREAD

**Issue by tobyjsullivan** [buildkite/agent#730]
We are having an issue with our test servers running v3.0.0 of `buildkite-agent`. The issue is that our test code seems to be executed with a different $PATH value as compared to v2. 

When we provision our build servers with `buildkite-agent=2.6.10-2219`, our code is executed with same path as the user under which the agent is running (configured in `.bashrc`). However, if we provision with the latest buildkite-agent (3.0.0), our tests use some other value for PATH. 

Our specific problem is that our setup requires that `/usr/local/bin` has higher precedence in the path than `/usr/bin` so that we can be guaranteed the correct versions of various tools are being used. We configure this by provisioning a `buildkite-agent` user with a `.bashrc` file. `buildkite-agent` runs under this user. In v2 the PATH specified in `.bashrc` is pick up but in v3 it is not.

Our test agents are running Ubuntu 14.04 trusty. We are installing `buildkite-agent` with `apt`.

1. Is there a more appropriate way we should be setting the PATH?
2. If not, I think this could be considered a bug.

**Comment by lox** [comment]
@tobyjsullivan are you able to set `PATH` in your global `environment` hook? Are you able to drop an email to support@buildkite.com with a failing build? I'd be interested to look into the different PATH values.

**Comment by tobyjsullivan** [comment]
@lox Thanks for the tip. It looks like adding `/usr/local/bin` to the path in the environment hook should do the trick (will take a couple hours to verify). We were setting some paths in there already but not this one.

We did some more investigation and found that the PATH value we were getting looked like this:

```
PATH="[paths set in environment hook]:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin"
```

Notice that `/usr/bin` is in there twice and so was getting precedence over `/usr/local/bin`. 

I'm not sure how to verify, but I suspect this has to do with us having `BUILDKITE_BIN_PATH=/usr/bin` as an environment variable on the pipeline. I don't think we're setting this so I assume it's the default. My guess is how this is added to the path changed between 2.6.10 and 3.0.0. Maybe not a bug, per se, but certainly an unexpected change in behaviour.

**Comment by tobyjsullivan** [comment]
I have confirmed that setting the PATH via global environment hook solved the problem. Thanks again.
