### ISSUE TITLE
Unable to target agent version 2 with yum

### ISSUE THREAD

**Issue by jnewbigin** [buildkite/agent#731]
On CentOS-7/yum/rpm, 
since the release of agent version 3, we can not easily track the latest agent in the version 2 series.
It would be great if there was a virtual provides which included the major version number.
ie:
`rpm -qp buildkite-agent-*.rpm --provides`
```
buildkite-agent = 2.6.10-2219
buildkite-agent(x86-64) = 2.6.10-2219
buildkite-agent-2 = 2.6.10-2219
```

Then in theory we can do
`yum install buildkite-agent-2`

For now I am using a workaround
`yum -y install buildkite-agent --enablerepo=buildkite-agent --exclude=buildkite-agent-3\*`
but that will break one day when version 4 comes out :-)

**Comment by lox** [comment]
That sounds like something that might be a good idea! I'm afraid I'm not very familiar with RPM/YUM, any suggestions on how we'd add provides to https://github.com/buildkite/agent/blob/a58fe98264a095aea87ebf89735432e9be49668a/scripts/build-rpm-package.sh?

**Comment by jnewbigin** [comment]
I'll have a look. Never used `fpm` before. How hard can it be :-)

**Comment by lox** [comment]
Well, we got the PR merged, which will let you pin to `buildkite-agent-3`, but still need to get it into a stable release.

**Comment by keithduncan** [comment]
Looks like this issue has been addressed! We don’t offer support for version 2 any more 😅 but let us know if the RPM/YUM packaging is working as expected :bow:
