### ISSUE TITLE
Support for shell input redirection.

### ISSUE THREAD

**Issue by uri-canva** [buildkite/agent#735]
`buildkite-agent` doesn't seem to support reading config from an input anymore:
```
$ touch ~/t.yaml
$ buildkite-agent pipeline upload --replace <~/t.yaml
2018-04-18 05:11:12 INFO   Searching for pipeline config...
2018-04-18 05:11:12 FATAL  Could not find a default pipeline configuration file. See `buildkite-agent pipeline upload --help` for more information.
$ cat ~/t.yaml | buildkite-agent pipeline upload --replace
2018-04-18 05:11:26 INFO   Reading pipeline config from STDIN
2018-04-18 05:11:26 FATAL  Config file is empty
```
Note the two different error messages. The first one complains it couldn't find the config, the second one complains the config is empty. This used to work with the previous version, so it might have something to do with this change:

v2.6.10:
https://github.com/buildkite/agent/blob/ce612fc8406f7de031c671478c380cedf4399700/clicommand/pipeline_upload.go#L103

v3.0.1:
https://github.com/buildkite/agent/blob/3ac2abb9d4afd691c5f5acc408139aff4c26a1e4/clicommand/pipeline_upload.go#L106

**Comment by lox** [comment]
🤔So looks like the first one isn't correctly detecting stdin, but the second is working correctly? I'm assuming OS is linux, in am interactive bash shell?

Tests are at https://github.com/buildkite/agent/blob/3ac2abb9d4afd691c5f5acc408139aff4c26a1e4/stdin/main_test.go. It's been very tricky to get working correctly across platforms, I'll do some, further testing.

**Comment by uri-canva** [comment]
The test I ran on 3.0.1 is on Linux, interactive bash shell. It was working before on 2.6.10 with a non-interactive shell, never tried with an interactive shell there.

**Comment by tigris** [comment]
+1 - we have a large number of existing pipelines using the `< filename.yml` syntax, so this is blocking our upgrade to v3
