### ISSUE TITLE
How to trigger a build step for branch deletion

### ISSUE THREAD

**Issue by snktagarwal** [buildkite/agent#739]
I am using buildkite to do Google Protobufs.

Protobuf (repo1) -> lang1-genproto (repo2), lang2-genproto(repo3) ....

When team creates experimental branch in protobut it gets reflected in the genproto repos too.

I am able to handle creation well, but how do I handle branch deletion? I want to trigger a cascading deletion of branches when that happens. So:

Branch del in Protobuf (repo1) -> branch del in lang1-genproto (repo2) .... so on.

If my question is not clear I am happy to share the config files for details.

**Comment by lox** [comment]
Hi @snktagarwal, I'm afraid this one slipped through the cracks, mind dropping us an email at support@buildkite.com if you still have questions around this?
