### ISSUE TITLE
Invalid access token when attempting to annotate a build

### ISSUE THREAD

**Issue by ox** [buildkite/agent#743]
I've been playing with the new annotation feature in `buildkite-agent` but I cannot seem to get it to authenticate with the v3 API. First I found it curious that the agent needed the `--agent-access-token` flag set (I thought it would pull it from the config), then I found it strange that the `Authorization:` header was either not being set or shown in the console when using the `--debug --debug-http` flags. I then attempted to make a manual request with telnet, setting the `Authorization:` header myself, but still got an error:

```
{"message": "Invalid access token"}
```

The access token I am using is directly from `/etc/buildkite-agent/buildkite-agent.cfg`. Is there another access token I should be using? Any idea what could be the issue?

I'm sending the request like so:

```
$ openssl s_client -connect agent.buildkite.com:443
...
... SSL handshake
...
---
POST /v3/jobs/<job id>/annotations HTTP/1.1
Host: agent.buildkite.com
User-Agent: buildkite-agent/3.0.1.2336 (linux; amd64)
Content-Length: 38
Content-Type: application/json
Authorization: Token <token>
Accept-Encoding: identity

{"body":"hello world","context":"random","style":"info"}
```

**Comment by toolmantim** [comment]
Hey @ox! Sorry you’re having trouble using the annotation gear.

Are you running the command from inside a build step? If so, it should pick up all the required env vars, including the agent session token. Or maybe you’re running it in Docker (or similar) and the env vars aren’t being passed through?

You’ll need to pass through:

- `BUILDKITE_AGENT_ACCESS_TOKEN`
- `BUILDKITE_JOB_ID`

Let us know if you need help doing that.

If you’re trying to create an annotation outside of a build step, you’ll need to use the GraphQL API.

**Comment by ox** [comment]
Ahh interesting. I was running it as the buildkite-agent user on the build machine we have set up. Is it absolutely required to pass through the args as environment variables or will the `buildkite-agent annotate` flags do the job? I attempted to call the `buildkite-agent`, outside of a build step, like so:

```
 echo "hello world" | buildkite-agent annotate --job <job id> --style info  --agent-access-token "<access token>" --debug-http --debug
``` 

and got:

```401 Invalid access token```

**Comment by toolmantim** [comment]
Sorry yeah, I think that’s a different token. It requires a session (access) token which the agent sets up internally and exposes as the environment variable, whereas “agent start” requires a registration token (the one from your agent config file).

I can see how the docs and naming made this confusing.

If you want to call it outside of a build step, you’ll need to use the GraphQL API sorry.

**Comment by lox** [comment]
Going to close this for now, let us know if you still need help @ox!
