### ISSUE TITLE
`command` hook exit codes are squelched

### ISSUE THREAD

**Issue by ticky** [buildkite/agent#754]
It appears that [exit codes generated from `command` hooks](https://github.com/buildkite/agent/blob/fc99bcc46cb8bc94f0e15cac0a8020ad7d821bea/bootstrap/bootstrap.go#L147-L154) (such as in the docker-compose plugin) are swallowed up rather than propagating all the way out to the job.

**Comment by arturopie** [comment]
@ticky @lox Would downgrading to a specific agent version fix this problem for us?

**Comment by seantsb** [comment]
Found the same when using multiple commands; workaround for us was using `&&` and one-lining it as opposed to having multiple lines of commands. Idk if that's applicable to you but figured I'd mention it.

**Comment by lox** [comment]
@seantsb that sounds like you need `set -o pipefail`? That's standard shell behaviour.

**Comment by seantsb** [comment]
This is in the `pipeline.yml` file, right? I tried
```bash
sh -c 'set -o pipefail; npm run lint && npm run flow'
```
but get
```
sh: 1: set: Illegal option -o pipefail
```

**Comment by ticky** [comment]
`sh` might not be bash on your system!  try `bash -c` instead! 😄

**Comment by seantsb** [comment]
Ahh good call! So doing 
```yaml
      - bash -c 'set -o pipefail; npm run lint && npm run flow'
      - python ...
```
where `npm run flow` fails and exits with code 2 did not cause the container to fail, as I would've hoped.

**Comment by ticky** [comment]
that configuration will only apply _within_ the bash process, python is being called from the default shell

**Comment by seantsb** [comment]
ah makes sense. Do you know if there's a way to set it globally, so I can line-split and still have it fail?

Also I'd assumed my issue was the same as what this Issue was about but I guess you're referencing hooks as opposed to commands?

**Comment by ticky** [comment]
The best option would be to make your steps call out to a build script which sets it - we do this ourselves plenty, [here’s an example in our frontend repo](https://github.com/buildkite/frontend/blob/be5ae89a92c080a80a72f642840a5b4d42b896a9/.buildkite/steps/webpack.sh#L1-L2).

Hooks are generally shell scripts, and this issue is relating specifically to the fact their exit status as a whole is disregarded, I believe this is different from the fact that the default shell behaviour doesn’t consider intermediate commands’ nonzero exit codes to be an error.

**Comment by seantsb** [comment]
Cool thanks! We'll have to decide if it's more readable to have a one-liner with the 3 commands, or break it off into its own file, which seem to be the two options. It's a relatively small pipeline.yml file so far (51 lines). Thanks again for the pointers!

**Comment by lox** [comment]
@seantsb the other option is something like this:

```yaml
steps:
  - label: "Run multiple commands"
     command: |
     set -o pipefail
     npm run lint
     npm run flow
     python ....
```

**Comment by lox** [comment]
But yeah, nothing to do with this bug 😅

**Comment by seantsb** [comment]
Hm yea then I get
```

Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"set\": executable file not found in $PATH": unknown
--
  | /etc/buildkite-agent/plugins/github-com-buildkite-plugins-docker-compose-buildkite-plugin-v2-2-0/hooks/../commands/run.sh: line 128: npm: command not found

```
again

**Comment by seantsb** [comment]
If there's documentation I'm missing somewhere I'm happy to check that out too!
