### ISSUE TITLE
Support `%hostname` in agent metadata

### ISSUE THREAD

**Issue by therealbnut** [buildkite/agent#773]
We want to add hostname to the agent metadata, so we can target individual troublesome machines. We ideally don’t want to have to change the configuration on each machine to achieve this.

**User story**

We had a troublesome machine over the weekend, but didn’t have any way to target it directly (we have ssh disabled). This isn't the first time this has happened, but its the first time it has happened on the weekend and the people affected didn't know the hack workarounds.

In the end we had to run a script on all machines, and filter for the specific one with `BUILDKITE_AGENT_NAME`, and get it to update the agent's config file. We could not just turn off the agent because it has a launch daemon that keeps it running.

**Comment by lox** [comment]
This is a great idea!

**Comment by lox** [comment]
Now that we have #791, I'm going to close this one. Please let me know if that doesn't solve your problem @therealbnut.

**Comment by lox** [comment]
It's in v3.3.0 @therealbnut! https://github.com/buildkite/agent/releases/tag/v3.3.0
