### ISSUE TITLE
legacy docker-compose builds with multiple commands broken in v3

### ISSUE THREAD

**Issue by samritchie** [buildkite/agent#778]
I’ve just upgraded my agent to v3 and one of my builds started failing. It looks like it’s related to the fact this build has multiple commands.

v2 command line spake thusly:

`docker-compose -f docker-compose.yml -p buildkitefec68bada1ad4879ae4d1dbbd4662a47 run build ./buildkite-script-fec68bad-a1ad-4879-ae4d-1dbbd4662a47`

v3 command line instead opines:

`docker-compose -f docker-compose.yml -p buildkited221e3131ae146dcb11bbe68498d0b03 run build "rm -rf dist\nrm -rf elm-stuff\nrm -rf node_modules\nnpm install\nnpm run build"`

to which docker-compose wittily responds:

`ERROR: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"rm -rf dist\\nrm -rf elm-stuff\\nrm -rf node_modules\\nnpm install\\nnpm run build\": executable file not found in $PATH": unknown`

I’ve added a build script to the repo as a workaround and it’s running. I _think_ just dropping the quotes from the command (and `&&`ing together the commands) should work, but I don’t speak fluent docker-compose and could be wrong.

**Comment by samritchie** [comment]
Should add it’s configured with `BUILDKITE_DOCKER_COMPOSE_CONTAINER`, not the plugin - that’s what I meant by legacy.

**Comment by toolmantim** [comment]
Ah, we should probably `bash -c` the commands and separate them with `&&` - the old support assumed you had bash anyway!

**Comment by samritchie** [comment]
Hmm, build commands with parameters seem to be broken as well - 

```
docker-compose -f docker-compose.yml -p buildkite61bb284ee7d942ebb9f23aca3caac25b run build "./gradlew --no-daemon --stacktrace clean app:assembleRelease"
--
  | Creating network "buildkite61bb284ee7d942ebb9f23aca3caac25b_default" with the default driver
  | ERROR: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./gradlew --no-daemon --stacktrace clean app:assembleRelease\": stat ./gradlew --no-daemon --stacktrace clean app:assembleRelease: no such file or directory": unknown
```

It definitely looks like the quotes shouldn’t be there - I think it would work if it was running 

`docker-compose -f docker-compose.yml -p buildkite61bb284ee7d942ebb9f23aca3caac25b run build ./gradlew --no-daemon --stacktrace clean app:assembleRelease`

I can’t directly list `bash -c` in the build commands either for the same reason.

**Comment by chesterlau** [comment]
When will this be fix?
How to force the removing of quotes when running docker-compose?

pipeline.yml:
steps:
  - name: ":node:"
    command: "npm test"

error:

docker-compose -f docker-compose.yml -p buildkitexxxxxxxxxxxxxxxxx run app "npm test"
--
  | Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \":npm test:\": executable file not

**Comment by keithduncan** [comment]
> Ah, we should probably `bash -c` the commands and separate them with `&&` - the old support assumed you had bash anyway!

I’ve been examining this issue and I *think* it is fixed today though I haven’t spent the time to delve into the history and changes here.

The [default shell](https://github.com/buildkite/agent/blob/bd1678c104f1fcd16471bc7938a98c83e5880249/clicommand/agent_start.go#L127-L139) we use specifies `-e` which should exit the shell process if any of the shell-spawned commands exit with a non-zero code. This should do away with the need for the `&&` joining of commands, and `-c` supports newline separated commands which is what we end up passing in as a single ARGV to the user configurable shell.

I’m afraid any window to fix a lingering incompatibility with v2 is likely missed now 😅 as it may introduce further incompatibilities with the v3 method! If things are still not working for folks who ran into this issue, please let us know and we’ll suggest alternatives to get things going :bow:
