### ISSUE TITLE
Add support for deleting annotations

### ISSUE THREAD

**Issue by queimadus** [buildkite/agent#779]
One can create annotations within the build using `buildkite-agent annotate` but there is no way to delete a annotation.

Use case:
I make use of this to show a summary of failed tests but I'd like to delete the annotation once I retry that step and it passes with success.

**Comment by lox** [comment]
Thanks for this @queimadus, we're tracking feature requests for Buildkite over at https://forum.buildkite.community/c/feature-requests, if this is something you still run into, could I trouble you to create a thread there?
