### ISSUE TITLE
Access command exit-code in a plugin's post-command step

### ISSUE THREAD

**Issue by queimadus** [buildkite/agent#784]
Inject an env var with the previous step exit code, or a env var with the exit code for each step (e.g. `PRE_COMMAND_EXIT_CODE`, `COMMAND_EXIT_CODE`, `POST_COMMAND_EXIT_CODE`)

**Comment by lox** [comment]
We set `BUILDKITE_COMMAND_EXIT_STATUS ` currently:

https://github.com/buildkite/agent/blob/a9645cdfe3698270cd3b69afca6ae054c53b8dfc/bootstrap/bootstrap.go#L908

Does that solve your problem?

**Comment by queimadus** [comment]
Perfect 👍 
Sorry I opened the issue but I searched the docs and couldn't find anything.

**Comment by lox** [comment]
No problems!
