### ISSUE TITLE
Killing agents running in launchd

### ISSUE THREAD

**Issue by jerrymarino** [buildkite/agent#802]
I'm really enjoying the ability to kill agents through the API and Web interface! This feature is a core component of my workflow.

Unfortunately, it doesn't work when the agent is running under `launchd`.  Despite killing the agent from the API or Website, `launchd` will automatically respawn the agent. Do you have any suggestions about how to fix this?

**Comment by lox** [comment]
Could you tell us a bit about your workflow @jerrymarino? Killing agents remotely doesn't work in a few contexts unfortunately, I'm interested to hear how you use it.

**Comment by jerrymarino** [comment]
Hey @lox - the primarily use case is when a host becomes corrupted, it may need be disconnected altogether.

Unfortunately this can require manual oversight and correction, so the ability to terminate rouge agents from Web / API is still needed even if the agent is daemonized.

**Comment by lox** [comment]
Gotcha! I think https://github.com/buildkite/homebrew-buildkite/pull/12 should fix this!

**Comment by jerrymarino** [comment]
@lox that will work good - thanks for fixing 👏
