### ISSUE TITLE
Feature Request: Expand / Collapse All Steps in Build

### ISSUE THREAD

**Issue by jgavris** [buildkite/agent#808]
Sometimes I open a bunch of build logs, and they get pretty long. I have to do a lot of scrolling to get back to where I want to go (or use the back button). This would be along the same lines as the existing 'expand / collapse groups' but for build steps.

<img width="504" alt="screen shot 2018-08-09 at 5 47 09 pm" src="https://user-images.githubusercontent.com/178749/43927678-52dc1020-9bfc-11e8-98de-81febe78775a.png">

**Comment by lox** [comment]
👋 We're moving feature requests over to https://forum.buildkite.community/c/feature-requests, if this is still something that you run into a lot, could I trouble you to create a thread over there?
