### ISSUE TITLE
Feature request: Option to use bash as shell interpreter for commands run in Windows agents.

### ISSUE THREAD

**Issue by frodera** [buildkite/agent#809]
Hook commands can be written as bash scripts and BuildKite agent will execute them via `bash.exe` (through a *Git for Windows* package installed in the machine) as long as they [do not include an extension](https://github.com/buildkite/agent/blob/202e4483eafa5b38f3a23bd5de8011b4537c4109/bootstrap/hook.go#L99).

Would it be possible to allow the same for regular `command`s in pipelines' steps? [It looks like](https://github.com/buildkite/agent/blob/6f3b7ceb80a6df0650052224eef70b61e599acb9/bootstrap/bootstrap.go#L1030) the agent directly goes for `CMD.exe`  as the shell for commands in Windows.
Being able to use bash scripting makes life so much easier for those unfamiliar with Windows batch/cmd programs.

**Comment by lox** [comment]
Hi @frodera 👋 The agent has a `shell` configuration (see https://buildkite.com/docs/agent/v3/configuration) which it will use to determine what shell to invoke commands with. You should be able to specify bash in there for windows!

**Comment by frodera** [comment]
Worked like a charm. Thanks @lox 👍
