### ISSUE TITLE
Windows agent got stuck on a job, but Buildkite doesn't realize it

### ISSUE THREAD

**Issue by philwo** [buildkite/agent#821]
Hi Buildkite :)

We had an interesting failure today on CI:
- 2018-09-06, Buildkite assigns a job that usually runs for ~30 minutes to one of our Windows agents.
- More than 24h later (umhm, what? :D), the agent runs into trouble checking in with Buildkite and reports "Problem with getting job state b4810698-6910-400c-8d80-26dcd76a2ed5 (GET https://agent.buildkite.com/v3/jobs/b4810698-6910-400c-8d80-26dcd76a2ed5: 502)" and "...: 500 Internal Server Error" in its log.
- The agent's never gonna give you up, so it dutifully retries its requests for two more days (!?), until it realizes that Buildkite is just not going to give a positive response.
- The agent accepts its new life and doesn't complain anymore in the log. It just sits there, doing nothing.
- I don't know how to get the job page from the job UUID above, so I'm not sure what happened to the job that the agent was actually processing when it got into this weird state. But: Buildkite thinks the agent is *totally fine* and tries to assign a new job to it. It reports: "Assigned to agent, waiting for it to accept", but the agent never does. Hours later, Buildkite still just can't believe that that agent is not going to accept the job and retries over and over, restarting the stopwatch that counts the time that it's already in this state every minute. (The "Today at 11:26:00 PM: Assigned to agent, waiting for it to accept" state that you can see in the screenshot below was just replaced every minute, e.g. it went from "Today at 11:24:00 PM" to "Today at 11:25:00 PM" and so on.)

What went wrong:
- The Buildkite agent somehow lost contact with Buildkite and instead of terminating, which would have triggered a reboot of the VM thanks to "disconnect-after-job=true" and our service monitor script and the thing getting back into a good state, it just sat there.
- Buildkite didn't realize that something is wrong with that agent, even after it didn't accept an assigned job for hours.

What would have been cool:
- Buildkite agent realizes that something is wrong and terminates (which would trigger a service restart or machine reboot, getting it back into a good state).
- Buildkite scheduler realizes that the agent is somehow broken and just picks another available agent instead of retrying forever with the same agent.

Our environment:
Buildkite agent 3.4.0.
Windows Server version 1803 Datacenter Core
Running on Google Compute Engine

Additional data:

The job that tried to use a broken agent for 5 hours and not giving up:
https://buildkite.com/bazel/google-bazel-presubmit/builds/8897#
<img width="773" alt="screen shot 2018-09-11 at 23 46 01" src="https://user-images.githubusercontent.com/504652/45389678-e90bbc00-b61c-11e8-8f6e-01a1ea8b5e65.png">

The agent mentioned in this bug report:
<img width="1352" alt="screen shot 2018-09-11 at 23 24 01" src="https://user-images.githubusercontent.com/504652/45389596-a813a780-b61c-11e8-8340-d46f7663d24f.png">

Another agent who had a similar problem roughly at the same time:
<img width="1352" alt="screen shot 2018-09-11 at 23 22 17" src="https://user-images.githubusercontent.com/504652/45389589-a4802080-b61c-11e8-83b9-188343243811.png">

**Comment by philwo** [comment]
FYI @buchgr

**Comment by lox** [comment]
Hey @philwo, sorry you ran into this! We will investigate and update.

**Comment by lox** [comment]
This is a tricky one, it looks like the job was accepted, but then during execution the API returned an error whilst checking on job state. What should happen is this should keep checking the API, but stop when the process it's running stops. I'm wondering what happened to the process in this case. 

We've made a heap of process related fixes for Windows in recent releases (especially in the upcoming 3.8), I might close this one out and see if it re-surfaces with the new releases if that is ok!
