### ISSUE TITLE
Submodule problems with diverse repository hosts

### ISSUE THREAD

**Issue by jam13** [buildkite/agent#825]
I still seem to be hitting this problem (https://github.com/buildkite/agent/issues/503) on latest buildkite agent (3.4.0).

I've got a Bitbucket repo that has a single submodule from GitHub. When it tries to update the submodules it prompts to accept the GitHub keys and so prevents the build from continuing.

It doesn't fail on every build because an agent instance might have added the GitHub keys to wellknown through another pipeline job, but on newly deployed instances (AWS stack) it fails every time.

Looking at the code, the problem seems to be that it uses the following command to get the submodule URLs which it then uses to update the known_hosts:

```
git submodule foreach --recursive git ls-remote --get-url
```

As this is run _before_ the submodules are initialised, the foreach always returns empty and so no URLs are returned.

_Originally posted by @jam13 in https://github.com/buildkite/agent/issues/503#issuecomment-426307393_

**Comment by jam13** [comment]
Note that I have a workaround for this at the moment of using `git://github.com/` form submodule references to avoid SSH, however this would only work with public repos.

**Comment by lox** [comment]
Thanks for letting us know and sorry you ran into this issue! I'll have a look and see if we can re-arrange things to prevent this happening.
