### ISSUE TITLE
Add command line args (showing env var defaults) for `artifact` commands

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#83]
This way we can list the output of `--help` in the docs, and it will expose the command line args and ENV vars that need to be set for AWS custom bucket upload.

**Comment by toolmantim** [comment]
Also: should we use `AWS_` vars, when everything else is `BUILDKITE`? Is there much benefit to `AWS_`?

**Comment by keithpitt** [comment]
AWS is required by the AWS golang lib

**Comment by keithpitt** [comment]
Also AWS is actually optional if you're on an ec2 box and you have the IAM stuff setup right

**Comment by toolmantim** [comment]
Gotcha. Okay, this is what the guide will look like…

Add `pre-command` hook that exports the secrets into your build environment:

```bash
#!/usr/bin/env bash

export AWS_SECRET_ACCESS_KEY=xxx
export AWS_ACCESS_KEY_ID=xxx
export AWS_S3_ACL=private
export BUILDKITE_ARTIFACT_UPLOAD_DESTINATION="s3://name-of-your-s3-bucket/$BUILDKITE_JOB_ID"
```

I couldn't find a good hook to choose, so I just chose `pre-command`. Is that the right one you reckon, or should we have a `pre-build` or `build-setup` or `build-started`, which is where people can export all their secrets.

Currently the hooks are:

* pre-checkout
* checkout
* post-checkout
* pre-command
* command
* post-command

**Comment by keithpitt** [comment]
Maybe we should have a `pre-artifact` and `post-artifact` as well? Even though technically `pre-artifact` and `post-command` are the same, at least they have more context as to what may be inside the hook?

**Comment by keithpitt** [comment]
Also, @orj suggested we change our auth gear to also look for the `BUILDKITE_` versions (at least, use those first, then default to the `AWS_` ones.

**Comment by keithpitt** [comment]
Btw, we now support:

```bash
export BUILDKITE_SECRET_ACCESS_KEY=xxx
export BUILDKITE_ACCESS_KEY_ID=xxx
export BUILDKITE_S3_ACL=private
```

And I've also added a `pre-artifact` hook: https://github.com/buildkite/agent/blob/master/templates/bootstrap.sh#L344 that will run if an artifact upload path has been specified.

**Comment by keithpitt** [comment]
Going to close this for now as you can add the bits you need in a `pre-artifact` block.
