### ISSUE TITLE
Images on Docker Hub reporting vulnerabilities

### ISSUE THREAD

**Issue by conorgil** [buildkite/agent#841]
The docker images tagged `latest` and `stable` report as vulnerable on [Docker Hub](https://hub.docker.com/r/buildkite/agent/tags/).

**Comment by lox** [comment]
Thanks for letting us know @conorgil. Honestly Docker Hub is in a terrible state. They are supposed to have discontinued that "security scanning" and there is no way to contact them for assistance or make queries about things like this. 

I've looked through the issues, and half of them are spurious (for instance jq is reported as vulnerable but has been patched by alpine) and the others are tenuous. 

I'm going to update to Alpine 3.8 in that image and I will file an issue in https://github.com/docker/hub-feedback/issues and hope someone over there notices.

**Comment by lox** [comment]
For instance, see: https://hub.docker.com/r/library/ubuntu/tags/🤔

**Comment by lox** [comment]
This is resolved now!
