### ISSUE TITLE
Feature Request: [Periodic Builds] Add option to skip scheduling a build if one is active

### ISSUE THREAD

**Issue by mikezucc** [buildkite/agent#852]
Provide option in Periodic settings: Prevent scheduling a new build for periodic builds if there is a build already started.

Currently you can either skip previously scheduled builds or cancel existing ones, however you cant skip scheduling a new build if there is an active one. For example, if the build time somehow exceeds the scheduling period, then you have perpetually canceling builds. Ideally this shouldnt happen.

However it would be very efficient if the scheduling process can more so assure that there is an active build and if not, to start one.

**Comment by lox** [comment]
Hi Mike! Thanks for the suggestion, could I trouble you to lodge this in https://forum.buildkite.community/c/feature-requests?
