### ISSUE TITLE
Access token appears in the job environment when set using an environment variable

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#897]
If you configure the agent registration token using the `BUILDKITE_AGENT_TOKEN` environment variable, it then becomes available in the job environment. This doesn't happen if you start the agent with the explicit `--token` argument.

We should probably remove `BUILDKITE_AGENT_TOKEN` from the job environment (leaving only the existing `BUILDKITE_AGENT_ACCESS_TOKEN` session token).

**Comment by lox** [comment]
Ugh, yeah that is no good, let's remove it.

**Comment by lox** [comment]
Turns our #902 didn't fix the issue, as the env doesn't come from the job environment, it comes from the shell environment inherited by the agent.

**Comment by toolmantim** [comment]
Can we just set the value to "" no matter what, so we always override whatever value might be present?

**Comment by lox** [comment]
I'll get a fix for this out now @toolmantim

**Comment by lox** [comment]
This was fixed in v3.9.0.
