### ISSUE TITLE
AWS authentication credentials/ENV vars should be buildkite-specific.

### ISSUE THREAD

**Issue by orj** [buildkite/agent#90]
s3_uploader should use BUILDKITE_AWS_ env vars to feed into:

    auth, err := aws.GetAuth("", "", "", time.Time{})

Rather than providing empty strings, which causes the aws library to use its own env var definitions.  

Reasoning: All buildkite environment vars should be prefixed with BUILDKITE_.  This namespacing avoids any potential collision with user scripts/environment.

**Comment by keithpitt** [comment]
Fixed in https://github.com/buildkite/agent/commit/4a27a37ccf1a61d6a8d7109f1790169b5d490fea

**Comment by keithpitt** [comment]
We know support the more specific`BUILDKITE_S3_ACCESS_KEY` and `BUILDKITE_S3_SECRET_KEY`, then we default back to the global `AWS_ACCESS_KEY` and `AWS_SECRET_KEY` if the `BUILDKITE_` ones aren't present.
