### ISSUE TITLE
Agent option to always run build as clean checkout

### ISSUE THREAD

**Issue by regner** [buildkite/agent#903]
We are currently running agent version 3.7.0. We would love the ability to configure our agents in such a way that the checkout folder gets nuked before or after every build. We find the git checkout command to be insufficient.

We have some projects that are very sensitive to files being left over and some of those files are artifacts of the build process. Those files are also part of the .gitignore file so they don't get checked in, but that also means they are ignored by all the git cleanup commands.

Is there a way, or could one be added, that causes the buildkite agent to delete the checkout folder before or after every build?

Even if this wasn't an issue I would personally prefer that. We don't mind the extra time to checkout the repo and would prefer the better guarantees for consistency in our builds.

**Comment by regner** [comment]
My apologies, I didn't know that environment variable was a thing. I also attempted some Google searches but failed to notice/understand/see that -x flag. I will give both of those a shot and see what happens.

Thank you for the quick response. Closing for now.

**Comment by lox** [comment]
No problems, let us know how you go!

**Comment by regner** [comment]
Just as a quick heads up, because I thought I was crazy, that option is not listed anywhere on the Builtekite agent configuration: https://buildkite.com/docs/agent/v3/configuration

**Comment by lox** [comment]
`git-clean-flags` is, and `BUILDKITE_CLEAN_CHECKOUT` is on https://buildkite.com/docs/pipelines/environment-variables.

**Comment by regner** [comment]
Aaaaaaaah, it is in the pipeline configuration not the agent configuration. Makes sense. Thank you once again. :)

**Comment by lox** [comment]
Yup, apologies, I should have been clearer! It's one of those features that exists as a work around for broken checkouts, so we tend not to surface in the docs super clearly because we'd generally prefer to fix that cause of the broken checkout!

**Comment by lox** [comment]
You can also use https://github.com/buildkite-plugins/git-clean-buildkite-plugin to override git clean flags for just a single step.
