### ISSUE TITLE
Jobs no longer receiving SIGTERM on cancellation/timeout

### ISSUE THREAD

**Issue by stevendanna** [buildkite/agent#922]
We recently upgraded to v3.8.4 and noticed that our jobs are no longer receiving SIGTERM when they are cancelled or time out.  We've confirmed this with a simple script that traps only SIGTERM and prints to standard output.  When the job hits the timeout, we get no print statement.

Previously we were trapping SIGTERM to perform various cleanups as documented here:

https://buildkite.com/docs/agent/v3#signal-handling

Via a quick reading of the code we think this bug was potentially introduced here:

https://github.com/buildkite/agent/commit/56c34ba1bae731b143b50ffb7cf15683286bcd4c

since calling cancel() on an exec.Command object will result in it getting SIGKILL'd.  Note this is based on a rather quick reading of the code. The code has changed a bit on master, but a quick reading of master leads us to believe that master likely has the same behavior but we haven't confirmed this.

We can likely work around this by moving our cleanup routines into the pre-exit hook; however, it seems like either the SIGTERM behavior should be restored or the documentation should be updated.

**Comment by lox** [comment]
Thanks for the heads up @stevendanna, we've been doing a fair bit of internal work to get the signal handling right for windows/linux and cancellation. You raise an excellent point that I hadn't considered. Our view of the contract is that the SIGTERM/SIGKILL is sent to the sub-process that we run each job in (we call it the bootstrap). That then executes hooks and commands, around which the signal contract hasn't ever been very clear, and we should do a better job of documenting that distinction.

What you are doing with signal handling and trapping a SIGTERM in your scripts for cleanup is entirely reasonable. My apologies for breaking it! We hate doing that, especially in a minor version. Whilst moving your cleanup logic sounds like the sensible thing to do, we'll also fix the behaviour in the next release.
