### ISSUE TITLE
Regression in logs of commands which don't output newlines

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#929]
If you have a long running command that doesn't output a new line, nothing gets output in the build log until the command ends:

```yml
steps:
   - command: |
       while true; do
         sleep 0.1
         printf "."
       done
```

<img width="971" alt="image" src="https://user-images.githubusercontent.com/153/53520214-3925fe80-3b29-11e9-991d-cad0167de79f.png">

```
$ buildkite-agent --version
buildkite-agent version 3.8.4, build 2783
```

It appears you can't sed/tr/awk your way around the problem either:
https://gist.github.com/toolmantim/f4801f3ed2321b156105ff5e97fdbfbb

I believe we used to do some type of flushing, so I did a binary search of tests from `buildkite/agent:2` to the current release, and it appears to have regressed in [v3.6.0](https://github.com/buildkite/agent/releases/tag/v3.6.0) as [v3.5.4](https://github.com/buildkite/agent/releases/tag/v3.5.4) worked AOK:

<img width="984" alt="image" src="https://user-images.githubusercontent.com/153/53520395-ae91cf00-3b29-11e9-9bd7-011f1a350818.png">

**Comment by tekumara** [comment]
Thanks for raising this, I also tried the `tr` workaround on my build to no avail.

**Comment by lox** [comment]
Good find! I’ll get this solved immediately.

**Comment by lox** [comment]
Ok, I tracked this down. Previously we didn't buffer lines UNLESS you had the `--timestamp-lines` setting set. After 3.6.0 we buffer lines regardless. 

I could put it back like it was, but it would be nice to do something better.

**Comment by toolmantim** [comment]
Are you thinking of trying to get both non-line-buffered output and line timestamping working?

**Comment by lox** [comment]
Yeah, possibly. In the short term I might just fix the regression.
