### ISSUE TITLE
Running process in the background

### ISSUE THREAD

**Issue by rena2damas** [buildkite/agent#939]
In my pipeline, I am trying to spawn new agents. To do so, my environment hook looks like this:

```bash
#!/bin/bash

set -uo pipefail

buildkite-agent start --config buildkite-agent.cfg
```

This works fine. A new agent is now running in the same machine of the currently running agent. However, the pipeline keeps hanging as the process is running. Therefore I make it run as a background process, like this: ```buildkite-agent start --config buildkite-agent.cfg &```

Then I do ```ps aux | grep buildkite-agent```within the hook and the new agent is there. But as soon as the execution of the hook ends, so does the agent I just spawn. The process does not seem to live after the full execution of the hook. Is this an expected behavior? If so, is there a workaround for this?

**Comment by lox** [comment]
This sounds brain-bending! Can you tell us a bit more about what problem you are trying to solve with dynamically spawning agents from another agent?

> The process does not seem to live after the full execution of the hook. Is this an expected behavior? If so, is there a workaround for this?

This is how shells work! When they exit they send a `SIGHUP` to child processes. If you REALLY wanted the spawned agents to survive you could use the `[nohup](https://en.wikipedia.org/wiki/Nohup)` utility that is designed for specifically this usecase.

**Comment by rena2damas** [comment]
So basically, I don't want each user to be able to run every command they want within the agent. And whitelisting these commands is also an exhaustive amount of work. Therefore, in the environments hook, I dynamically spawn an agent running under the user. That way, the user privileges are left to the OS the agent is running and not to the agent itself. That was my idea..

**Comment by rena2damas** [comment]
I am now using the nohup. It works. I now have a running agent spawned in the pipeline creation step. The I then have to steps:

1. I upload an artifact in the new agent
2. I download the artifact in the new agent

However I get an error in the second step:
```FATAL  Missing artifact download path. See: `buildkite-agent artifact download --help````

According to the documentation, "_The buildkite-agent artifact download command only works within the context of a running build_" which is true, these two steps are part of the same build.

**Comment by lox** [comment]
That's a really interesting idea @rena2damas! I'd never considered dropping user privileges per-job.

Sounds like it would be a perfect fit for the [`bootstrap-script`](buildkite-agent bootstrap script) configuration option. The agent listens for work and then runs a sub-process for each job. This used to be a bash script, but it's now a sub-command of the `buildkite-agent` binary. This makes for a perfect extension point for a wrapper around the whole job execution process.

Say if you had a script like `drop-agent-privs.sh` that you set as the `bootstrap-script`, you could do something like:

```
#!/bin/bash
set -euo pipefail

case "$BUILDKITE_BUILD_CREATOR_EMAIL" in
"lachlan@buildkite.com")
  echo "~~~ Executing bootstrap as lachlan"
  sudo -u lachlan -g buildkite-agent --preserve-env -- buildkite-agent bootstrap
  ;;
*)
  echo "No user found for $BUILDKITE_BUILD_CREATOR_EMAIL"
  exit 1
  ;;
esac
```

I hope that helps!

**Comment by lox** [comment]
Another trick along these lines is running each bootstrap inside a docker container, which you could apply a similar approach to:

https://github.com/buildkite/docker-bootstrap-example

**Comment by toolmantim** [comment]
There's also another doc I just remembered, which might be of use @rena2damas:
https://buildkite.com/docs/agent/v3/securing#customizing-the-bootstrap

If this is a useful approach for some situations, it could be a good example to add to that Securing your Buildkite Agent guide. We'll see how you go!

**Comment by rena2damas** [comment]
Hi guys,

thank you so much for the suggestions. I ended up following the suggestion from @lox . I wrapped the bootstrap execution in my own script. I then have a ```bootstrap-wrapper``` script:

```bash
sudo -u $username -E /bin/bash -i -c buildkite-agent bootstrap
```

**Comment by toolmantim** [comment]
Is it something we should consider adding to the "Securing" guide do you think?

**Comment by rena2damas** [comment]
I found this approach particularly useful if you want to run your job with the same privileges as the user that is triggering the pipeline. That way you free yourself from whitelisting the shell commands the user allowed to run in the machine the agent is running on.

**Comment by rena2damas** [comment]
Guys, do come up with a way to identify which step is running in runtime? Let's say that in my own bootstrap script ```bootstrap-wrapper``` (the same mentioned above), I want to perform a certain action only if the step running is the pipeline submission. I went through the environment variables and I did not find anything useful except for the ```BUILDKITE_COMMAND```.

```bash
[...]
if [ "${BUILDKITE_COMMAND}" == "buildkite-agent pipeline upload .buildkite/pipeline.yml" ]; then
    # Some other action
fi
[...]
```

Is there any prettier way to check which of the steps is currently running?

**Comment by toolmantim** [comment]
There is an `id` attribute you can set on a step, and it becomes available as the env var `BUILDKITE_STEP_IDENTIFIER` — perhaps that’s better suited?

**Comment by rena2damas** [comment]
That seems perfect :) thank you

**Comment by rena2damas** [comment]
Hey @toolmantim . I just gave it a try to that ```id``` attribute. That would have been great if you could not assign the same ```id``` to different steps. The thing is that I want to make skip command validation only in the pipeline build step. So a pseudo code that represents this, would be like:

```
if this is pipeline build step:
   skip command validation
otherwise
    validate commands whitelisting
```

If I use ```id``` to run that verification, then another user can simply add the same ```id``` to be able to skip command validation process in order to run eventual malicious code. Shouldn't it be ensured that ```id``` is unique among the steps of the pipeline?
