### ISSUE TITLE
Docker-compose support

### ISSUE THREAD

**Issue by Maxim-Filimonov** [buildkite/agent#94]
Docker-compose is getting close to release.
https://github.com/docker/fig/releases
I'm using it in dev/ test already and some features like external_link are very useful. Need to modify bootstrap.sh manually for now but it would be great if elastic agent supported it from get go.

**Comment by keithpitt** [comment]
I tried to find installation instructions, but they all seem to point to fig still?

**Comment by toolmantim** [comment]
@keithpitt https://github.com/docker/fig/releases

**Comment by Maxim-Filimonov** [comment]
My bootstrap file which works with docker-compose -> https://gist.github.com/Maxim-Filimonov/e96f75e5fa2953571db4

**Comment by keithpitt** [comment]
We've shipped this into the beta agents now! :star2:
