### ISSUE TITLE
how to prevent logging with color?

### ISSUE THREAD

**Issue by nhooyr** [buildkite/agent#941]
Don't want colored logs for the agent on GKE as the logs go to stackdriver and you see the raw escape codes everywhere.

<img width="756" alt="screen shot 2019-03-05 at 8 12 09 pm" src="https://user-images.githubusercontent.com/10180857/53848606-f928a680-3f82-11e9-9d51-2afa89c3d589.png">

**Comment by lox** [comment]
Did you check our docs? There is a no-color option.

**Comment by nhooyr** [comment]
I did, must have missed it.

Why not automatically enable color based on whether stdout is a tty or not?

**Comment by lox** [comment]
All good! Apologies for terse reply. 

> Why not automatically enable color based on whether stderr is a tty or not?

Good question, seems like a good idea! Things get a bit complicated with tty support cross-platform, but we could probably do that for linux/mac.

**Comment by keithpitt** [comment]
> Why not automatically enable color based on whether stderr is a tty or not?

We do!

https://github.com/buildkite/agent/blob/6f4f79022d349c7f17facea2770e76f02e7d2548/logger/log.go#L51-L63

```sh
buildkite-agent start --config .buildkite-agent.cfg &> no-color.log
```

I looked at the output in `no-color.log` and it didn't have any colours. Where as if I run `buildkite-agent start` in a terminal, I get colours.

Sounds like maybe the thing on your end @nhooyr is reporting itself as a TTY. As far as the agent is concerned, I think it's doing the right thing!

**Comment by nhooyr** [comment]
Interesting. Thanks for looking into this for me.

**Comment by nhooyr** [comment]
Ah, kubernetes runs each app with a TTY so that when you run `kubectl logs mypod` in a terminal, you can see colors.

I guess that does make sense. Unfortunate with Stackdriver though, I think I'll file an issue with them to remove the escape codes.
