### ISSUE TITLE
Provide an interface for the buildkite api to enable Mocking

### ISSUE THREAD

**Issue by wolfeidau** [buildkite/agent#947]
I know I am probably the only person testing this but it would be handy. 

This would relate to `Client` in github.com/buildkite/agent/blob/master/api/buildkite.go.

Requires a refactor of all consumers similar to what you have recently done, but rather than return in the struct, you return the interface.

Would enable better unit testing inside the agent as well if you choose to do that.

Cheers 😄

**Comment by lox** [comment]
Fixed in https://github.com/buildkite/agent/pull/1020
