### ISSUE TITLE
Artifact path normalization

### ISSUE THREAD

**Issue by underscorediscovery** [buildkite/agent#96]
Paths from Windows agent (1.0-beta.12.317) display in the dash board as `\` while other agents (mac/linux) display as `/`. The real problem is trying to download those from an agent - an artifact path to match `files/*` fails to find Windows built artifacts that would match the glob/path. I think all paths should be normalized to / as to retain parity/consistency at all times. 

Reproduce :
- add build step with artifact path in pipeline such as `files/*`
- observe artifacts from a Windows agent are uploaded just fine
- add second build step (with wait for previous steps)
- try download the artifacts from the step using `buildkite-agent build-artifact download "files/*"`
- result:
  - Windows agent artifacts not found
  - Other agents artifacts found

Also tested:
- Tried `files\*` and `files\\*`, no luck.

**Comment by underscorediscovery** [comment]
Newer fixes by @toolmantim have solved the downloads being found by the tool. \o/ 

However, while on a unix machine downloading the artifacts from Windows agents, it results in files only found by `\`. This is ok, but the resulting disk-file being named as `path\to\item.file` literally, as the filename.

**Comment by samritchie** [comment]
+1. I’ve observed the following additional behaviour:

For uploads:

* `files/**/*` only matches one level deep, i.e. `files/foo/bar.txt`, but not `files/foo/bar/baz.txt`
* `files\**\*` matches the entire tree

For downloads:

* `files\**\*` seems to match all artifacts
* `files\foo\*` doesn’t match anything

Looks like I’m currently running 2.0.3.761.

**Comment by keithpitt** [comment]
We've done some testing with Artifacts and the latest v3 release of the agent, and everything seems to be working A-OK! We're gonna close this for now. If you see any further issues, hit us up!
