### ISSUE TITLE
Need to be able to spin up an agent without it accepting other jobs

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#97]
If you have an army of CI agents running builds targeting `*`, and you want to set up a CI agent on a special machine with `--meta-data deploy=true`, there's no way to have it only accept deploy jobs… it'll just start accidentally picking up the other CI jobs (and failing them) upsetting existing team members.

We need some mechanism to force an agent to only accept jobs with matching meta-data, so you can safely set up a new set of agents and have a play. Something like:

```buildkite-agent start --only-jobs-with-meta-data ci=true```

**Comment by dgoodlad** [comment]
:hand: we're in exactly this position. Switching to a white-list of acceptable jobs/metadata would be huge.

**Comment by keithpitt** [comment]
Perhaps another way of doing this, is instead of defining `*` in the Buildkite UI, you define: `deploy!=true`, so it'll match any agent where deploy isn't there?

**Comment by dgoodlad** [comment]
@keithpitt sure, but what if you forget? It's far safer to be able to whitelist acceptable jobs, rather than to accidentally run full builds which may not even be possible on this agent.

What you've got is a system where agents can :hand: and make the representation that they are capable of building jobs requiring specific properties *and* all other default jobs. I'd like to exclude the defaults.

**Comment by keithpitt** [comment]
The same could be said for the `--only-jobs-with-meta-data` approach. You could forget to add that.

If you do, you gotta SSH back into the machine, shut down the agent, edit config files, and boot back up. If you have a fleet of these things, then it becomes even more hard. If you've got some sort of provisioning stuff in the mix, then you'd have to do all that jazz as well.

Or you go: "doh!", edit the step to be `deploy!=true`, which would match every other agent but `deploy=true` then carry on!

I'm not saying that `-only-jobs-with-meta-data ` is a bad approach, just throwing another one out there from fresh eyes.

**Comment by dgoodlad** [comment]
I *could* forget, true, but when setting up a build agent I'm far more aware of what its capabilities are. I'm in a better position to rationally evaluate what types of jobs can run on that agent. On the other hand, when setting up a build job, you need to know every possible piece of metadata that you have to exclude, you're bound to make a mistake.

This is really a situation for larger groups of teams, or for much longer-running projects that build up assumptions over time. So I can see how it doesn't make much sense when seen through the eyes of a new or small team, but it makes a ton more sense if you think about it from the perspective of a team where most people do not know the majority of the ins-and-outs of what other teams are up to.

**Comment by toolmantim** [comment]
With Dave he would need to edit every step of every existing project just to boot up a new deploy agent for a new job :(

**Comment by keithpitt** [comment]
Oh, we shipped this! Let me know if you want more details.
