### ISSUE TITLE
Rename BUILDKITE_AGENT_META_DATA_* to BUILDKITE_AGENT_TAG_*

### ISSUE THREAD

**Issue by harrietgrace** [buildkite/agent#975]
Given that these are set with the `--tags` flag, could we update the individual tag env vars to match? 😊 

e.g. If we set `tagname=tagvalue`, it would be great to have  `BUILDKITE_AGENT_TAG_TAGNAME=tagvalue` instead of `BUILDKITE_AGENT_META_DATA_TAGNAME=tagvalue` 👌🏻

**Comment by lox** [comment]
I'd love to, although this one is set server side and will be tough to do in a backwards compatible way!
