### ISSUE TITLE
Tests pass when docker fails to pull container

### ISSUE THREAD

**Issue by andreeaflorescu** [buildkite/agent#981]
I am not sure if this is the right place for reporting the problem. Please re-direct me to the appropriate repository in that case.

Due to a wrong permission configuration on the host where the buildkite-agent is running, the agent fails to pull and run a Docker Container. Even though the test step was not run due to the permission error, the test is marked as passed. The behaviour that I was expecting would be for the test to fail.

For further details, please check  the output of "build-gnu-arm": https://buildkite.com/rust-vmm/kvm-ioctls-ci/builds/103#eac8048e-1d0b-4fa6-9432-8781d2463753

**Comment by lox** [comment]
Apologies for the slow response, I completely missed this one. Mind dropping us an email to support@buildkite.com if you are still seeing the issue?
