### ISSUE TITLE
Regression: Content-type for *.log files not text/plain anymore

### ISSUE THREAD

**Issue by blueimp** [buildkite/agent#983]
Hi,
with [this commit (Use the nginx mime type list)](https://github.com/buildkite/agent/commit/a97a56255736cef94e01801828458ea5001c176f) the mapping of `*.log` files to a content-type of `text/plain` was removed.
This means with the latest agent, `*.log` files will be uploaded as `binary/octet-stream` and not be directly viewable anymore in the browser, prompting a download dialog instead.
Since `*.log` files are likely very common artifact targets that benefit from direct in-browser viewing, any chance we could get the old behavior back?

**Comment by blueimp** [comment]
Related, I saw in the [pull request](https://github.com/buildkite/agent/pull/912) that contained the commit, a new `--content-type` argument was added to the `artifact upload` command.
If something like this would be made available for `artifact_paths` in the `pipeline.yml`, e.g. an environment variable or another YAML property of additional mappings, that could also work.

**Comment by blueimp** [comment]
There might be another reason than the changed mime type list.
We also don't get the correct content-type anymore for `*.mp4` files - although they're still in the mime type mapping with `video/mp4`, they're stored with the fallback `binary/octet-stream`.

**Comment by blueimp** [comment]
We're using a custom S3 bucket for the artifacts, not sure if this affects the default Buildkite artifact storage as well.

**Comment by toolmantim** [comment]
Sorry you hit this! Did you know which agent version used the correct content type, and which agent version did not?

Because  this is a custom artifact bucket, the web UI doesn’t do any content-type overrides. And so the agent change in #912 most probably introduced a change, as I believe it uses an entirely new mime type list.

**Comment by blueimp** [comment]
Yes, the agent version was definitely older and did not include the changes from that pull request yet, we were on a v2 of Buildkite-elastic-ci-stack, which is now on v4.
Can dig in old builds to find out the exact agent versions if that helps.

What I don’t understand though is why mp4 files also don’t get the correct content-type, since they are still part of the mime list.

png files still work fine (they get the correct image/png type), while log and mp4 are stored as binary/octet-stream in our artifacts s3 bucket.

**Comment by blueimp** [comment]
The previous Buildkite agent version we used was `v3.0-beta.39` (on `buildkite-aws-stack=v2.3.5`).

The current Buildkite agent version we use is `v3.10.3` (on `buildkite-aws-stack=v4.3.1`).

**Comment by lox** [comment]
Happy to add back a content-type for `log` @blueimp, sorry about that regression. Would happily accept a PR, or I'll put one together when I get a chance. 

Like you, I'm perplexed why mp4 wouldn't be getting a content-type. 🤔

**Comment by blueimp** [comment]
Thanks @lox !
If I find the time next week, I'll happily try to put together a PR. ☺️

**Comment by blueimp** [comment]
I'm starting to test with a local agent.
The first thing I can report is that this issue affects custom artifact buckets only, everything works as expected with the default buildkite artifact storage.

**Comment by blueimp** [comment]
I cannot reproduce the issue on Buildkite agent `3.10.4` (built straight from current `master` branch) running on a macOS Mojave host - all tested filetypes get stored with their proper mime types (`mp4` as `video/mp4`, `log` as `text/plain; charset=utf-8`, `png` as `image/png`).

**Comment by blueimp** [comment]
I couldn't reproduce the issue on Buildkite agent `3.10.3` (built from the tagged release) running on macOS Mojave either.
However I understand now why this issue only affects certain hosts.

The mime fallback call [here](https://github.com/buildkite/agent/blob/master/mime/mime.go#L12) uses the native Golang [mime.TypeByExtension](https://golang.org/pkg/mime/#TypeByExtension), which uses the following short default list:

```go
var builtinTypesLower = map[string]string{
	".css":  "text/css; charset=utf-8",
	".gif":  "image/gif",
	".htm":  "text/html; charset=utf-8",
	".html": "text/html; charset=utf-8",
	".jpg":  "image/jpeg",
	".js":   "application/javascript",
	".wasm": "application/wasm",
	".pdf":  "application/pdf",
	".png":  "image/png",
	".svg":  "image/svg+xml",
	".xml":  "text/xml; charset=utf-8",
}
```

However this list is augmented  based on the following rules:
> The built-in table is small but on unix it is augmented by the local system's mime.types file(s) if available under one or more of these names:
> 
> /etc/mime.types
> /etc/apache2/mime.types
> /etc/apache/mime.types
> On Windows, MIME types are extracted from the registry.

That I could not reproduce this on a macOS host is due to the default Apache2 installation on macOS, which provides `/etc/apache2/mime.type` that comes with mime mappings for all the tested files.

A quick fix therefore is to provide additional mime mappings in one of the system's mime.types locations.

That information would probably be helpful to have in the documentation, although I'm not sure what the right location is.

It probably still makes sense to augment the buildkite agent default mapping, maybe a combination between `nginx` and `apache` mime mappings.

**Comment by blueimp** [comment]
The reason for `mp4` files not getting the correct mime type is that the mime list in https://github.com/buildkite/agent/blob/master/mime/mime.go was never applied, since the file extensions did not start with a leading dot.

The pull request https://github.com/buildkite/agent/pull/988 fixes this issue, combines the mime type from both Apache and Nginx sources and adds a generator function for easy updates that can be run via `go generate`.

**Comment by lox** [comment]
Really appreciate you digging into this @blueimp, apologies for the face-palm worthy bug.

**Comment by blueimp** [comment]
No need to apologize, glad I could contribute!

At my current job we're very happy customers of buildkite as well as happy users of [aws-vault](https://github.com/99designs/aws-vault), so thanks for your products! ☺️
