### ISSUE TITLE
Agents with `--disconnect-after-idle-timeout` and `--spawn` don't terminate as expected

### ISSUE THREAD

**Issue by lucas044** [buildkite/agent#985]
Using the new lambda scaler v0.4.0 with the new termination and graceful shutdown scripts.

For example, if I have 8 agents running on a single instance using the multiple agents per instance functionality, when the inactive or cooldown period elapses and only 1 of those agents actually did any work. 

7 of the inactive ones will shutdown, but the 1 that had done some work had its idle timer reset.

This leaves my instance in a state where I have a big box such as a t3.2xlarge or something like that with only a single agent running and is not a very good efficient use of resources or cost.

What we need to overcome this, is if I have multiple agents on a single instance for the instance to ONLY shutdown if ALL the agents have reached the inactive period. Its an all or nothing kind of deal.
Because now it looks like I only have 1 available agent and then the lambda function will scale my ASG up another instance, so I'd now have 9 total buildkite agents running but over 2 instances.

You could also get very unlucky and fill out the max_size on your autoscaling group with only a single agent per instance.

Hopefully that made sense.

**Comment by lox** [comment]
I think the right behaviour is to modify the agent so that `--disconnect-after-idle-timeout` waits for all agents to have been idle for the timeout before shutdown.

**Comment by lucas044** [comment]
Example with 8 agents running on a single beefy instance:

Just to add, since the lambda has the `AGENTS_PER_INSTANCE` variable tied into it if you have a large amount of agents running on a single instance and all but one a shut down. You have to query more than that `AGENTS_PER_INSTANCE` number for your lambda to think it needs to scale again. So you actually just get stuck with potentially 1 agent and it doesn't scale cause it thinks it has the required agents to run.

**Comment by lox** [comment]
Haven't forgotten about this, just struggling to figure out how to implement it. Currently our [AgentPool](https://github.com/buildkite/agent/blob/3764cec0bbd193ff4a349f0a0d3cbdd63d8dcc10/agent/agent_pool.go) doesn't know about the internal semantics of [AgentWorkers](https://github.com/buildkite/agent/blob/master/agent/agent_worker.go) that run in it.

**Comment by lucas044** [comment]
Nah you're alright. Just thought I'd add more data to this issue :+1:
