### ISSUE TITLE
Systemd restarts agent stopped with disconnect-after-idle-timeout

### ISSUE THREAD

**Issue by moensch** [buildkite/agent#986]
An agent stopped due to `disconnect-after-idle-timeout` is automatically restarted by systemd. Here is my syslog:

```
Apr 13 00:08:18 ip-10-37-0-214 buildkite-agent: #033[38;5;48m2019-04-13 00:08:18 INFO  #033[0m #033[38;5;243mi-0bf46b89e7e89ab60#033[0m #033[0mAgent has been idle for 300 seconds#033[0m
Apr 13 00:08:18 ip-10-37-0-214 buildkite-agent: #033[38;5;48m2019-04-13 00:08:18 INFO  #033[0m #033[38;5;243mi-0bf46b89e7e89ab60#033[0m #033[0mGracefully stopping agent. Since there is no job running, the agent will disconnect immediately#033[0m
Apr 13 00:08:18 ip-10-37-0-214 buildkite-agent: #033[38;5;48m2019-04-13 00:08:18 INFO  #033[0m #033[38;5;243mi-0bf46b89e7e89ab60#033[0m #033[0mDisconnecting...#033[0m
[snip]
Apr 13 00:08:18 ip-10-37-0-214 systemd: buildkite-agent.service: control process exited, code=exited status=1
Apr 13 00:08:18 ip-10-37-0-214 systemd: Unit buildkite-agent.service entered failed state.
Apr 13 00:08:18 ip-10-37-0-214 systemd: buildkite-agent.service failed.
Apr 13 00:08:24 ip-10-37-0-214 systemd: buildkite-agent.service holdoff time over, scheduling restart.
Apr 13 00:08:24 ip-10-37-0-214 systemd: Started Buildkite Agent.
Apr 13 00:08:24 ip-10-37-0-214 systemd: Starting Buildkite Agent...
[snip]
Apr 13 00:08:24 ip-10-37-0-214 buildkite-agent: #033[0m
Apr 13 00:08:24 ip-10-37-0-214 buildkite-agent: #033[1;36m2019-04-13 00:08:24 NOTICE#033[0m #033[0mStarting buildkite-agent v3.10.4 with PID: 6096#033[0m
```

**Comment by toolmantim** [comment]
How have you configured your systemd unit @moensch?

**Comment by lox** [comment]
I think it's just a standard Elastic Stack, I asked @moensch to drop an issue in here for context on a Slack discussion in #aws-vault.

**Comment by moensch** [comment]
It is not a default elastic stack (building our own AMI and deploying the lambdas using terraform). So the systemd unit is just the default the RPM ships.

```
[Unit]
Description=Buildkite Agent
Documentation=https://buildkite.com/agent
After=syslog.target
After=network.target

[Service]
Type=simple
User=buildkite-agent
Environment=HOME=/var/lib/buildkite-agent
ExecStart=/usr/bin/buildkite-agent start
RestartSec=5
Restart=on-failure
RestartForceExitStatus=SIGPIPE
TimeoutStartSec=10
TimeoutStopSec=0
KillMode=process

[Install]
WantedBy=multi-user.target
DefaultInstance=1
```

Since I am hand rolling this, I now also dropped this config in addition:
```
[Service]
ExecStopPost=/usr/local/bin/terminate-instance true
ExecStopPost=/usr/sbin/poweroff
```

**Comment by jeremiahsnapp** [comment]
@moensch I might be wrong but I think you need to have `sudo` in front of that `poweroff` like you see here.

https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/linux/conf/bin/bk-install-elastic-stack.sh#L142

 If I'm right then I think what's happening is the `poweroff` is failing to run so systemd's `Restart=on-failure` is going ahead and starting the service back up again. I'm pretty sure I saw similar unexpected behavior recently while working with a custom AMI and elastic stack. In fact my issue was that I have AMIs for many different platforms that have `sudo` in different locations so I ended up doing this.

```
[Service]
ExecStopPost=/usr/local/bin/terminate-instance true
ExecStopPost=$(command -v sudo) poweroff
```

**Comment by lox** [comment]
Does the above resolve your issues @moensch?

**Comment by lox** [comment]
Closing for now @moensch, let us know if that above didn't fix things for you.
