### ISSUE TITLE
Using Rust with Buildkite

### ISSUE THREAD

**Issue by NicholasLYang** [buildkite/agent#997]
Hi,

I'm running into some issues with using Rust in Buildkite. Namely, I'm not sure how I can install Rust for the buildkite-agent. Rust installations are user specific by default and buildkite-agent doesn't have a home directory. I've tried installing to /var/lib/buildkite-agent, but that hasn't been super successful. 

Unfortunately, using a docker container is also tricky since I need nightly, which the default rust docker image doesn't provide. I'm attempting a workaround, but I'd appreciate it if I could just install nightly onto the agent.

Thanks,
Nicholas

**Comment by lox** [comment]
Hey @NicholasLYang, the buildkite-agent binary can certainly be run as a specific user with a home directory. Check out how we install it in the [AWS Elastic Stack](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/linux/scripts/install-buildkite-agent.sh#L10-L18). 

When builds run, they will inherit the environment of the shell they run in, but they won't automatically do things like source ~/.bashrc and friends. If you are running your agent with something like `systemd`, you might need to set up the environment yourself in an [environment hook](https://buildkite.com/docs/agent/v3/hooks).

That said, relying on things installed on the host ends up being sub-optimal, as it's hard to reproduce locally and it's tough to test version updates. Looks like there is a rust nightly docker image https://hub.docker.com/r/rustlang/rust, perhaps that might work for you?

If you've got follow up questions, drop us an email at hello@buildkite.com, we try and keep this repository focused on bugs in the agent!

**Comment by NicholasLYang** [comment]
Hey Lachlan,

Thanks for the quick response! I appreciate the help. Unfortunately we're having problems with the nightly docker image and linking libclang. I'll be sure to check out having buildkite-agent be run as a specific user. 

Is there any place I can post public questions? I'd be happy to send an email, but if other people have similar issues, it might be good to have a public forum so they can see prior solutions.

**Comment by lox** [comment]
Sure thing, you can post on our Discourse forum: https://forum.buildkite.community/c/help
